### ISSUE TITLE
Request support for the MOES single-pole no-neutral switch

### ISSUE THREAD

**Issue by nprez83** [make-all/tuya-local#1060]
# Log Message

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 1540, in detect_available_dps
    data = self.status()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 1505, in status
    data = self._send_receive(payload, 0, getresponse=(not nowait))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 1085, in _send_receive
    sock_result = self._get_socket(False)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 948, in _get_socket
    return err
           ^^^
UnboundLocalError: cannot access local variable 'err' where it is not associated with a value
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000004s20z\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-power\",\"attribute\":\"640\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":7,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"736\"},\"name\":\"倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_box\",\"attribute\":\"224\"},\"name\":\"上电状态设置\",\"typeSpec\":{\"range\":[\"off\",\"on\",\"memory\"],\"type\":\"enum\",\"typeDefaultValue\":\"off\"}},
{\"abilityId\":15,\"accessMode\":\"rw\",\"code\":\"light_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_box2\",\"attribute\":\"224\"},\"name\":\"指示灯状态设置\",\"typeSpec\":{\"range\":[\"none\",\"relay\",\"pos\"],\"type\":\"enum\",\"typeDefaultValue\":\"none\"}}]}]}"
  },
  "success": true,
  "t": 1693814084879,
  "tid": "4fe8d2254af811ee9db51e8ad7cd6da8"
}
```
```
{
  "result": {
    "properties": [
      {
        "code": "switch_1",
        "custom_name": "",
        "dp_id": 1,
        "time": 1693812936156,
        "value": true
      },
      {
        "code": "countdown_1",
        "custom_name": "",
        "dp_id": 7,
        "time": 1693624000823,
        "value": 0
      },
      {
        "code": "relay_status",
        "custom_name": "",
        "dp_id": 14,
        "time": 1693624000825,
        "value": "off"
      },
      {
        "code": "light_mode",
        "custom_name": "",
        "dp_id": 15,
        "time": 1693624000829,
        "value": "pos"
      }
    ]
  },
  "success": true,
  "t": 1693814168138,
  "tid": "818de1a84af811ee8179fa3ecb648a44"
}
```

# Product ID

"product_id": "dn7fpj6lcz3krzbv",

# Information about how the device functions

It's a simple, single-pole switch as described [here](https://www.amazon.com/dp/B0BPGPRKKS?ref=ppx_yo2ov_dt_b_product_details&th=1).

**Comment by nprez83** [comment]
Wondering if there's any further I can provide @make-all, thanks in advance

**Comment by make-all** [comment]
Logs after you have solved the connection issues that are giving the current errors would help.  See #522 for how to resolve connection issues, but most likely it is filling in actual values instead of using the Auto setting, double checking the device id and local key, and making sure the IP address is the local address on your home network, not the one the tuya cloud sees.

**Comment by make-all** [comment]
Using the current "main" version will also upgrade tinytuya to fix the bug that causes that UnboundLocalError, so you can see the actual error it is trying to report.
