### ISSUE TITLE
Request support for SmarDeer Lock33 Wi-Fi smart door lock (jtmspro)

### ISSUE THREAD

**Issue by felipecrs** [make-all/tuya-local#1181]
# Log Message

```
Device matches None with quality of 0%. DPS: {"updated_at": 1697509642.0612128, "9": 54}
```

# Information about DPS mappings

Note that I translated the Chinese names and descriptions to English.

```json
{
  "modelId": "000003l0vw",
  "services": [
    {
      "actions": [],
      "code": "",
      "description": "",
      "events": [],
      "name": "Default Service",
      "properties": [
        {
          "abilityId": 1,
          "accessMode": "ro",
          "code": "unlock_fingerprint",
          "description": "Optional. Fingerprint data is recorded on the door lock, and after recording is complete, the hardware assigns an ID. When fingerprint unlocking occurs, the door lock will report this data. Please use recorded data for reporting.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1024" },
          "name": "Fingerprint Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 2,
          "accessMode": "ro",
          "code": "unlock_password",
          "description": "Optional. Regular passwords (non-temporary) are recorded on the door lock, and after recording is complete, the hardware assigns an ID. When regular password unlocking occurs, the door lock will report this data. Regular passwords refer to passwords created on the door lock hardware, excluding temporary passwords created through the app. Please use recorded data for reporting.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1024" },
          "name": "Regular Password Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 3,
          "accessMode": "ro",
          "code": "unlock_temporary",
          "description": "Optional. Distinguishes between temporary and regular passwords. Temporary passwords are created through the app and can have an exact expiration date. They can also send SMS notifications to the recipients during creation. Please use recorded data for reporting.",
          "extensions": { "iconName": "icon-shoushimima", "attribute": "1024" },
          "name": "Temporary Password Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 5,
          "accessMode": "ro",
          "code": "unlock_card",
          "description": "Optional. Card data is recorded on the door lock, and after recording is complete, the hardware assigns an ID. When card unlocking occurs, the door lock will report this data. Please use recorded data for reporting.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1024" },
          "name": "Card Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 8,
          "accessMode": "ro",
          "code": "alarm_lock",
          "description": "Required. 0=Fingerprint error alarm, 1=Password error alarm, 2=Card error alarm, 3=Face error alarm, 4=Fake lock (tongue stuck), 5=High temperature alarm, 6=Timeout without closing the door, 7=Electronic tongue not popped out, 8=Anti-pry alarm, 9=Key insertion, 10=Low battery alarm, 11=Power depletion alarm, 12=Vibration alarm, 13=Arming alarm (function not yet supported).",
          "extensions": { "iconName": "icon-dp_warming", "attribute": "1024" },
          "name": "Alarm",
          "typeSpec": {
            "range": [
              "wrong_finger",
              "wrong_password",
              "wrong_card",
              "wrong_face",
              "tongue_bad",
              "too_hot",
              "unclosed_time",
              "tongue_not_out",
              "pry",
              "key_in",
              "low_battery",
              "power_off",
              "shock",
              "defense"
            ],
            "type": "enum",
            "typeDefaultValue": "wrong_finger"
          }
        },
        {
          "abilityId": 9,
          "accessMode": "ro",
          "code": "unlock_request",
          "description": "Optional. To use remote door opening, this data point is required. The door lock reports a remote door opening request, which needs to be triggered by the hardware. When the door lock locally reports a remote door opening request, it comes with an x-second countdown. A response can only be made within x seconds. By clicking 'Allow' within the time limit, the door lock will unlock. x can be less than or equal to 90. If the door lock has either accepted or rejected the remote door opening, change the value of this field to 0, and the panel will stop blinking.",
          "extensions": { "attribute": "1152" },
          "name": "Remote Door Opening Request Countdown",
          "typeSpec": {
            "max": 90,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 11,
          "accessMode": "ro",
          "code": "battery_state",
          "description": "Optional but must choose one of the two. Battery status and battery value, choose one. high=High, medium=Medium, low=Low, poweroff=Battery about to run out.",
          "extensions": { "iconName": "icon-dp_battery", "attribute": "1024" },
          "name": "Battery Status",
          "typeSpec": {
            "range": ["high", "medium", "low", "poweroff"],
            "type": "enum",
            "typeDefaultValue": "high"
          }
        },
        {
          "abilityId": 12,
          "accessMode": "ro",
          "code": "residual_electricity",
          "description": "Optional but must choose one of the two. Battery value and battery status, choose one. Report the numerical value of the battery charge.",
          "extensions": { "attribute": "1152" },
          "name": "Remaining Battery Charge",
          "typeSpec": {
            "max": 100,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 15,
          "accessMode": "ro",
          "code": "unlock_app",
          "description": "Optional. When an app remote door opening event occurs, the door lock reports a record of the remote door opening. Use recorded data for reporting.",
          "extensions": { "iconName": "icon-shouji", "attribute": "1024" },
          "name": "App Remote Unlock (Wi-Fi Door Lock)",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 16,
          "accessMode": "ro",
          "code": "hijack",
          "description": "Optional. This function does not require hardware implementation. The door lock does not need to make hijack judgments; marking the unlock ID in the app is sufficient.",
          "extensions": { "iconName": "icon-baojing", "attribute": "1024" },
          "name": "Hijack Alarm",
          "typeSpec": { "type": "bool", "typeDefaultValue": false }
        },
        {
          "abilityId": 19,
          "accessMode": "ro",
          "code": "doorbell",
          "description": "Optional. If the door lock hardware has a doorbell function, clicking this data point will trigger a doorbell call notification to the cloud. It is recommended to trigger only one doorbell call notification for continuous doorbell calls. After reporting, the app will retain a record, and it can trigger push notifications.",
          "extensions": { "iconName": "icon-a_power", "attribute": "1024" },
          "name": "Doorbell Call",
          "typeSpec": { "type": "bool", "typeDefaultValue": false }
        },
        {
          "abilityId": 44,
          "accessMode": "rw",
          "code": "unlock_double_kit",
          "description": "Local combination unlocking record, use this data point to upload.",
          "extensions": { "attribute": "1280" },
          "name": "Combination Unlock Record",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 49,
          "accessMode": "rw",
          "code": "remote_no_pd_setkey",
          "description": "Optional. New encryption mechanism for remote door opening. This data point needs to be delivered during network configuration.",
          "extensions": { "iconName": "icon-setting", "attribute": "1152" },
          "name": "Set No-Pass Remote Door Opening Key",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 50,
          "accessMode": "rw",
          "code": "remote_no_dp_key",
          "description": "Optional. New encryption mechanism for remote door opening. This data point needs to be sent simultaneously in response to remote door opening.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1152" },
          "name": "New No-Pass Remote Door Opening with Key",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 212,
          "accessMode": "rw",
          "code": "initiative_message",
          "description": "Used for transmitting images and videos as system data points. When creating a PID, this capability must be selected, otherwise, it will not support transmitting images or videos.",
          "extensions": { "attribute": "2560" },
          "name": "Active Message Push",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        }
      ]
    }
  ]
}
```

# Product ID

oufbykkic2alxcjw

# Information about how the device functions

https://aliexpress.com/item/1005003731084162.html

I believe the functions of this lock is similar to the existing ones, like `intelbras_IFR7000_lock`.

Also, I think the functions are well documented.

**Comment by babacana** [comment]
Any news if it worked?

**Comment by ScottWoolven5** [comment]
@felipecrs @babacana did you get the lock to work properly?

**Comment by felipecrs** [comment]
Not really. I was never able to make it connect. The door lock isn't actually in my home, it's in my brother's home, so it's more difficult to get a chance to test.

**Comment by felipecrs** [comment]
@make-all I finally got around to testing this.

Here is how the lock works:

1. It is never connected to Wi-Fi normally
1. You can press *9#, this means the camera will connect to the wi-fi during one minute waiting for an "remote" unlock command to be given (by the Tuya app)
1. I was able to make Tuya Local connect to the lock. It properly finds the IP and everything, but I need to keep the lock connected to Wi-Fi with *9#.
1. The setup process works perfectly.

But, when I try to press "unlock" in the lock entity, the following error is thrown:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 4:16:46 PM (3 occurrences)
Last logged: 4:22:39 PM

[139666584981648] Unexpected exception
[139666584986688] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 239, in async_handle_unlock_service
    await self.async_unlock(**self.add_default_code(kwargs))
  File "/config/custom_components/tuya_local/lock.py", line 153, in async_unlock
    raise NotImplementedError()
NotImplementedError
```

Do you believe something can be done about it?

Again, thanks very much for adding the device profile, I would not be able to reach this far otherwise.

**Comment by make-all** [comment]
If it is not permanently connected to WiFi, then you will only get reasonable behaviour from the cloud integration. Battery powered devices need a hub they can connect to during the short periods they come online, for WiFi devices the cloud is that hub.

**Comment by felipecrs** [comment]
I understand. BTW, I would be more than satisfied if I could get only the unlock option for when *9# is pressed. This would allow me to not use the Tuya app.

My lock itself can be unlocked without a key code from the Tuya app (when *9# is pressed and thus it connects to Wi-Fi).

I will do some research on whether at least I could get it working through the Tuya API (the official cloud integration doesn't support locks).

Thank you anyway.

**Comment by make-all** [comment]
Unlocking involves these datapoints:
```
  {
          "abilityId": 49,
          "accessMode": "rw",
          "code": "remote_no_pd_setkey",
          "description": "Optional. New encryption mechanism for remote door opening. This data point needs to be delivered during network configuration.",
          "extensions": { "iconName": "icon-setting", "attribute": "1152" },
          "name": "Set No-Pass Remote Door Opening Key",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 50,
          "accessMode": "rw",
          "code": "remote_no_dp_key",
          "description": "Optional. New encryption mechanism for remote door opening. This data point needs to be sent simultaneously in response to remote door opening.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1152" },
          "name": "New No-Pass Remote Door Opening with Key",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
```

When the lock is paired with the app, the app generates a shared key and sends it to the lock using `remote_no_pd_setkey`. The app is then able to unlock the lock remotely using that shared key and `remote_no_dp_key`.

Unless you can find a way to get the key, there is no hope of remotely unlocking from HA. Some other locks can workaround this by toggling the auto lock setting, but it will depend on your lock's firmware.

**Comment by felipecrs** [comment]
Very interesting. Thank you. I'll let you know if I find something.

**Comment by 33Crypto** [comment]
LOCK33 Development Organization is intervening.

**Comment by babacana** [comment]
> Very interesting. Thank you. I'll let you know if I find something.

Tell me more about that.

**Comment by felipecrs** [comment]
I think I didn't find anything useful and then I gave up.
