### ISSUE TITLE
Siren.turn_on does not appear to work when calling with a volume_level attribute

### ISSUE THREAD

**Issue by bdf0506** [make-all/tuya-local#1224]
Using the loycco_sound_nightlight.yaml configuration, you actually can't control the volume of this device with the default config for the white noise machine. Looking at other siren.turn_on yaml files for known devices in tuya-local, looks like this is the only yaml file that uses an integer number for the volume_level, so there must be something in the code that needs to be fixed to allow this to work properly with an integer.

Calling the following service:
````
service: siren.turn_on
data:
  tone: Fan
  volume_level: 0.5
target:
  entity_id: siren.white_noise_machine_sound
````

Gives you an error in the services panel of 
`Failed to call service siren.turn_on. Unknown error`

The home assistant logs show the following:

````
2023-10-27 20:54:48.932 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140366361120704] Error handling message: Unknown error (unknown_error) admin from 192.168.20.101 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 727, in handle_execute_script
    script_result = await script_obj.async_run(msg.get("variables"), context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/siren/__init__.py", line 117, in async_handle_turn_on_service
    await siren.async_turn_on(
  File "/config/custom_components/tuya_local/siren.py", line 103, in async_turn_on
    volume = min(
             ^^^^
ValueError: min() arg is an empty sequence
````

_Originally posted by @bdf0506 in https://github.com/make-all/tuya-local/discussions/1219#discussioncomment-7408471_

**Comment by make-all** [comment]
Was fixed in commit 3275beb2ae01

**Comment by bdf0506** [comment]
confirmed this works. You do have to be careful and make sure that you set a value no less than 0.1, or else it does not work, but that's a caveat that's to be expected, as this device has a minimum value of 10% for sound.

**Comment by make-all** [comment]
Yes, unfortunately many entities in Home Assistant do not enforce minimums in the UI, so out of range values come through to the integration to be rejected there.
