### ISSUE TITLE
Slow HA restart due to offline devices

### ISSUE THREAD

**Issue by fireheadman** [make-all/tuya-local#1373]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Restarts of HA are taking a lot longer due to offline devices having to timeout.

**To Reproduce**
restart HA and watch the logs

**Expected behavior**
Would be nice if there way to skip over offline devices quicker?

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by fireheadman** [comment]
Here is a snippet from the HA log on start up for a tuya bulb that is purposely offline (4 of them).    I control these with a KASA smart switch, so when this is powered off, the bulbs are completely powered off.   
```

2023-12-03 14:59:38.038 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Hallway Bulb 4 for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 314, in async_setup_entry
    setup_device(hass, config)
  File "/config/custom_components/tuya_local/device.py", line 626, in setup_device
    device = TuyaLocalDevice(
             ^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/device.py", line 86, in __init__
    raise e
  File "/config/custom_components/tuya_local/device.py", line 77, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 848, in __init__
    raise Exception("Unable to find device on network (specify IP address)")
Exception: Unable to find device on network (specify IP address)
```

**Comment by make-all** [comment]
Your main issue is that you have specified Auto for IP address (and maybe protocol).  If you want them to time out quickly, you need to set these values so that the integration does not need to search (for the IP address, then try each protocol version to find the one that works).
I don't consider this a bug, but a tradeoff in convenience of not setting these values vs having the more reliable behaviour of setting them.

**Comment by fireheadman** [comment]
Thanks for the clarification and recommendation
I’ll apply that tomorrow to my configs
