### ISSUE TITLE
Error on HA startup

### ISSUE THREAD

**Issue by vampywiz17** [make-all/tuya-local#1487]
I get this when HA start. The devices are working propertly.

```
2024-01-07 17:00:24.492 ERROR (MainThread) [homeassistant.components.select] Error while setting up tuya_local platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/select.py", line 14, in async_setup_entry
    await async_tuya_setup_platform(
  File "/config/custom_components/tuya_local/helpers/config.py", line 34, in async_tuya_setup_platform
    data[ecfg.config_id] = entity_class(device, ecfg)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/select.py", line 39, in __init__
    raise AttributeError(
AttributeError: select_initial_state does not have a mapping to a list of options
```

**Comment by make-all** [comment]
What device is this for (the name of the config file you selected)?

**Comment by vampywiz17** [comment]
@make-all general error, in home-assistant.log

**Comment by make-all** [comment]
It is not a general error, as it is not occuring on my installation.  It is an error parsing one of the 500+ config files, and I need to know which one it is to fix the issue.

**Comment by vampywiz17** [comment]
It help you?

```
2024-01-08 00:43:47.374 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config somgom_single_switch.yaml
2024-01-08 00:43:47.374 DEBUG (MainThread) [custom_components.tuya_local.helpers.config] Adding number for number_timer
2024-01-08 00:43:47.375 ERROR (MainThread) [homeassistant.components.select] Error while setting up tuya_local platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/select.py", line 14, in async_setup_entry
    await async_tuya_setup_platform(
  File "/config/custom_components/tuya_local/helpers/config.py", line 34, in async_tuya_setup_platform
    data[ecfg.config_id] = entity_class(device, ecfg)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/select.py", line 39, in __init__
    raise AttributeError(
AttributeError: select_initial_state does not have a mapping to a list of options
2024-01-08 00:43:47.389 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.tuya_local.light.TuyaLocalLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/make-all/tuya-local/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-01-08 00:43:47.391 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2024-01-08 00:43:47.391 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2024-01-08 00:43:47.391 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for step of value
2024-01-08 00:43:47.391 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Step for value is 1 with scale 60
2024-01-08 00:43:47.391 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2024-01-08 00:43:47.391 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2024-01-08 00:43:47.391 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for step of value
2024-01-08 00:43:47.391 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Step for value is 1 with scale 60
2024-01-08 00:43:47.392 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Wall switch
```

**Comment by vampywiz17** [comment]
Hmm i remember... this is device the prioblem:

https://github.com/make-all/tuya-local/issues/962

**Comment by vampywiz17** [comment]
I dont know help or not, but i try to change the device any parameter on iot.portal, i get a error message that "param is empty". I think it wait the "switch inching" param, but i dont know what is this.

![image](https://github.com/make-all/tuya-local/assets/14281430/cd937f68-ade5-4a21-bbe0-1f870282b2c4)

**Comment by vampywiz17** [comment]
I change somgom swith config and now the error is gone AND the last state field work well! Thanks a lot!!
