### ISSUE TITLE
Energy components not working after update to 2022.4

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#153]
The energy sensors that were previously working no longer are for my Kogan smart switches. 

The log file shows the following:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

**Comment by make-all** [comment]
The energy attributes on switches were removed in 2022.4.  This should not matter, as separate sensors were already created, but it seems from that log trace there is an additional undocumented change that is now requiring custom components to use the newly added Enumerations instead of strings for categories.

**Comment by Krispkiwi** [comment]
Thanks for looking into it mate. I'm finding your integration to be far more stable than local tuya. Appreciate the work.

**Comment by make-all** [comment]
I just released 0.16.1 to hopefully fix this issue.  I'm not in a position to test this myself now, so would appreciate if you can let me know if the fix is working.

**Comment by malomehi** [comment]
I am also getting errors with a power switch, on version `0.16.1`:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 518, in _async_add_entity
    entity_category=entity.entity_category,
  File "/config/custom_components/tuya_local/helpers/mixin.py", line 56, in entity_category
    return EntityCategory(self._config.entity_category)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: None is not a valid EntityCategory
```

**Comment by Krispkiwi** [comment]
I can confirm on 16.1 the switches don't appear to work at all: 
Logger: homeassistant.components.switch
Source: custom_components/tuya_local/helpers/mixin.py:56
Integration: Switch (documentation, issues)
First occurred: 10:25:33 AM (12 occurrences)
Last logged: 10:25:33 AM

Error adding entities for domain switch with platform tuya_local
Error while setting up tuya_local platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 518, in _async_add_entity
    entity_category=entity.entity_category,
  File "/config/custom_components/tuya_local/helpers/mixin.py", line 56, in entity_category
    return EntityCategory(self._config.entity_category)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: None is not a valid EntityCategory

**Comment by make-all** [comment]
Yes, the fix was too hastily made and did not consider the entities without a category setting, as None cannot be converted to an EntityCategory enum
