### ISSUE TITLE
Errors with galaxy projector device after 2024.2 

### ISSUE THREAD

**Issue by hyperb1iss** [make-all/tuya-local#1631]
After upgrading to HA 2024.2, my Blisslights Sky Lite Evolve is no longer working. This was working just fine before updating to 2024.2, it seems related to the light changes. Still getting up to speed with Tuya Local but here is the log:

2024-02-07 22:19:04.026 DEBUG (MainThread) [custom_components.tuya_local] Setting up entry for device: eb2ebd247bc7b789ebtn9r
2024-02-07 22:19:04.026 INFO (MainThread) [custom_components.tuya_local.device] Creating device: eb2ebd247bc7b789ebtn9r
2024-02-07 22:19:04.040 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config galaxy_projector_light.yaml
2024-02-07 22:19:04.050 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config galaxy_projector_light.yaml
2024-02-07 22:19:04.050 DEBUG (MainThread) [custom_components.tuya_local.helpers.config] Adding light for light
2024-02-07 22:19:04.050 DEBUG (MainThread) [custom_components.tuya_local.helpers.config] Adding light for light_laser
2024-02-07 22:19:04.059 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config galaxy_projector_light.yaml
2024-02-07 22:19:04.059 DEBUG (MainThread) [custom_components.tuya_local.helpers.config] Adding number for number_timer
2024-02-07 22:19:04.076 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config galaxy_projector_light.yaml
2024-02-07 22:19:04.076 DEBUG (MainThread) [custom_components.tuya_local.helpers.config] Adding fan for fan_laser_movement
2024-02-07 22:19:04.078 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.078 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.078 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.079 DEBUG (MainThread) [custom_components.tuya_local.device] Starting monitor loop for Sky Lite Evolve
2024-02-07 22:19:04.079 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.079 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.079 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.080 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] effect values: ['Manual', 'Scene', 'Music']
2024-02-07 22:19:04.080 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] effect values: ['Manual', 'Scene', 'Music']
2024-02-07 22:19:04.081 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] effect values: ['Manual', 'Scene', 'Music']
2024-02-07 22:19:04.081 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] effect values: ['Manual', 'Scene', 'Music']
2024-02-07 22:19:04.081 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] effect values: ['Manual', 'Scene', 'Music']
2024-02-07 22:19:04.081 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] effect values: ['Manual', 'Scene', 'Music']
2024-02-07 22:19:04.087 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2024-02-07 22:19:04.088 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2024-02-07 22:19:04.088 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for step of value
2024-02-07 22:19:04.089 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Step for value is 60 with scale 60
2024-02-07 22:19:04.089 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2024-02-07 22:19:04.089 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2024-02-07 22:19:04.089 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for step of value
2024-02-07 22:19:04.089 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Step for value is 60 with scale 60
2024-02-07 22:19:04.092 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Sky Lite Evolve to 3.5
2024-02-07 22:19:04.392 DEBUG (MainThread) [custom_components.tuya_local.device] Sky Lite Evolve received {"20": true, "24": "012c000003e8", "26": 0, "51": "colour", "52": true, "53": true, "54": 1000, "60": true, "62": 53, "101": 1000, "full_poll": true}
2024-02-07 22:19:04.393 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.393 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.394 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.394 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.395 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Galaxy Light: Mapped dps 52 value from True to hs
2024-02-07 22:19:04.395 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Galaxy Light: Mapped dps 52 value from True to hs
2024-02-07 22:19:04.396 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Galaxy Light: Mapped dps 52 value from True to hs
2024-02-07 22:19:04.396 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Galaxy Light: Mapped dps 52 value from True to hs
2024-02-07 22:19:04.397 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] format of >HHH found
2024-02-07 22:19:04.397 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] format of >HHH found
2024-02-07 22:19:04.400 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] color_mode values: ['white', 'hs']
2024-02-07 22:19:04.401 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] effect values: ['Manual', 'Scene', 'Music']
2024-02-07 22:19:04.402 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] effect values: ['Manual', 'Scene', 'Music']
2024-02-07 22:19:04.402 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] effect values: ['Manual', 'Scene', 'Music']
2024-02-07 22:19:04.406 ERROR (MainThread) [custom_components.tuya_local.device] Sky Lite Evolve receive loop terminated by exception unsupported operand type(s) for |: 'list' and 'set'
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 218, in receive_loop
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1049, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1129, in state_attributes
    self.__validate_color_mode(color_mode, legacy_supported_color_modes, effect)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1093, in __validate_color_mode
    effect_color_modes = supported_color_modes | {ColorMode.ONOFF}
                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for |: 'list' and 'set'

**Comment by hyperb1iss** [comment]
I got it working here by returning a set (with ColorModes.ONOFF included) instead of a list in the supported_color_modes accessor. I sent a pull request with a quick fix that works here, but I don't know if it has any side effects and how backwards compatibility is handled (if it's handled?)

**Comment by make-all** [comment]
I wonder if this also applies to other entities.  I am away from home now, and won't be able to check until tomorrow.  I will review the history however to see if the fix will have any backward compatibility issues.
