### ISSUE TITLE
Failed device setup not retried

### ISSUE THREAD

**Issue by mrbrdo** [make-all/tuya-local#1683]
I've had this issue several times now, it seems that if Tuya Local cannot find a device at startup or for some time after startup, it will stop looking for it and it will stay in "Failed to set up" state.

I've had this happen in 2 different situations:
1. When my power of the whole house goes out and I restart power, HA boots before my Wifi access point boots, to which the Tuya devices connect (probably with even some extra delay for connection retry)
2. I had my HA OS boot without a network connection for a few minutes, and after connecting the network, the Tuya devices are still not found, while everything else in HA is working.

If I manually reload the failed device in HA admin, it starts working immediately.

This is different to some other integrations I used (e.g. HomeKit Device), which never "give up" on a device and will keep trying to find it (successfully when it eventually becomes available). Especially since this plugin is only making local connections, there is even more reason to keep retrying.

**Comment by make-all** [comment]
If there is a bug in the integration preventing the device from being initialised by Home Assistant, there should be an error message in the Home Assistant log, which will have a stack trace pinpointing the issue.

Without that, it is not even clear the issue is in the integration and not Home Assistant itself.

**Comment by mrbrdo** [comment]
@make-all here is the relevant log entries from the last occurence of this issue:
```
2024-02-25 15:51:26.622 ERROR (MainThread) [custom_components.tuya_local.device] <class 'Exception'>: Unable to find device on network (specify IP address) while initialising device 1a2a3a4a5....
2024-02-25 15:51:26.622 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Vticnica Dnevna Prvo Nadstropje for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 314, in async_setup_entry
    setup_device(hass, config)
  File "/config/custom_components/tuya_local/device.py", line 635, in setup_device
    device = TuyaLocalDevice(
             ^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/device.py", line 86, in __init__
    raise e
  File "/config/custom_components/tuya_local/device.py", line 77, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core.py", line 941, in __init__
    raise Exception("Unable to find device on network (specify IP address)")
Exception: Unable to find device on network (specify IP address)
2024-02-25 15:51:44.753 ERROR (MainThread) [custom_components.tuya_local.device] <class 'Exception'>: Unable to find device on network (specify IP address) while initialising device 2a2a3a4a5....
2024-02-25 15:51:44.753 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mansarda Luc Tuya for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 314, in async_setup_entry
    setup_device(hass, config)
  File "/config/custom_components/tuya_local/device.py", line 635, in setup_device
    device = TuyaLocalDevice(
             ^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/device.py", line 86, in __init__
    raise e
  File "/config/custom_components/tuya_local/device.py", line 77, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core.py", line 941, in __init__
    raise Exception("Unable to find device on network (specify IP address)")
Exception: Unable to find device on network (specify IP address)
2024-02-25 15:52:02.780 ERROR (MainThread) [custom_components.tuya_local.device] <class 'Exception'>: Unable to find device on network (specify IP address) while initialising device 3a2a3a4a5....
2024-02-25 15:52:02.781 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Lucka Spalnica Levo Tuya for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 314, in async_setup_entry
    setup_device(hass, config)
  File "/config/custom_components/tuya_local/device.py", line 635, in setup_device
    device = TuyaLocalDevice(
             ^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/device.py", line 86, in __init__
    raise e
  File "/config/custom_components/tuya_local/device.py", line 77, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core.py", line 941, in __init__
    raise Exception("Unable to find device on network (specify IP address)")
Exception: Unable to find device on network (specify IP address)
2024-02-25 15:52:13.126 WARNING (SyncWorker_1) [custom_components.tuya_local.device] Terrace Dimmable light protocol error 901: Network Error: Unable to Connect
2024-02-25 15:52:52.697 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
2024-02-25 15:52:57.700 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
2024-02-25 15:53:02.705 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
2024-02-25 15:53:07.711 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
2024-02-25 15:53:12.717 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
2024-02-25 15:53:17.721 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
2024-02-25 15:53:22.723 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
2024-02-25 15:53:27.727 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
2024-02-25 15:53:32.729 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
2024-02-25 15:53:37.734 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
...message repeating...
2024-02-25 16:13:34.314 ERROR (MainThread) [custom_components.tuya_local.device] Failed to fetch device status for Terrace Dimmable light
...message stops...
2024-02-25 16:13:49.931 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.mansarda_luc_tuya are missing or not currently available
2024-02-25 16:13:49.934 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.lucka_spalnica_levo_tuya are missing or not currently available
```
