### ISSUE TITLE
Support for BWT FI 45 pool heater

### ISSUE THREAD

**Issue by cartman10** [make-all/tuya-local#17]
Hi, 
are you guys planning to support the BWT FI 45 pool heater? 

I tried to integrate it which resulted in the follwoing error:
2021-05-25 17:19:58 ERROR (MainThread) [homeassistant.components.climate] Error while setting up tuya_local platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/climate.py", line 52, in async_setup_entry
    await async_setup_platform(hass, {}, async_add_entities, discovery_info)
  File "/config/custom_components/tuya_local/climate.py", line 27, in async_setup_platform
    raise ValueError(f"Unable to detect type for device {device.name}")
ValueError: Unable to detect type for device My pool heater

From the error message I assume the decvice is simply not supported... 

I also assume the integration almost works because I could see some actual device data in the log:
2021-05-25 17:38:13 WARNING (MainThread) [homeassistant.loader] You are using a custom integration tuya_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-25 17:38:18 DEBUG (MainThread) [custom_components.tuya_local] Setting up entry for device: 4771835498f4abecc15f
2021-05-25 17:38:18 DEBUG (MainThread) [custom_components.tuya_local.device] Creating device: 4771835498f4abecc15f
2021-05-25 17:38:18 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for My pool heater to 3.3.
2021-05-25 17:38:20 DEBUG (SyncWorker_2) [custom_components.tuya_local.device] Refreshing device state for My pool heater.
2021-05-25 17:38:20 DEBUG (SyncWorker_2) [custom_components.tuya_local.device] refreshed device state: {"devId": "4771835498f4abecc15f", "dps": {"1": true, "2": 25, "3": 24, "4": "heat", "9": 0, "updated_at": 1621957100.7268553}}
2021-05-25 17:38:20 DEBUG (SyncWorker_2) [custom_components.tuya_local.device] new cache state (including pending properties): {"1": true, "2": 25, "3": 24, "4": "heat", "9": 0, "updated_at": 1621957100.7268553}
2021-05-25 17:38:20 DEBUG (MainThread) [custom_components.tuya_local.device] Inferring device type from cached state: {'1': True, '2': 25, '3': 24, '4': 'heat', '9': 0, 'updated_at': 1621957100.7268553}
2021-05-25 17:38:21 WARNING (MainThread) [custom_components.tuya_local.device] Detection for My pool heater failed
2021-05-25 17:38:21 ERROR (MainThread) [homeassistant.components.climate] Error while setting up tuya_local platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/climate.py", line 52, in async_setup_entry
    await async_setup_platform(hass, {}, async_add_entities, discovery_info)
  File "/config/custom_components/tuya_local/climate.py", line 27, in async_setup_platform
    raise ValueError(f"Unable to detect type for device {device.name}")
ValueError: Unable to detect type for device My pool heater

From the log I can guess that taget and current temperature as well as heating mode and other information is already taken from the device... 

All in all looks pretty promising to me :-) 

Hope to hear from you guys

**Comment by make-all** [comment]
Hi,
The other information I would need is:
1) Which of the "2": 25 and "3": 24 is the target temperature, and which the measured temperature. 
2) What is the temperature range that can be set.
3) "4": "heat" looks like a preset (I guess that is what you mean by heating mode).   What are the other presets? Or is it just an indicator. 
4) Do you have any idea what "9": 0 is for?  It could be an error code (0 being no error), or a timer. 

Currently I am in the middle of a refactoring to make adding new devices easier.  I will add this and other pending devices once I have the required climate functions working. This one looks fairly basic, so should

**Comment by cartman10** [comment]
Hi, thank you very much for considering this device for your integration!

1. 25 degrees celsius is the target temperature and 24 degrees is the temperature measured by the device.
2. The target temperature range can vary between 8 and 40 degrees.
3. The device supports heating and cooling. It heats or cools in different modes (see screenshot) like 'Automatic', 'Smart Cooling', 'Boost Cooling', 'Eco Cooling and similar ones for heating. If you like i can try all those modes and provide you the logs for each mode.
4. I have no clue so far what "9": 0 is for. You can setup timers and I also saw error messages in the app when e.g. the pool pump was idle. I'll try some different settings in the app and collect the results in the logs if you think that helps....

![image](https://user-images.githubusercontent.com/64599464/119598832-f9235400-bde3-11eb-9d5d-02f32c34d55a.png)

**Comment by make-all** [comment]
Yes, cycling through the presets will help.  No need to spend much time on dps "9", timers can be set up in HA independently of the device, and if it is an error code, I can just add an attribute that reports it as an int for any automations to pick up on.

**Comment by make-all** [comment]
This appears to be the same as the Remora pool heater requested in #15, except for a variation in the minimum temperature, and maybe some additional presets.  They could either be combined into one device with lowest common denominator functionality, or they will be impossible to distinguish automatically and will need to be manually configured.

**Comment by cartman10** [comment]
OK, here are the modes :

- Eco heating mode : {"1": true, "2": 25, "3": 23, "4": "quietheat", "9": 0, "updated_at": 1622002888.8546965}
- Boost heating mode : {"1": true, "2": 25, "3": 23, "4": "quickheat", "9": 0, "updated_at": 1622023001.359755}
- Smart heating mode : {"1": true, "2": 25, "3": 24, "4": "heat", "9": 0, "updated_at": 1622028474.5414855}
- Automatic : {'1': True, '2': 25, '3': 24, '4': 'auto', '9': 0, 'updated_at': 1622028926.2002869}
- Smart cooling mode :  {"1": true, "2": 25, "3": 24, "4": "cool", "9": 0, "updated_at": 1622029041.9679456}
- Boost cooling mode : {"1": true, "2": 25, "3": 24, "4": "quickcool", "9": 0, "updated_at": 1622029119.8440619}
- Eco cooling mode : {"1": true, "2": 25, "3": 24, "4": "quietcool", "9": 0, "updated_at": 1622029167.5428402}
- Eco cooling mode but device switched to standby {"1": false, "2": 25, "3": 24, "4": "quietcool", "9": 0, "updated_at": 1622029204.0674973}
Hope that helps ! Let me know if you need more or want me to test something else...
Thanks!

**Comment by make-all** [comment]
OK, unfortunately apart from heat and cool, they are not the same as the Remora heatpump.  I will have to think some more about how these two devices can be distinguished.  I just added the Remora support in 0.5.0, so you could try that now.  If you are using HACS, click on the menu at top right of the Tuya Local box, and select "Update Information" to check for updates without waiting the 10 hours that HACS has between checks.

**Comment by cartman10** [comment]
I forgot the device states with the water pump switched off :
{"1": true, "2": 25, "3": 24, "4": "heat", "9": 1, "updated_at": 1622030104.1905162}

**Comment by cartman10** [comment]
I tried it...

![image](https://user-images.githubusercontent.com/64599464/119656329-d9634e80-be2a-11eb-9b21-072305d01fab.png)

You made my day !!!

Thank you so much!!!

**Comment by make-all** [comment]
I have added full support in 0.8.3 for this device.  You will need to delete and re-add the device to change the device type from Remora to BWT.  Make sure you have a note of the local key and device id before you delete it.  The local key is in the Options, the device id may appear in the logs, or you can browse through config/.storage/core.config_entries to look for the current config.

**Comment by cartman10** [comment]
Just installed it and it worked right away.


Jason Rumney ***@***.***> schrieb am Sa., 3. Juli 2021, 05:04:
