### ISSUE TITLE
WiFi Din Rail Switch with metering connect with error and without switch

### ISSUE THREAD

**Issue by Der-Nax** [make-all/tuya-local#186]
Hi,
I try to connect wifi switch with energy metering. It's connected as just switch or smartplugv2. Any way it's has not any parameters and management functionality.
Could you please check possibility to correct settings for this device?
Log info:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/switch.py", line 54, in async_setup_entry
    await async_setup_platform(hass, {}, async_add_entities, config)
  File "/config/custom_components/tuya_local/switch.py", line 34, in async_setup_platform
    _LOGGER.debug(f"Adding switch for {discovery_info[ecfg.config_id]}")
KeyError: 'switch'

2022-06-23 13:03:56 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tuya_local platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/switch.py", line 54, in async_setup_entry
    await async_setup_platform(hass, {}, async_add_entities, config)
  File "/config/custom_components/tuya_local/switch.py", line 34, in async_setup_platform
    _LOGGER.debug(f"Adding switch for {discovery_info[ecfg.config_id]}")
KeyError: 'switch'
2022-06-23 13:03:56 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tuya_local platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/sensor.py", line 53, in async_setup_entry
    await async_setup_platform(hass, {}, async_add_entities, config)
  File "/config/custom_components/tuya_local/sensor.py", line 44, in async_setup_platform
    _LOGGER.debug(f"Adding sensor for {discovery_info[ecfg.config_id]}")
KeyError: 'sensor_voltage'
2022-06-23 13:03:56 ERROR (MainThread) [homeassistant.components.number] Error while setting up tuya_local platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/number.py", line 53, in async_setup_entry
    await async_setup_platform(hass, {}, async_add_entities, config)
  File "/config/custom_components/tuya_local/number.py", line 44, in async_setup_platform
    _LOGGER.debug(f"Adding number for {discovery_info[ecfg.config_id]}")
KeyError: 'number_timer'

    "model": "AT-Q-SY1-JWT",
    "category": "dlq",
    "product_id": "jdj6ccklup7btq3a",
    "product_name": "WiFi Din Rail Switch with metering",

Device matches smartplugv2 with quality of 31%. DPS: {'1': True, '9': 0, '17': 2, '18': 84, '19': 127, '20': 2207, '21': 1, '22': 0, '23': 0, '24': 0, '25': 0, '26': 0, '38': 'on', '40': 'relay', '41': False, '42': '', 'updated_at': 1655979614.7518883}

**Comment by make-all** [comment]
I don't have any information on what those additional parameters are.  Tuya's platform only lets you look up information on devices you own.

**Comment by Der-Nax** [comment]
I undestand that you have not enought information. I am ready to help you. Could you please provide instruction to do for me?

**Comment by make-all** [comment]
Do you have an account on iot.tuya.com?  If you do, then there may be more information in the Cloud API Explorer.  The specific function to use is the last "Get Device Specification Attribute" one listed under the second to last category "Device Control".  You need to check the server at the top of the page, as well as enter your device id.

Otherwise, comparing the data in the log message above with what is displayed in the app may help figure some out.

**Comment by Der-Nax** [comment]
Unforchantly responce from Tuya IoT Platform is not help:
{
  "result": {
    "category": "dlq"
  },
  "success": true,
  "t": 1656025314923,
  "tid": "79d0e6d9f34811ec81e2daf929f70cab"
}

Please look what I fuond - DPS: {'1': True (switch relay), '9': 0, '17': 2, '18': 84 (Current mA), '19': 127 (Power W *0.1), '20': 2207 (Voltage V * 0.1), '21': 1, '22': 0, '23': 0, '24': 0, '25': 0, '26': 0, '38': 'on' (Initial sate after reboot), '40': 'relay', '41': False, '42': '', 'updated_at': 1655979614.7518883}

**Comment by make-all** [comment]
That is unfortunate, usually there will be functions: [...] and status: [...] in the result as well listing at least some of the writable and readable dps.  But looking at the full list, this appears to be very similar to the smartplugv2_energy.yaml device that I have already added with just two differences - one dps is a different type, and another is missing.

1: switch
9: timer
17: energy (Wh) - this seems to self reset when it reports to the cloud, so not very useful in experience.
18: current (mA)
19: power (*0.1 W)
20: voltage (*0.1 V)
21: test_bit
22: voltage_calibration (I expose these as read-only attributes, as I think writing them requires some special procedure)
23: current_calibration
24: power_calibration
25: energy_calibration
26: fault_code (no actual code meanings are known, apart from 0 = OK)
41: cycle_timer - in this device it is a boolean, which is different than the string from smartplugv2_energy, so probably a different function.
42: random_timer
46* Overcharge cutoff enable/disable - not present, which is why the existing config does not match.

**Comment by Der-Nax** [comment]
when I try to add this relay to intergation I get choise 2 point simple switch and smartplugv2 without energy. With both cases device without any sensors and switch. I can not turn on or turn off it. I may make screenshots of all cases. Should I do it?
I tried to make new device file with differen dps on base smartplugv2_energy.yaml. But intergation never provide me additional choice then siple switch and smartplugv2.

Thank you very mach for your help.

**Comment by make-all** [comment]
I think you can remove the entries for dps ids 41 and 46 from the smartplugv2_energy.yaml, and it should detect.  Of course this is not a long term solution, as it will be overwritten with the original whenever you upgrade, but as an experiment to see if this will work.  In case of dps id 41, it is on a sensor by itself, and the whole sensor entity needs to be removed.

It is a bit strange that the switch is not working though.  Are you trying to monitor using the app at the same time?  This may block home assistant from connecting if the app is using a local connection.

**Comment by Der-Nax** [comment]
I did device:
cat smartrelayv2_energy.yaml
name: AT Switch with metering
primary_entity:
  entity: switch
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: sensor
    category: diagnostic
    class: energy
    name: Energy
    dps:
      - id: 17
        name: sensor
        type: integer
        unit: Wh
        class: total_increasing
  - entity: sensor
    category: diagnostic
    class: current
    name: Current
    dps:
      - id: 18
        name: sensor
        type: integer
        class: measurement
        unit: mA
  - entity: sensor
    category: diagnostic
    class: power
    name: Power
    dps:
      - id: 19
        name: sensor
        type: integer
        class: measurement
        unit: W
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: voltage
    name: Voltage
    dps:
      - id: 20
        name: sensor
        type: integer
        class: measurement
        unit: V
        mapping:
          - scale: 10 
I try to add it. It was find and I had possibility to choice it.
It was done without switch and sensors :(
I have no idea more.
Debug log for this operation:

2022-06-24 18:09:31 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3.
2022-06-24 18:09:31 DEBUG (SyncWorker_3) [custom_components.tuya_local.device] Refreshing device state for Test.
2022-06-24 18:09:31 DEBUG (SyncWorker_3) [custom_components.tuya_local.device] Test refreshed device state: {"dps": {"1": true, "9": 0, "17": 1, "18": 0, "19": 0, "20": 2161, "21": 1, "22": 0, "23": 0, "24": 0, "25": 0, "26": 0, "38": "on", "40": "relay", "41": false, "42": "", "updated_at": 1656083371.6271317}}
2022-06-24 18:09:31 DEBUG (SyncWorker_3) [custom_components.tuya_local.device] new cache state (including pending properties): {"1": true, "9": 0, "17": 1, "18": 0, "19": 0, "20": 2161, "21": 1, "22": 0, "23": 0, "24": 0, "25": 0, "26": 0, "38": "on", "40": "relay", "41": false, "42": "", "updated_at": 1656083371.6271317}
2022-06-24 18:09:31 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config andersson_gsh_heater.yaml
2022-06-24 18:09:31 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config anko_fan.yaml
2022-06-24 18:09:31 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config arlec_fan.yaml
2022-06-24 18:09:31 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config arlec_fan_light.yaml
2022-06-24 18:09:31 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config aspen_asp200_fan.yaml
2022-06-24 18:09:31 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config awow_th213_thermostat.yaml
2022-06-24 18:09:31 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config awow_th213v2_thermostat.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config beca_bac002_thermostat_c.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config beca_bhp6000_thermostat_c.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config beca_bhp6000_thermostat_f.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config beca_bht002_thermostat_c.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config beca_bht6000_thermostat_c.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config beok_tr9b_thermostat.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config betterlife_bl1500_heater.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config bwt_heatpump.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config carson_cb.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config deta_fan.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config devola_patio_heater.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config digoo_dgsp01_dual_nightlight_switch.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config digoo_dgsp202.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config eanons_humidifier.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config eberg_cooly_c35hd.yaml
2022-06-24 18:09:32 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config eberg_qubo_q40hd_heatpump.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config ecostrad_accentiq_heater.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config ecostrad_iqceramic_radiator.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config electriq_12wminv_heatpump.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config electriq_cd12pw_dehumidifier.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config electriq_cd12pwv2_dehumidifier.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config electriq_cd20pro_dehumidifier.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config electriq_cd25pro_dehumidifier.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config electriq_desd9lw_dehumidifier.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config eurom_600_heater.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config eurom_600_heater_v2.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config eurom_601_heater.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config eurom_walldesignheat2000_heater.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config fersk_vind_2_climate.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config garage_door_opener.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config gardenpac_heatpump.yaml
2022-06-24 18:09:33 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config goldair_dehumidifier.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config goldair_fan.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config goldair_geco_heater.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config goldair_gpcv_heater.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config goldair_gpph_heater.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config greenwind_dehumidifier.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config grid_connect_double_switch.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config grid_connect_usb_double_power_point.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config hellnar_heatpump.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config himox_h05_purifier.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config himox_h06_purifier.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config hysen_hy08we2_thermostat.yaml
2022-06-24 18:09:34 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config inkbird_itc306a_thermostat.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config inkbird_itc308_thermostat.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config ips_pro_heatpump.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config jiahong_et72w_thermostat.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config jjpro_jpd01_dehumidifier.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config jjpro_jpd02_dehumidifier.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config kogan_dehumidifier.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config kogan_garage_opener.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config kogan_glass_1_7l_kettle.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config kogan_kahtp_heater.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config kogan_kashmfp20ba_heater.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config kogan_kawfhtp_heater.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config kogan_kawfpac09ya_airconditioner.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config kyvol_e30_vacuum.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config lefant_m213_vacuum.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config lexy_f501_fan.yaml
2022-06-24 18:09:35 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config logicom_powerstrip.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config m027_curtain.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config madimack_elite_v3_heatpump.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config madimack_heatpump.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config minco_mh1823d_thermostat.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config mirabella_genio_usb.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config moes_bht002_thermostat_c.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config moes_rgb_socket.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config nashone_mts700wb_thermostat.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config nedis_htpl20f_heater.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config owon_pct513_thermostat.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config parkside_plgs2012a1_smart_charger.yaml
2022-06-24 18:09:36 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config poiema_one_purifier.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config poolex_qline_heatpump.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config poolex_silverline_heatpump.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config poolex_vertigo_heatpump.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config purline_m100_heater.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config qoto_03_sprinkler.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config qs_c01_curtain.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config remora_heatpump.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config renpho_rp_ap001s.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config saswell_c16_thermostat.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config saswell_t29utk_thermostat.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config sd123_hpr01_presence.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config simple_blinds.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config simple_switch.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Matched config for Simple Switch
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config simple_switch_timer.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartmcb_smt006_energymeter.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartplug_encoded.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartplugv1.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartplugv2.yaml
2022-06-24 18:09:37 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Matched config for Energy Monitoring Smart Plug
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartplugv2_energy.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartplugv3_energy.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Matched config for Advanced Energy Monitoring Smart Plug
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartrelay.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartrelay2.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartrelay_energy.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Matched config for AT Switch with metering
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartrelayv2_energy.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Matched config for AT Switch with metering
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config starlight_heatpump.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config stirling_fs140dc_fan.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config tadiran_wind_heatpump.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config tesla_air_purifier_mini.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config tesla_air_purifier_pro.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config tmwf02_fan.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config vork_vk6067aw_purifier.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config weau_pool_heatpump.yaml
2022-06-24 18:09:38 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config wetair_wawh1210lw_humidifier.yaml
2022-06-24 18:09:39 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config wetair_wch750_heater.yaml
2022-06-24 18:09:39 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config wilfa_haze_hu400bc_humidifier.yaml
2022-06-24 18:09:39 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config woox_r4028_powerstrip.yaml
2022-06-24 18:09:39 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches smartplugv3_energy with quality of 88%. DPS: {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2161, '21': 1, '22': 0, '23': 0, '24': 0, '25': 0, '26': 0, '38': 'on', '40': 'relay', '41': False, '42': '', 'updated_at': 1656083371.6271317}
2022-06-24 18:09:39 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
2022-06-24 18:09:44 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartrelayv2_energy.yaml
2022-06-24 18:09:47 DEBUG (MainThread) [custom_components.tuya_local] Setting up entry for device: --DEVICE ID--
2022-06-24 18:09:47 INFO (MainThread) [custom_components.tuya_local.device] Creating device: --DEVICE ID--
2022-06-24 18:09:47 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for AT Switch with metering to 3.3.
2022-06-24 18:09:47 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartrelayv2_energy.yaml
2022-06-24 18:09:47 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartrelayv2_energy.yaml
2022-06-24 18:09:47 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config smartrelayv2_energy.yaml

How I may help more?
Thank you for your time!

**Comment by make-all** [comment]
How did you install tuya-local?

From the log messages, it seems you may be using a non-released version from about a week ago which is also not the current HEAD.  I think the errors are caused by a bug in that version.  Since your config will already be migrated, I think you can only update to the latest to fix this.

**Comment by Der-Nax** [comment]
I manual install tuya-local at 18.06.2022. And I had this problem.
I download and install current version. My device smartrelayv2_energy.yaml start working without remove and install it again.
Thank you very much!
Should I close the issue or anyway it's need to add new device?

**Comment by make-all** [comment]
I'll add the new device, so leave it open for now.
