### ISSUE TITLE
Request support for `Smart lock_PB_003_005` - RAYKUBE M5 BLE lock with wifi gateway connection

### ISSUE THREAD

**Issue by nickdos** [make-all/tuya-local#1885]
RAYKUBE M5 Tuya BLE Fingerprint Door Lock ([link](https://www.aliexpress.com/item/1005006755492242.html))

    "product_id": "zhk7n5ey",
    "product_name": "Smart lock_PB_003_005",

The lock is able to be added to `tuya-local` via its wifi bridge and 2 locks are offered, but neither provide functioning lock/unlock actions, when selected.

* `novadigital_sl06_lock`
* `ironzon_fingerprint_lock`

# Log Message

Lock is successfully installed with Tuya-Local but attempting to unlock it via `lock.tuya_door_lock` returns an error:  "Failed to call service lock/lock. unknown error", with the following log messages:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 226, in async_handle_unlock_service
    await self.async_unlock(**self.add_default_code(kwargs))
  File "/config/custom_components/tuya_local/lock.py", line 145, in async_unlock
    raise NotImplementedError(self)
NotImplementedError:
```

# Information about DPS mappings

TinyTuya output (See API output in comment below)

```json
{
        "category": "jtmspro",
        "product_name": "Smart lock_PB_003_005",
        "product_id": "zhk7n5ey",
        "biz_type": 0,
        "model": "",
        "sub": true,
        "icon": "https://images.tuyaeu.com/smart/icon/bay1665802448309laHv/bd86277cd4d989abbcb75ca706613ee1.png",
        "node_id": "45bd98e49dc05c52",
        "mapping": {
            "1": {
                "code": "unlock_method_create",
                "type": "Raw",
                "values": {}
            },
            "2": {
                "code": "unlock_method_delete",
                "type": "Raw",
                "values": {}
            },
            "3": {
                "code": "unlock_method_modify",
                "type": "Raw",
                "values": {}
            },
            "8": {
                "code": "residual_electricity",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            },
            "12": {
                "code": "unlock_fingerprint",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "13": {
                "code": "unlock_password",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "15": {
                "code": "unlock_card",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "18": {
                "code": "open_inside",
                "type": "Boolean",
                "values": {}
            },
            "19": {
                "code": "unlock_ble",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "21": {
                "code": "alarm_lock",
                "type": "Enum",
                "values": {
                    "range": [
                        "wrong_finger",
                        "wrong_password",
                        "wrong_card",
                        "wrong_face",
                        "tongue_bad",
                        "too_hot",
                        "unclosed_time",
                        "tongue_not_out",
                        "pry",
                        "key_in",
                        "low_battery",
                        "power_off",
                        "shock",
                        "defense"
                    ]
                }
            },
            "31": {
                "code": "beep_volume",
                "type": "Enum",
                "values": {
                    "range": [
                        "mute",
                        "low",
                        "normal",
                        "high"
                    ]
                }
            },
            "32": {
                "code": "reverse_lock",
                "type": "Boolean",
                "values": {}
            },
            "33": {
                "code": "automatic_lock",
                "type": "Boolean",
                "values": {}
            },
            "36": {
                "code": "auto_lock_time",
                "type": "Integer",
                "values": {
                    "min": 1,
                    "max": 1800,
                    "scale": 0,
                    "step": 1
                }
            },
            "40": {
                "code": "closed_opened",
                "type": "Enum",
                "values": {
                    "range": [
                        "unknown",
                        "open",
                        "closed"
                    ]
                }
            },
            "46": {
                "code": "manual_lock",
                "type": "Boolean",
                "values": {}
            },
            "47": {
                "code": "lock_motor_state",
                "type": "Boolean",
                "values": {}
            },
            "51": {
                "code": "temporary_password_creat",
                "type": "Raw",
                "values": {}
            },
            "52": {
                "code": "temporary_password_delete",
                "type": "Raw",
                "values": {}
            },
            "54": {
                "code": "synch_method",
                "type": "Raw",
                "values": {}
            },
            "55": {
                "code": "unlock_temporary",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "58": {
                "code": "arming_switch",
                "type": "Boolean",
                "values": {}
            },
            "61": {
                "code": "remote_no_dp_key",
                "type": "Raw",
                "values": {}
            },
            "62": {
                "code": "unlock_phone_remote",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "63": {
                "code": "unlock_voice_remote",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "64": {
                "code": "password_offline_time",
                "type": "String",
                "values": "{}"
            },
            "65": {
                "code": "unlock_offline_clear_single",
                "type": "Raw",
                "values": {}
            },
            "66": {
                "code": "unlock_offline_clear",
                "type": "Raw",
                "values": {}
            },
            "67": {
                "code": "unlock_offline_pd",
                "type": "Raw",
                "values": {}
            },
            "68": {
                "code": "special_function",
                "type": "Enum",
                "values": {
                    "range": [
                        "function1",
                        "function2"
                    ]
                }
            },
            "70": {
                "code": "check_code_set",
                "type": "Raw",
                "values": {}
            },
            "71": {
                "code": "ble_unlock_check",
                "type": "Raw",
                "values": {}
            },
            "73": {
                "code": "remote_pd_setkey_check",
                "type": "Raw",
                "values": {}
            }
        },
        "parent": ""
    }
```

# Product ID

    "product_id": "zhk7n5ey",
    "product_name": "Smart lock_PB_003_005",

# Information about how the device functions

https://www.aliexpress.com/item/1005006755492242.html

Seems to be similar in appearance to the `ironzon fingerprint lock` that is one of the recognised locks when adding to Tuya-local. Has fingerprint reader, number pad and a button on the internal handle to lock the door.

**Comment by nickdos** [comment]
Google translate version of DPS JSON

```json
{
   "modelId": "e9du88",
   "services": [
     {
       "actions": [],
       "code": "",
       "description": "",
       "events": [],
       "name": "Default service",
       "properties": [
         {
           "abilityId": 1,
           "accessMode": "rw",
           "code": "unlock_method_create",
           "description": "[Add unlocking method] After the device is online, add an unlocking method. Supports adding fingerprint, password, card and face unlocking methods; supports administrator mark.",
           "extensions": {
             "iconName": "icon-a_up",
             "attribute": "1888"
           },
           "name": "Add unlocking method",
           "typeSpec": {
             "type": "raw",
             "maxlen": 128
           }
         },
         {
           "abilityId": 2,
           "accessMode": "rw",
           "code": "unlock_method_delete",
           "description": "[Delete unlocking method] After the device is online, delete the unlocking method. Support unlocking methods of deleting fingerprints, passwords, cards and faces. This dp appears in pairs with the added dp",
           "extensions": {
             "iconName": "icon-dp_rabbish",
             "attribute": "1888"
           },
           "name": "Delete unlocking method",
           "typeSpec": {
             "type": "raw",
             "maxlen": 128
           }
         },
         {
           "abilityId": 3,
           "accessMode": "rw",
           "code": "unlock_method_modify",
           "description": "[Modify unlocking method] After the device is online, you can modify the name of the unlocking method and the content of the password.",
           "extensions": {
             "iconName": "icon-edit",
             "attribute": "1888"
           },
           "name": "Modify unlocking method",
           "typeSpec": {
             "type": "raw",
             "maxlen": 128
           }
         },
         {
           "abilityId": 8,
           "accessMode": "ro",
           "code": "residual_electricity",
           "description": "[Device Status] is used to display the power in percentage. The range is -1~100. When the device reports a value of -1, the power is not displayed. (Choose one with DP9)",
           "extensions": {
             "iconName": "icon-dp_battery",
             "attribute": "1280"
           },
           "name": "Remaining power",
           "typeSpec": {
             "type": "value",
             "max": 100,
             "min": 0,
             "scale": 0,
             "step": 1
           }
         },
         {
           "abilityId": 12,
           "accessMode": "ro",
           "code": "unlock_fingerprint",
           "description": "[Report unlocking records] is used for the device to report fingerprint unlocking records. This dp is only enabled when the smart lock product has a fingerprint recognition function on the hardware",
           "extensions": {
             "iconName": "icon-dp_lock",
             "attribute": "1280",
             "trigger": "direct"
           },
           "name": "Fingerprint unlock",
           "typeSpec": {
             "type": "value",
             "max": 999,
             "min": 0,
             "scale": 0,
             "step": 1
           }
         },
         {
           "abilityId": 13,
           "accessMode": "ro",
           "code": "unlock_password",
           "description": "[Report unlocking records] is used for the device to report the records of ordinary password unlocking. This dp is only enabled when the smart lock product has a password button on the hardware that can unlock the door with a password",
           "extensions": {
             "iconName": "icon-dp_lock",
             "attribute": "1280",
             "trigger": "direct"
           },
           "name": "Password unlock",
           "typeSpec": {
             "type": "value",
             "max": 999,
             "min": 0,
             "scale": 0,
             "step": 1
           }
         },
         {
           "abilityId": 15,
           "accessMode": "ro",
           "code": "unlock_card",
           "description": "[Report unlocking records] is used by the device to report door card unlocking records. This dp is only enabled when the smart lock product has a card swiping function on the hardware and can report card swiping records",
           "extensions": {
             "iconName": "icon-dp_lock",
             "attribute": "1280",
             "trigger": "direct"
           },
           "name": "Key card unlocking",
           "typeSpec": {
             "type": "value",
             "max": 999,
             "min": 0,
             "scale": 0,
             "step": 1
           }
         },
         {
           "abilityId": 18,
           "accessMode": "ro",
           "code": "open_inside",
           "description": "[Report unlocking records] If the device locally supports the detection of opening the door from the inside, it is used for the device to report the record of opening the door from the inside. Only if this smart lock product can detect and identify unlocking from the inside on the hardware, and When data can be reported, enable this dp",
           "extensions": {
             "iconName": "icon-dp_power2",
             "attribute": "1024",
             "trigger": "direct"
           },
           "name": "The door opens from the inside",
           "typeSpec": {
             "type": "bool"
           }
         },
         {
           "abilityId": 19,
           "accessMode": "ro",
           "code": "unlock_ble",
           "description": "[Report unlocking records] is used by the device to report the unlocking records generated by Bluetooth unlocking on the mobile app. Generally, all Bluetooth locks support this function",
           "extensions": {
             "iconName": "icon-dp_lock",
             "attribute": "1280",
             "trigger": "direct"
           },
           "name": "Bluetooth Unlock",
           "typeSpec": {
             "type": "value",
             "max": 999,
             "min": 0,
             "scale": 0,
             "step": 1
           }
         },
         {
           "abilityId": 21,
           "accessMode": "ro",
           "code": "alarm_lock",
           "description": "[Alarm record] When an alarm occurs locally, it is used to report the alarm record of the device. Corresponding value description: 0=Fingerprint trial and error alarm, 1=Password trial and error alarm, 2=Card trial and error alarm, 3=Person Face trial and error alarm, 4=fake lock (the deadbolt is stuck), 5=high temperature alarm, 6=timeout does not close the door, 7=the electronic deadbolt does not pop up, 8=anti-pry alarm, 9=key inserted, 10=low battery Alarm, 11=battery exhaust alarm, 12=vibration alarm, 13=arming alarm, if the device only uses a few items in the alarm dp, the redundant content does not need to be deleted. If deleted, the serial number of the MCU when reporting needs to be adjusted. . It is recommended that developers do not change the enumeration value in the alarm. In case of special circumstances, please perform operations such as adding, deleting, and configuring multiple languages under the guidance of PM."
           "extensions": {
             "iconName": "icon-dp_warming",
             "attribute": "1280",
             "trigger": "direct"
           },
```

**Comment by make-all** [comment]
It is common for locks to not support simple remote unlock functionality, as to do so would be a security risk.
