### ISSUE TITLE
WeeKett not detected as kettle

### ISSUE THREAD

**Issue by davidc** [make-all/tuya-local#2140]
**Describe the bug**
WeeKett support was added in #1481 but the device type is not detected.

**To Reproduce**
1. Retrieve local key for weekett
2. Add to tuya local
3. Device is connected to but is not correctly identified.

**Expected behavior**
Kettle should be detected as weeket_kettle (sic)

**Additional context**
The device type `01rtpfyd3amxdsps` retrieved by tuya-uncover matches the id in tuya_local/devices/weeket_kettle.yaml:

```
    "Kettle ": {
        "id": "xxx",
        "local_key": "xxx",
        "category": "bh",
        "uuid": "xxx",
        "product_id": "01rtpfyd3amxdsps",
        "dps": {
            "1": false,
            "101": false,
            "12": "c",
            "13": false,
            "15": "standby",
            "16": "setting_quick",
            "19": 0,
            "2": 24,
            "3": 74,
            "8": 90,
            "9": 194
        }
    },
```

weeket_kettle doesn't appear as an option in the device type dropdown.

![image](https://github.com/user-attachments/assets/a9f05f71-7e6f-4073-9217-5d6461c896a7)

Home assistant logs:

```
2024-07-21 11:21:25.646 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/tuya_local/devices/9in1_airquality_monitor.yaml',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 415, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 436, in async_step_local
    return await self.async_step_select_type()
  File "/config/custom_components/tuya_local/config_flow.py", line 474, in async_step_select_type
    async for type in self.device.async_possible_types():
  File "/config/custom_components/tuya_local/device.py", line 360, in async_possible_types
    for match in possible_matches(cached_state):
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 987, in possible_matches
    parsed = TuyaDeviceConfig(cfg)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in __init__
    self._config = load_yaml(filename)

2024-07-21 11:21:37.361 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches gold_cct_lightbulb with quality of 40%. DPS: {"updated_at": 1721557285.5574162, "1": false, "2": 38, "3": 100, "8": 40, "9": 104, "12": "c", "13": false, "15": "standby", "19": 0, "101": false}
2024-07-21 11:21:37.361 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log message with any new device request to https://github.com/make-all/tuya-local/issues/
2024-07-21 11:29:01.852 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches gold_cct_lightbulb with quality of 40%. DPS: {"updated_at": 1721557730.114488, "1": false, "2": 37, "3": 98, "8": 40, "9": 104, "12": "c", "13": false, "15": "standby", "19": 0, "101": false}
2024-07-21 11:29:01.853 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log message with any new device request to https://github.com/make-all/tuya-local/issues/
2024-07-21 11:29:50.414 WARNING (SyncWorker_1) [custom_components.tuya_local.device] Test protocol error 904: Unexpected Payload from Device
2024-07-21 11:30:19.456 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches gold_cct_lightbulb with quality of 40%. DPS: {"updated_at": 1721557807.6376805, "1": false, "2": 37, "3": 98, "8": 40, "9": 104, "12": "c", "13": false, "15": "standby", "19": 0, "101": false}
2024-07-21 11:30:19.457 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log message with any new device request to https://github.com/make-all/tuya-local/issues/
```

Tuya Local installed via HACS and working with another device (a Tuya presence sensor).

Home assistant core 2024.7.3
HACS 1.34.0
Tuya Local 2024.7.0

In order to gather more diagnostics, I let it get added as a gold lightbulb and downloaded the device diagnostics, it is not a lightbulb so I don't know how helpful this is.

[config_entry-tuya_local-01J3AE0JA5A3DMW5XMXSGPWSRA.json](https://github.com/user-attachments/files/16323927/config_entry-tuya_local-01J3AE0JA5A3DMW5XMXSGPWSRA.json)

#1985 appears to have had the same problem but didn't provide debugging.

Let me know if you need anything else.

**Comment by davidc** [comment]
Brilliant, thank you!

![image](https://github.com/user-attachments/assets/c75bc21e-811f-4742-ad31-36589f7b0a9c)

![image](https://github.com/user-attachments/assets/846f0e20-8f87-450f-acd8-c5f58b0de111)
