### ISSUE TITLE
Request support for Suntec Air Conditioner 9.000 BTU/h

### ISSUE THREAD

**Issue by Shirotaku** [make-all/tuya-local#2200]
### Log message

```text
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.localtuya.pytuya
Quelle: custom_components/localtuya/pytuya/__init__.py:863
Integration: LocalTuya integration (Dokumentation, Probleme)
Erstmals aufgetreten: 11:51:10 (14 Vorkommnisse)
Zuletzt protokolliert: 12:13:39

[267...e92] Failed to get status:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/locks.py", line 386, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 863, in detect_available_dps
    data = await self.status()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 795, in status
    status = await self.exchange(DP_QUERY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"0000043i1w\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"Power\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"1\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_temp\"},\"name\":\"设置温度\",\"typeSpec\":{\"type\":\"value\",\"max\":31,\"min\":16,\"scale\":0,\"step\":1,\"unit\":\"℃\"}},{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_sun\"},\"name\":\"当前温度 \",\"typeSpec\":{\"type\":\"value\",\"max\":35,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"℃\"}},{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"cold：制冷模式；wet：除湿模式；wind：送风模式；hot：制热模式；可根据产品实际功能修改功能属性。\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"工作模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"cold\",\"wet\",\"wind\",\"hot\"]}},{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"windspeed\",\"description\":\"低风\\n中风\\n高风\",\"extensions\":{\"iconName\":\"icon-dp_wind\"},\"name\":\"风速\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"low\",\"med\",\"high\"]}},{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"anion\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_fresh\"},\"name\":\"负离子\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":15,\"accessMode\":\"rw\",\"code\":\"windshake\",\"description\":\"开关\",\"extensions\":{\"iconName\":\"icon-dp_shake\"},\"name\":\"竖摆风\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"off\",\"on\"]}},{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"Fault\",\"description\":\"1:室温传感器故障；2:盘管传感器故障；3：水满报警；\\n\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"E1\",\"E2\",\"warter_full\"],\"maxlen\":3}},{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"Sleeping_mode\",\"description\":\"\",\"name\":\"睡眠\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"TimerOn\",\"description\":\"\",\"name\":\"定时开启\",\"typeSpec\":{\"type\":\"value\",\"max\":1440,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"分钟\"}},{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"TimerOff\",\"description\":\"\",\"name\":\"定时关闭\",\"typeSpec\":{\"type\":\"value\",\"max\":1440,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"分钟\"}},{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"temp_set_f\",\"description\":\"\",\"name\":\"设置温度\",\"typeSpec\":{\"type\":\"value\",\"max\":88,\"min\":61,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"temp_current_f\",\"description\":\"\",\"name\":\"当前温度 \",\"typeSpec\":{\"type\":\"value\",\"max\":95,\"min\":32,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":109,\"accessMode\":\"ro\",\"code\":\"funcTag\",\"description\":\"第一位：竖摆风 0：无竖摆风 1：竖摆风；\\n第二位：横摆风 0：无横摆风 1：横摆风；\\n第三位：无负离子0、负离子1；\\n第四位：单冷0、冷暖1；\\n第五位：风速二档0、三挡1；\\n第六位：摄氏度0，华氏度1；\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"功能标记\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\"],\"maxlen\":6}},{\"abilityId\":110,\"accessMode\":\"rw\",\"code\":\"windshakeH\",\"description\":\"\",\"name\":\"横摆风\",\"typeSpec\":{\"type\":\"bool\"}}]}]}"
  },
  "success": true,
  "t": 1723543477075,
  "tid": "72827e91595b11efb841325685d3ae3c"
}
```

### Product Name

Suntec Air Conditioner 9.000 BTU/h

### Information about how the device functions

```{
  "result": {
    "properties": [
      {
        "code": "Power",
        "custom_name": "",
        "dp_id": 1,
        "time": 1723544120614,
        "type": "bool",
        "value": true
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 2,
        "time": 1723542637835,
        "type": "value",
        "value": 22
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 3,
        "time": 1723543635686,
        "type": "value",
        "value": 30
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 4,
        "time": 1723542851866,
        "type": "enum",
        "value": "cold"
      },
      {
        "code": "windspeed",
        "custom_name": "",
        "dp_id": 5,
        "time": 1723542637835,
        "type": "enum",
        "value": "low"
      },
      {
        "code": "anion",
        "custom_name": "",
        "dp_id": 11,
        "time": 1723542637835,
        "type": "bool",
        "value": false
      },
      {
        "code": "windshake",
        "custom_name": "",
        "dp_id": 15,
        "time": 1723542637835,
        "type": "enum",
        "value": "off"
      },
      {
        "code": "Fault",
        "custom_name": "",
        "dp_id": 20,
        "time": 1723542637835,
        "type": "bitmap",
        "value": 0
      },
      {
        "code": "Sleeping_mode",
        "custom_name": "",
        "dp_id": 103,
        "time": 1723542637835,
        "type": "bool",
        "value": false
      },
      {
        "code": "TimerOn",
        "custom_name": "",
        "dp_id": 104,
        "time": 1723542637835,
        "type": "value",
        "value": 0
      },
      {
        "code": "TimerOff",
        "custom_name": "",
        "dp_id": 105,
        "time": 1723542637835,
        "type": "value",
        "value": 0
      },
      {
        "code": "temp_set_f",
        "custom_name": "",
        "dp_id": 107,
        "time": 1723542631413,
        "type": "value",
        "value": 61
      },
      {
        "code": "temp_current_f",
        "custom_name": "",
        "dp_id": 108,
        "time": 1723542631413,
        "type": "value",
        "value": 32
      },
      {
        "code": "funcTag",
        "custom_name": "",
        "dp_id": 109,
        "time": 1723542637835,
        "type": "bitmap",
        "value": 0
      },
      {
        "code": "windshakeH",
        "custom_name": "",
        "dp_id": 110,
        "time": 1723542637835,
        "type": "bool",
        "value": false
      }
    ]
  },
  "success": true,
  "t": 1723544179127,
  "tid": "15001352595d11efa755"
}
```

![Screenshot_20240813_121451_Tuya Smart](https://github.com/user-attachments/assets/8c296f7d-351a-4619-a846-0b2804407a7b)
![Screenshot_20240813_121458_Tuya Smart](https://github.com/user-attachments/assets/4bf9d268-ce45-4af7-a84d-650a31eda382)
![Screenshot_20240813_121503_Tuya Smart](https://github.com/user-attachments/assets/8422394a-3673-4a55-a454-02c9dd9425f8)
![Screenshot_20240813_121507_Tuya Smart](https://github.com/user-attachments/assets/9a02b39e-02c0-44f7-a21b-673a584371b3)
be0969012f23

**Comment by make-all** [comment]
Logs are from a different integration.
