### ISSUE TITLE
Request support for Smart lock_QJ_006 (rxfxmjls)

### ISSUE THREAD

**Issue by Kejszijo** [make-all/tuya-local#2303]
### Log message

```text
Napló: homeassistant.components.websocket_api.http.connection
Forrás: components/websocket_api/commands.py:245
integráció: Home Assistant WebSocket API (dokumentáció, problémák)
Először fordult elő: 13:49:39 (6 Események)
Utoljára naplózott: 14:02:15

[140276051382416] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 239, in async_handle_unlock_service
    await self.async_unlock(**self.add_default_code(kwargs))
  File "/config/custom_components/tuya_local/lock.py", line 141, in async_unlock
    await self._lock_dp.async_set_value(self._device, False)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 476, in async_set_value
    raise TypeError(f"{self.name} is read only")
TypeError: lock is read only
```

### DPS information

```text
Smart lock_QJ_006 (rxfxmjls)
```

**Comment by Kejszijo** [comment]
Hi,

I try to add this Smart Lock (https://www.aliexpress.com/item/1005007081618563.html?spm=a2g0o.store_pc_home.promoteRecommendProducts_6000407453534.1005007081618563) and I can do that, but I can't run open and close operation.
The error message: Failed to call service lock/unlock. lock is read only

**Comment by make-all** [comment]
This is normal. You need a key to open the lock, you don't want just anyone opening it with a simple command.

**Comment by make-all** [comment]
It is not supported to open such locks remotely. Tuya does not provide documentation for how to do that.
