### ISSUE TITLE
Request support for Tuya Video Doorbell Security Camera from Aliexpress

### ISSUE THREAD

**Issue by paulomac1000** [make-all/tuya-local#2319]
### Log message

```text
2024-09-20 16:21:36.565 DEBUG (SyncWorker_6) [custom_components.tuya_local.device] Test refreshed device state: null
2024-09-20 16:21:36.567 DEBUG (MainThread) [custom_components.tuya_local.device] Retrying after exception <class 'TypeError'> argument of type 'NoneType' is not iterable (2/3)
2024-09-20 16:21:36.567 ERROR (MainThread) [custom_components.tuya_local.device] Failed to refresh device state for Test.
```

### DPS information

```text
Received like from there: https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_4-create-a-cloud-project

162 Device Restart
134 Motion Switch
103 Vision Flip
231 Switch Channel
104 OSD Watermark
136 Doorbell AActive (typo in original string)
232 lock2
233 lock_support
106 Motion Sensitivity
109 Get Memory Card Capacity
110 Memory Card Status
111 Format Memory Card
115 Motion Detection (log empty, also scenes on Tuya not works with this - potentially bug in software)
148 Door lock
117 Formatted State
185 Alarm Report
154 Doorbell Snapshot

-------

Response from "Query properties":

{
  "result": {
    "properties": [
      {
        "code": "basic_flip",
        "custom_name": "",
        "dp_id": 103,
        "time": 1726839219298,
        "type": "bool",
        "value": false
      },
      {
        "code": "basic_osd",
        "custom_name": "",
        "dp_id": 104,
        "time": 1726839218976,
        "type": "bool",
        "value": false
      },
      {
        "code": "motion_sensitivity",
        "custom_name": "",
        "dp_id": 106,
        "time": 1726839224301,
        "type": "enum",
        "value": "2"
      },
      {
        "code": "sd_storge",
        "custom_name": "",
        "dp_id": 109,
        "time": 1726839218980,
        "type": "string",
        "value": "30514624|23033056|7481568"
      },
      {
        "code": "sd_status",
        "custom_name": "",
        "dp_id": 110,
        "time": 1726839218984,
        "type": "value",
        "value": 1
      },
      {
        "code": "sd_format",
        "custom_name": "",
        "dp_id": 111,
        "time": 1725971695319,
        "type": "bool",
        "value": true
      },
      {
        "code": "movement_detect_pic",
        "custom_name": "",
        "dp_id": 115,
        "time": 1721249439402,
        "type": "raw"
      },
      {
        "code": "sd_format_state",
        "custom_name": "",
        "dp_id": 117,
        "time": 1726829189179,
        "type": "value",
        "value": 0
      },
      {
        "code": "motion_switch",
        "custom_name": "",
        "dp_id": 134,
        "time": 1726829189511,
        "type": "bool",
        "value": false
      },
      {
        "code": "doorbell_active",
        "custom_name": "",
        "dp_id": 136,
        "time": 1726829189394,
        "type": "string",
        "value": "-1"
      },
      {
        "code": "accessory_lock",
        "custom_name": "",
        "dp_id": 148,
        "time": 1726839219576,
        "type": "bool",
        "value": false
      },
      {
        "code": "doorbell_pic",
        "custom_name": "",
        "dp_id": 154,
        "time": 1721249439402,
        "type": "raw"
      },
      {
        "code": "device_restart",
        "custom_name": "",
        "dp_id": 162,
        "time": 1721249439402,
        "type": "bool",
        "value": false
      },
      {
        "code": "alarm_message",
        "custom_name": "",
        "dp_id": 185,
        "time": 1726824201490,
        "type": "raw",
        "value": "eyJ2IjoiNS4wIiwiY21kIjoiaXBjX21vdGlvbiIsInR5cGUiOiJpbWFnZSIsIndpdGgiOiJyZXNvdXJjZXMiLCJmaWxlcyI6W1sidHktZXUtc3RvcmFnZTMwLXBpYyIsIi9mZGRiNTItMTUyMzg3ODk1LWJ3bDA1ZWVlZTY2YjYwYTc3NDY0L2RldGVjdC8xNzI2ODI0MjAxLmpwZWciLCIwMDQwNGYyNjAyNjYwYTBlIiwiMTcyOTQxNjIwNCJdXX0="
      },
      {
        "code": "ipc_c_switch_channel",
        "custom_name": "",
        "dp_id": 231,
        "time": 1726829189509,
        "type": "string",
        "value": ""
      },
      {
        "code": "accessory_lock2",
        "custom_name": "",
        "dp_id": 232,
        "time": 1726829191632,
        "type": "bool",
        "value": false
      },
      {
        "code": "access_lock_support",
        "custom_name": "",
        "dp_id": 233,
        "time": 1726824288039,
        "type": "string",
        "value": "148,232"
      }
    ]
  },
  "success": true,
  "t": 1726842636228,
  "tid": "e6a2350c775c11efb77736033862a1ba"
}
```

### Product ID

csr2fqitalj5o0tq

### Product Name

Smart Monitor 

### Information about how the device functions

Hello LocalTuya team,

I would like to request support for a new device—a popular, budget-friendly Tuya video doorbell from AliExpress. Here it's response from "Query Device Details" with more information:

```
{
  "result": {
    "active_time": 1721249439,
    "bind_space_id": "152387895",
    "category": "sp",
    "create_time": 1721249439,
    "custom_name": "",
    "icon": "smart/icon/ay1565761798595HD4IR/1657503642ddfe877df8d.png",
    "id": "<REDACTED>",
    "ip": "<REDACTED>",
    "is_online": true,
    "lat": "52.37",
    "local_key": "<REDACTED>",
    "lon": "16.95",
    "model": "",
    "name": "Security Camera ",
    "product_id": "csr2fqitalj5o0tq",
    "product_name": "Smart Monitor ",
    "sub": false,
    "time_zone": "+02:00",
    "update_time": 1726607527,
    "uuid": "bwl05eeee66b60a77464"
  },
  "success": true,
  "t": 1726842594710,
  "tid": "cde0b416775c11efb77736033862a1ba"
}
```

I have been debugging this device using the tinytuya library and encountered some issues I’m hoping you could assist with or provide suggestions for.

I can successfully connect to the device using the following code:
```
device = tinytuya.Device(
      dev_id=device_id,
      address=device_ip,
      local_key=local_key,
      dev_type = "device22",
      version=3.3)
device.add_dps_to_request(103)
data =  device.status()
print(data)
```

While this connection works and returns valid data, it resets some settings on the device, such as motion detection and the watermark. The line `device.add_dps_to_request(103)` is required—without it, no data is returned at all. However, I’m unable to fetch more than one DPS value in a single request. I've attempted to manually create a payload and tried adding multiple `add_dps_to_request` lines, but only the first value is returned. To retrieve another DPS value, I need to recreate the Device object each time.

For reference, here are the responses for different DPS codes I managed to retrieve:
```
103: {'dps': {'103': False}, 't': 1725971631}
104: {'dps': {'104': False}, 't': 1725971643}
106: {'dps': {'106': '0'}, 't': 1725971658}
109: {'dps': {'109': '30521344|30009056|512288'}, 't': 1725971616}
109 after call 111: {'dps': {'109': '30514624|144|30514480'}, 't': 1725971734}
110: {'dps': {'110': 1}, 't': 1725971675}
111: {'dps': {'117': 0}, 't': 1725971695}
115: error and device reboot
117: {'dps': {'117': 100}, 't': 1725971718}
134: {'dps': {'134': False}, 't': 1725971907}
136: {'dps': {'136': '-1'}, 't': 1725971920}
148: DEBUG:status() received data=None
154: error and device reboot
162: DEBUG:status() received data=None
185: error and device reboot
231: {'dps': {'231': ''}, 't': 1725971993}
232: {'dps': {'232': True}, 't': 1725972008}
233: DEBUG:status() received data=None
```

I’ve also attached logs for a successful connection (DPS 103) and an error (DPS 115, which causes the device to reboot).

Example log for DPS 103:
```
DEBUG:status() entry (dev_type is device22)
DEBUG:final payload_dict for '<REDACTED>' ('v3.3'/'device22'): {1: {'command': {'gwId': '', 'devId': '', 'uid': '', 't': ''}}, 7: {'command': {'devId': '', 'uid': '', 't': ''}}, 8: {'command': {'gwId': '', 'devId': ''}}, 9: {'command': {'gwId': '', 'devId': ''}}, 10: {'command': {'devId': '', 'uid': '', 't': ''}, 'command_override': 13}, 13: {'command': {'devId': '', 'uid': '', 't': ''}}, 16: {'command': {'devId': '', 'uid': '', 't': ''}}, 18: {'command': {'dpId': [18, 19, 20]}}, 64: {'command': {'reqType': '', 'data': {}}}}
DEBUG:building command 10 payload=b'{"devId":"<REDACTED>","uid":"<REDACTED>","t":"1726843490","dps":{"103":null}}'
DEBUG:sending payload
DEBUG:payload encrypted=b'000055aa000000010000000d00000087332e33000000000000000000000000e5f7d643a2c1fe68e289323b46eb6b9eb34959db86d42b953f4423b25f9e8aa9653e340564372f85cda4f2fe79df7f4e67dc42211b2fae30592644b6e6a38edb9ea71e53fdef46c30cfafaf9acf51a52674013f30ded3ab2296109f29e4f67ba99440aaf22042ab5f46ab151c22eaa2c5eb3917c0000aa55'
DEBUG:received data=b'000055aa000000010000000d0000000c00000000302b238a0000aa55'
DEBUG:received null payload (TuyaMessage(seqno=1, cmd=13, retcode=0, payload=b'', crc=808133514, crc_good=True, prefix=21930, iv=None)), fetch new one - retry 0 / 5
DEBUG:received data=b'000055aa00000000000000080000004b00000000332e33000000000000d4810000000100613dbcaa88b9f0691ccd181c2b73963625aca05c0a9627b1ca43b25a79ee6cb927714a1a1bda26e2157fed951699ad0d7d71b40000aa55'
DEBUG:received message=TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b"3.3\x00\x00\x00\x00\x00\x00\xd4\x81\x00\x00\x00\x01\x00a=\xbc\xaa\x88\xb9\xf0i\x1c\xcd\x18\x1c+s\x966%\xac\xa0\\\n\x96'\xb1\xcaC\xb2Zy\xeel\xb9'qJ\x1a\x1b\xda&\xe2\x15\x7f\xed\x95\x16\x99\xad", crc=226324916, crc_good=True, prefix=21930, iv=None)
DEBUG:raw unpacked message = TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b"3.3\x00\x00\x00\x00\x00\x00\xd4\x81\x00\x00\x00\x01\x00a=\xbc\xaa\x88\xb9\xf0i\x1c\xcd\x18\x1c+s\x966%\xac\xa0\\\n\x96'\xb1\xcaC\xb2Zy\xeel\xb9'qJ\x1a\x1b\xda&\xe2\x15\x7f\xed\x95\x16\x99\xad", crc=226324916, crc_good=True, prefix=21930, iv=None)
DEBUG:decode payload=b"3.3\x00\x00\x00\x00\x00\x00\xd4\x81\x00\x00\x00\x01\x00a=\xbc\xaa\x88\xb9\xf0i\x1c\xcd\x18\x1c+s\x966%\xac\xa0\\\n\x96'\xb1\xcaC\xb2Zy\xeel\xb9'qJ\x1a\x1b\xda&\xe2\x15\x7f\xed\x95\x16\x99\xad"
DEBUG:removing 3.x=b"\x00a=\xbc\xaa\x88\xb9\xf0i\x1c\xcd\x18\x1c+s\x966%\xac\xa0\\\n\x96'\xb1\xcaC\xb2Zy\xeel\xb9'qJ\x1a\x1b\xda&\xe2\x15\x7f\xed\x95\x16\x99\xad"
DEBUG:decrypting=b"\x00a=\xbc\xaa\x88\xb9\xf0i\x1c\xcd\x18\x1c+s\x966%\xac\xa0\\\n\x96'\xb1\xcaC\xb2Zy\xeel\xb9'qJ\x1a\x1b\xda&\xe2\x15\x7f\xed\x95\x16\x99\xad"
DEBUG:decrypted 3.x payload='{"dps":{"103":false},"t":1726843489}'
DEBUG:payload type = <class 'str'>
DEBUG:decoded results='{"dps":{"103":false},"t":1726843489}'
DEBUG:status() received data={'dps': {'103': False}, 't': 1726843489}
```

Error log for DPS 115:
```
DEBUG:status() entry (dev_type is device22)
DEBUG:final payload_dict for '<REDACTED>' ('v3.3'/'device22'): {1: {'command': {'gwId': '', 'devId': '', 'uid': '', 't': ''}}, 7: {'command': {'devId': '', 'uid': '', 't': ''}}, 8: {'command': {'gwId': '', 'devId': ''}}, 9: {'command': {'gwId': '', 'devId': ''}}, 10: {'command': {'devId': '', 'uid': '', 't': ''}, 'command_override': 13}, 13: {'command': {'devId': '', 'uid': '', 't': ''}}, 16: {'command': {'devId': '', 'uid': '', 't': ''}}, 18: {'command': {'dpId': [18, 19, 20]}}, 64: {'command': {'reqType': '', 'data': {}}}}
DEBUG:building command 10 payload=b'{"devId":"<REDACTED>","uid":"<REDACTED>","t":"1726843612","dps":{"115":null}}'
DEBUG:sending payload
DEBUG:payload encrypted=b'000055aa000000010000000d00000087332e33000000000000000000000000e5f7d643a2c1fe68e289323b46eb6b9eb34959db86d42b953f4423b25f9e8aa9653e340564372f85cda4f2fe79df7f4e67dc42211b2fae30592644b6e6a38edbb661ba214d7561310a431023e98a88071d2dd7ed9a90c973788f23a5371c988699440aaf22042ab5f46ab151c22eaa2c64e670660000aa55'
DEBUG:received data=b'000055aa000000010000000d0000000c00000000302b238a0000aa55'
DEBUG:received null payload (TuyaMessage(seqno=1, cmd=13, retcode=0, payload=b'', crc=808133514, crc_good=True, prefix=21930, iv=None)), fetch new one - retry 0 / 5
DEBUG:_recv_all(): no data? b''
DEBUG:_recv_all(): no data? b''
DEBUG:Error decoding received data - read retry 1/5
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1149, in _send_receive
    rmsg = self._receive()
           ^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1037, in _receive
    data = self._recv_all( min_len )
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1017, in _recv_all
    raise DecodeError('No data received - connection closed?')
tinytuya.core.DecodeError: No data received - connection closed?
DEBUG:_recv_all(): no data? b''
DEBUG:_recv_all(): no data? b''
DEBUG:Error decoding received data - read retry 2/5
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1149, in _send_receive
    rmsg = self._receive()
           ^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1037, in _receive
    data = self._recv_all( min_len )
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1017, in _recv_all
    raise DecodeError('No data received - connection closed?')
tinytuya.core.DecodeError: No data received - connection closed?
DEBUG:_recv_all(): no data? b''
DEBUG:_recv_all(): no data? b''
DEBUG:Error decoding received data - read retry 3/5
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1149, in _send_receive
    rmsg = self._receive()
           ^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1037, in _receive
    data = self._recv_all( min_len )
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1017, in _recv_all
    raise DecodeError('No data received - connection closed?')
tinytuya.core.DecodeError: No data received - connection closed?
DEBUG:_recv_all(): no data? b''
DEBUG:_recv_all(): no data? b''
DEBUG:Error decoding received data - read retry 4/5
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1149, in _send_receive
    rmsg = self._receive()
           ^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1037, in _receive
    data = self._recv_all( min_len )
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1017, in _recv_all
    raise DecodeError('No data received - connection closed?')
tinytuya.core.DecodeError: No data received - connection closed?
DEBUG:_recv_all(): no data? b''
DEBUG:_recv_all(): no data? b''
DEBUG:Error decoding received data - read retry 5/5
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1149, in _send_receive
    rmsg = self._receive()
           ^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1037, in _receive
    data = self._recv_all( min_len )
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tinytuya\core.py", line 1017, in _recv_all
    raise DecodeError('No data received - connection closed?')
tinytuya.core.DecodeError: No data received - connection closed?
DEBUG:status() received data=None
```

At this point, I'm out of ideas for how to resolve these issues and would greatly appreciate any guidance or suggestions on how to fix the payload handling, or general pointers for successfully integrating this device with LocalTuya.

I’m happy to assist with further debugging and testing if needed. Let me know if you need additional information.

Thank you in advance for your support!

Best regards,
paulomac1000

**Comment by make-all** [comment]
The message "Retrying after exception <class 'TypeError'> argument of type 'NoneType' is not iterable (2/3)" indicates that this device returns no data over the local protocol, so it will not be possible to support

**Comment by paulomac1000** [comment]
@make-all I was able to receive some of the local values, can we add them as configuration into homeassistant?
