### ISSUE TITLE
Request support for Könighaus M1000 Infrared Heating

### ISSUE THREAD

**Issue by hermann1514** [make-all/tuya-local#2328]
### Log message

```text
Device ID Heizung: <span style="color: #272e3b;">bffd13b3ead6151905ayc1</span>

<span style="color: yellow;">2024-09-23 09:01:44.745 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to walk with args ('/config/custom_components/tuya_local/devices',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 984: for path, dirs, files in walk(_CONFIG_DIR): (offender: /config/custom_components/tuya_local/helpers/device_config.py, line 984: for path, dirs, files in walk(_CONFIG_DIR):), please create a bug report at https://github.com/make-all/tuya-local/issues</span>

For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#walk

Traceback (most recent call last):

File "", line 198, in _run_module_as_main

File "", line 88, in _run_code

File "/usr/src/homeassistant/homeassistant/_*main*_.py", line 223, in

sys.exit(main())

File "/usr/src/homeassistant/homeassistant/_*main*_.py", line 209, in main

exit_code = runner.run(runtime_conf)

File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run

return loop.run_until_complete(setup_and_run_hass(runtime_config))

File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete

self.run_forever()

File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever

self._run_once()

File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once

handle._run()

File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run

self._context.run(self._callback, *self._args)

File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request

resp = await request_handler(request)

File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle

resp = await handler(request)

File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware

response = await handler(request)

File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle

result = await handler(request, **request.match_info)

File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin

return await func(self, request, *args, **kwargs)

File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post

return await super().post(request, flow_id)

File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper

return await method(view, request, data, *args, **kwargs)

File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post

result = await self._flow_mgr.async_configure(flow_id, data)

File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure

result = await self._async_configure(flow_id, user_input)

File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure

result = await self._async_handle_step(

File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step

result: _FlowResultT = await getattr(flow, method)(user_input)

File "/config/custom_components/tuya_local/config_flow.py", line 436, in async_step_local

return await self.async_step_select_type()

File "/config/custom_components/tuya_local/config_flow.py", line 474, in async_step_select_type

async for type in self.device.async_possible_types():

File "/config/custom_components/tuya_local/device.py", line 364, in async_possible_types

for match in possible:

File "/config/custom_components/tuya_local/helpers/device_config.py", line 992, in possible_matches

for cfg in available_configs():

File "/config/custom_components/tuya_local/helpers/device_config.py", line 984, in available_configs

for path, dirs, files in walk(_CONFIG_DIR):

<span style="color: yellow;">2024-09-23 09:01:44.749 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to scandir with args ('/config/custom_components/tuya_local/devices',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 984: for path, dirs, files in walk(_CONFIG_DIR): (offender: <frozen os>, line 366: ?), please create a bug report at https://github.com/make-all/tuya-local/issues</span>

For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#scandir

Traceback (most recent call last):

File "", line 198, in _run_module_as_main

File "", line 88, in _run_code

File "/usr/src/homeassistant/homeassistant/_*main*_.py", line 223, in

sys.exit(main())

File "/usr/src/homeassistant/homeassistant/_*main*_.py", line 209, in main

exit_code = runner.run(runtime_conf)

File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run

return loop.run_until_complete(setup_and_run_hass(runtime_config))

File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete

self.run_forever()

File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever

self._run_once()

File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once

handle._run()

File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run

self._context.run(self._callback, *self._args)

File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request

resp = await request_handler(request)

File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle

resp = await handler(request)

File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware

response = await handler(request)

File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle

result = await handler(request, **request.match_info)

File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin

return await func(self, request, *args, **kwargs)

File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post

return await super().post(request, flow_id)

File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper

return await method(view, request, data, *args, **kwargs)

File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post

result = await self._flow_mgr.async_configure(flow_id, data)

File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure

result = await self._async_configure(flow_id, user_input)

File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure

result = await self._async_handle_step(

File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step

result: _FlowResultT = await getattr(flow, method)(user_input)

File "/config/custom_components/tuya_local/config_flow.py", line 436, in async_step_local

return await self.async_step_select_type()

File "/config/custom_components/tuya_local/config_flow.py", line 474, in async_step_select_type

async for type in self.device.async_possible_types():

File "/config/custom_components/tuya_local/device.py", line 364, in async_possible_types

for match in possible:

File "/config/custom_components/tuya_local/helpers/device_config.py", line 992, in possible_matches

for cfg in available_configs():

File "/config/custom_components/tuya_local/helpers/device_config.py", line 984, in available_configs

for path, dirs, files in walk(_CONFIG_DIR):

<span style="color: yellow;">2024-09-23 09:01:44.756 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/tuya_local/devices/9in1_airquality_monitor.yaml',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 230: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues</span>

For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open

Traceback (most recent call last):

File "", line 198, in _run_module_as_main

File "", line 88, in _run_code

File "/usr/src/homeassistant/homeassistant/_*main*_.py", line 223, in

sys.exit(main())

File "/usr/src/homeassistant/homeassistant/_*main*_.py", line 209, in main

exit_code = runner.run(runtime_conf)

File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run

return loop.run_until_complete(setup_and_run_hass(runtime_config))

File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete

self.run_forever()

File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever

self._run_once()

File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once

handle._run()

File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run

self._context.run(self._callback, *self._args)

File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request

resp = await request_handler(request)

File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle

resp = await handler(request)

File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware

return await handler(request)

File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware

response = await handler(request)

File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle

result = await handler(request, **request.match_info)

File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin

return await func(self, request, *args, **kwargs)

File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post

return await super().post(request, flow_id)

File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper

return await method(view, request, data, *args, **kwargs)

File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post

result = await self._flow_mgr.async_configure(flow_id, data)

File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure

result = await self._async_configure(flow_id, user_input)

File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure

result = await self._async_handle_step(

File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step

result: _FlowResultT = await getattr(flow, method)(user_input)

File "/config/custom_components/tuya_local/config_flow.py", line 436, in async_step_local

return await self.async_step_select_type()

File "/config/custom_components/tuya_local/config_flow.py", line 474, in async_step_select_type

async for type in self.device.async_possible_types():

File "/config/custom_components/tuya_local/device.py", line 364, in async_possible_types

for match in possible:

File "/config/custom_components/tuya_local/helpers/device_config.py", line 993, in possible_matches

parsed = TuyaDeviceConfig(cfg)

File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in _*init*_

self._config = load_yaml(filename)

<span style="color: yellow;">2024-09-23 09:01:46.698 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches hama_radiator_controller with quality of 15%. DPS: {"updated_at": 1727074904.7362993, "1": false, "2": "manual", "3": "manual", "16": 225, "24": 178, "101": false, "102": 180, "103": 220, "104": 50, "106": "online", "108": "heat", "111": 240, "112": 180, "113": 220, "114": 180, "115": 400, "116": 180, "117": 240, "118": false, "120": true}</span>

<span style="color: yellow;">2024-09-23 09:01:46.698 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log message with any new device request to https://github.com/make-all/tuya-local/issues/</span>
```

### DPS information

```text
{
"result": {
"properties": [
{
"code": "switch",
"custom_name": "",
"dp_id": 1,
"time": 1727072725720,
"type": "bool",
"value": false
},
{
"code": "mode",
"custom_name": "",
"dp_id": 2,
"time": 1726943080227,
"type": "enum",
"value": "manual"
},
{
"code": "work_state",
"custom_name": "",
"dp_id": 3,
"time": 1726943080223,
"type": "enum",
"value": "manual"
},
{
"code": "temp_set",
"custom_name": "",
"dp_id": 16,
"time": 1726949331980,
"type": "value",
"value": 225
},
{
"code": "temp_current",
"custom_name": "",
"dp_id": 24,
"time": 1727073661143,
"type": "value",
"value": 177
},
{
"code": "week_program_5",
"custom_name": "",
"dp_id": 72,
"time": 1726842557278,
"type": "raw",
"value": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
},
{
"code": "relay_status",
"custom_name": "",
"dp_id": 101,
"time": 1727072726449,
"type": "bool",
"value": false
},
{
"code": "eco_mode_temp_heat",
"custom_name": "",
"dp_id": 102,
"time": 1726842557324,
"type": "value",
"value": 180
},
{
"code": "comfort_mode_temp_heat",
"custom_name": "",
"dp_id": 103,
"time": 1726842557332,
"type": "value",
"value": 220
},
{
"code": "holiday_mode_temp_heat",
"custom_name": "",
"dp_id": 104,
"time": 1726842557335,
"type": "value",
"value": 50
},
{
"code": "unpair_rf_thermostat",
"custom_name": "",
"dp_id": 105,
"time": 1726840413540,
"type": "bool",
"value": false
},
{
"code": "rf_thermostat_pair_status",
"custom_name": "",
"dp_id": 106,
"time": 1726937175174,
"type": "enum",
"value": "online"
},
{
"code": "clear_program_mode",
"custom_name": "",
"dp_id": 107,
"time": 1726840413540,
"type": "bool",
"value": false
},
{
"code": "heating_mode",
"custom_name": "",
"dp_id": 108,
"time": 1726842557342,
"type": "enum",
"value": "heat"
},
{
"code": "set_mode_settings_default",
"custom_name": "",
"dp_id": 109,
"time": 1726840413540,
"type": "bool",
"value": false
},
{
"code": "set_location_inside",
"custom_name": "",
"dp_id": 110,
"time": 1726840413540,
"type": "bool",
"value": false
},
{
"code": "location_inside_temp_heat",
"custom_name": "",
"dp_id": 111,
"time": 1726842557345,
"type": "value",
"value": 240
},
{
"code": "locationoutside_temp_heat",
"custom_name": "",
"dp_id": 112,
"time": 1726842557347,
"type": "value",
"value": 180
},
{
"code": "eco_mode_temp_cool",
"custom_name": "",
"dp_id": 113,
"time": 1726842559382,
"type": "value",
"value": 220
},
{
"code": "comfort_mode_temp_cool",
"custom_name": "",
"dp_id": 114,
"time": 1726842557395,
"type": "value",
"value": 180
},
{
"code": "holiday_mode_temp_cool",
"custom_name": "",
"dp_id": 115,
"time": 1726842557397,
"type": "value",
"value": 400
},
{
"code": "location_inside_temp_cool",
"custom_name": "",
"dp_id": 116,
"time": 1726842557401,
"type": "value",
"value": 180
},
{
"code": "locationoutside_temp_cool",
"custom_name": "",
"dp_id": 117,
"time": 1726842557410,
"type": "value",
"value": 240
},
{
"code": "window_open_status",
"custom_name": "",
"dp_id": 118,
"time": 1726842590017,
"type": "bool",
"value": false
},
{
"code": "rf_message",
"custom_name": "",
"dp_id": 119,
"time": 1727074422239,
"type": "raw",
"value": "+/02ANIAsQUFAAC7AAA="
},
{
"code": "user_mode_switch_status",
"custom_name": "",
"dp_id": 120,
"time": 1726842557412,
"type": "bool",
"value": true
}
]
},
"success": true,
"t": 1727074590039,
"tid": "f5e03a23797811efbc016e7818a0f8a2"
}
```

### Product ID

rufjdpbdogijhq89

### Product Name

Könighaus M1000 / in Cloud Name: W Modem

### Information about how the device functions

Is a heating controller that can activate the temperature and various heating programmes.
In principle, the functions are the same as a heating controller.

**Comment by hermann1514** [comment]
sorry -same as https://github.com/make-all/tuya-local/issues/2327
double post. Please delete

**Comment by hermann1514** [comment]
double post. Please delete
