### ISSUE TITLE
"Unsupported operand type(s) for *: 'int' and 'NoneType' " error on LEDKIA fan and led controller

### ISSUE THREAD

**Issue by bedtiming** [make-all/tuya-local#236]
Just in case you had to integrate devices similar to this one, I understood the operating logic of the light: the command to change the color temperature turns off the light and turns it back on an instant later with the new color temperature. So even if the light is turned off and on again quickly (within about 10 seconds), the color temperature changes. This is not very functional logic. If I change the color temperature and change the brightness within 10 seconds, the error appears and two "beeps" are heard (therefore two almost simultaneous commands). If I wait more than 10-15 seconds before changing the brightness the error does not appear.
However, that's fine for me, the fault lies with the logic of this strange light, not your excellent integration.
Thanks again for your effort!

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tuya_local/helpers/device_config.py:544
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 20:32:52 (5 occurrences)
Last logged: 20:33:44

[139647910136080] unsupported operand type(s) for *: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 693, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 933, in state_attributes
    data[ATTR_COLOR_TEMP] = self.color_temp
  File "/config/custom_components/tuya_local/generic/light.py", line 96, in color_temp
    unscaled = self._color_temp_dps.get_value(self._device)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 325, in get_value
    return self._map_from_dps(device.get_property(self.id), device)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 544, in _map_from_dps
    result = -1 * result + r["min"] + r["max"]
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'`

**Comment by bedtiming** [comment]
it works like a charm. With the latest version no more "beeps" are heard while brightness is being adjusted, so no DP more than necessary.
Thanks very much, again!
