### ISSUE TITLE
Smart IR with T&H cannot be trained

### ISSUE THREAD

**Issue by LotharWoman** [make-all/tuya-local#2528]
### Description

Link to devices:
- [https://www.pearl.de/a-ZX5130-1254.shtml](url)
- [https://www.aliexpress.com/gcp/300000512/nnpage2024?spm=a2g0o.detail.pcDetailTopMoreOtherSeller.2.7e9e9CCF9CCFjh&productIds=1005006677939904&pha_manifest=ssr&_immersiveMode=true&disableNav=YES&sourceName=pcDetailTopMoreOtherSellerProduct&utparam-url=scene%3ApcDetailTopMoreOtherSeller%7Cquery_from%3A](url)

No commands can be taught to the Smart IR with T&H device via HomeAssistant. It is also not possible to switch the IR function on/off.
Humidity sensor and temperature sensor are recognized and both work. The detected switch entity for the IR remote control results in an error.

### Steps to reproduce

1. switch IR on/off
2. Perform "Action" training of the remote control

### Expected behaviour

1. Turn on/off
2. learn new IR-commands

### Additional context

1.
`2024-11-20 18:58:15.270 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2024-11-20 18:58:15.270 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2024-11-20 18:58:15.278 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1712, in async_toggle
    await self.async_turn_off(**kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1695, in async_turn_off
    await self.hass.async_add_executor_job(ft.partial(self.turn_off, **kwargs))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1691, in turn_off
    raise NotImplementedError
NotImplementedError`

2.
`2024-11-20 19:03:38.931 WARNING (MainThread) [custom_components.tuya_local.remote] Timed out without receiving code in remote.learn_command
2024-11-20 19:03:38.950 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: No remote code received within 30.0 seconds
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tuya_local/remote.py", line 267, in async_learn_command
    code = await self._async_learn_command(command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/remote.py", line 305, in _async_learn_command
    raise TimeoutError(
TimeoutError: No remote code received within 30.0 seconds
2024-11-20 19:03:3`

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
I'm not sure your device is the same as any that is already supported. I think it would be better if you filed this as a new device request, so all the info needed to evaluate it is there. Or update this ticket with logs showing dps received when you add the device, and iot.tuya.com info for the device.

**Comment by LotharWoman** [comment]
Thanks for your answer, but i m only user.

Unfortunately, I don't see DPs anywhere, like on older Tuya devices. Neither in tuya local, nor local tuya or in the developer portal.

From Tuya Debug:

![grafik](https://github.com/user-attachments/assets/2e8a3e7f-043c-488a-b9c4-cd8327fe20f7)

![grafik](https://github.com/user-attachments/assets/0c98fde5-ca92-45e3-aa1b-bee5d1383f8b)

![grafik](https://github.com/user-attachments/assets/53791d66-d893-442a-9571-3925067f0058)

![grafik](https://github.com/user-attachments/assets/4f2bbb25-8d0f-4d03-8926-4af084ed0eb9)

and here after change in developer "standart instruction" to "DP instruction"

![grafik](https://github.com/user-attachments/assets/6c528672-eedf-433b-9f8a-f976e1d61722)

I hope this help.

**Comment by make-all** [comment]
The information that is required from iot.tuya.com comes from the API Explorer (under Cloud), in the Device Control section: Query Things Data Model. You need to give it your device id to get the information.

If you currently have the device connected to tuya-local, then the Device Diagnostics can be provided instead of logs, as that will show all dps that have been received from the device, so any others apart from temperature and humidity might show up.

**Comment by LotharWoman** [comment]
Here the data from "Things Data Model"
`{
  "result": {
    "model": "{\"modelId\":\"f1qbq8\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"attribute\":\"2\",\"trigger\":\"direct\"},\"name\":\"温度\",\"typeSpec\":{\"type\":\"value\",\"max\":600,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"humidity_value\",\"description\":\"\",\"extensions\":{\"attribute\":\"2\",\"trigger\":\"direct\"},\"name\":\"湿度\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},{\"abilityId\":201,\"accessMode\":\"rw\",\"code\":\"ir_send\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"红外控制下发\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":3072}},{\"abilityId\":202,\"accessMode\":\"ro\",\"code\":\"ir_study_code\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"红外学习值上报\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}}]}]}"
  },
  "success": true,
  "t": 1732145263089,
  "tid": "0a861d38a79711ef9520ae18e4d9fbe2"
}`


and here the diagnostic:
[config_entry-tuya_local-01JD4S9B1W223N1R59HYQ9WEJX.json](https://github.com/user-attachments/files/17837889/config_entry-tuya_local-01JD4S9B1W223N1R59HYQ9WEJX.json)

I think it is ID 201 which is not recognized.
`    "cached_state": {
      "updated_at": 1732145316.871974,
      "101": 176,
      "102": 59,
      "201": "{\\\"control\\\":\\\"study_exit\\\"}"`

Thank you for your attention

**Comment by LotharWoman** [comment]
Thank you,
 for a quick solution. Learning and sending commands now works wonderfully. 👍
The entity for switch turn IR "on/off". still triggers an error message. But I think this is normal because the device does not support turning off the IR sensor.

`
2024-11-21 18:46:23.093 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139898143284464] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1695, in async_turn_off
    await self.hass.async_add_executor_job(ft.partial(self.turn_off, **kwargs))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1691, in turn_off
    raise NotImplementedError
NotImplementedError`
