### ISSUE TITLE
Request support for KNOB LOCK

### ISSUE THREAD

**Issue by FillHK** [make-all/tuya-local#2560]
### Log message

```text
Exception in _update_handler when dispatching 'localtuya_eb0d7905c6272cc3dag9yy': ({'101': True, '103': True, '104': False, '105': False, '106': '1', '108': '0', '109': '61170688|204800|60965888', '110': 1, '117': 0, '120': False, '124': 'auto', '127': 'motion', '134': True, '138': False, '139': False, '140': '0', '150': False, '151': '1', '158': 100, '159': False, '161': True, '168': False, '169': '', '170': True, '188': '0', '231': True, '115': 'eyJ2IjoiMy4wIiwiYnVja2V0IjoidHktdXMtc3RvcmFnZTMwLXBpYyIsImZpbGVzIjpbWyIvMzQ4NmU1LTE5NjcwODAzMS16dGFjYzVkYWIyN2E5MzQxOTkzNC9kZXRlY3QvMTczMjY2OTc4NS5qcGVnIiwiOTEyNGQxMTBiYTQ0OTkwMiJdXX0=', '185': 'eyJ2IjoiMy4wIiwiYnVja2V0IjoidHktdXMtc3RvcmFnZTMwLXBpYyIsImNtZCI6ImlwY19odW1hbiIsInR5cGUiOiJpbWFnZSIsIndpdGgiOiJyZXNvdXJjZXMiLCJmaWxlcyI6W1siLzM0ODZlNS0xOTY3MDgwMzEtenRhY2M1ZGFiMjdhOTM0MTk5MzQvZGV0ZWN0LzE3MzI2NjQ2NjUuanBlZyIsImY3NzBiZGI3NWE2NjE5ZDQiXV19'},) Traceback (most recent call last): File "/config/custom_components/localtuya/entity.py", line 176, in _update_handler self.status_updated() File "/config/custom_components/localtuya/siren.py", line 64, in status_updated if state == self._config[CONF_STATE_ON].lower() or state == "true": ~~~~~~~~~~~~^^^^^^^^^^^^^^^ KeyError: 'state_on'
```

### Product ID

2hmqh0ty

### Product Name

KNOB LOCK

### DPS information

```text
Query Device Details:
---
{
  "result": {
    "active_time": 1730753495,
    "bind_space_id": "196708031",
    "category": "jtmspro",
    "create_time": 1730753495,
    "custom_name": "",
    "icon": "smart/icon/ay1566269753407dl25G/5768fe0def75e0f7678c56d0c547757c.png",
    "id": "eb6f5febe09c14200eahqf",
    "ip": "",
    "is_online": true,
    "lat": "33.0551",
    "local_key": "Jx=M{{FG?iA8D>7",
    "lon": "-97.0482",
    "model": "EL605A锐尔朗",
    "name": "KNOB LOCK",
    "product_id": "2hmqh0ty",
    "product_name": "KNOB LOCK",
    "sub": true,
    "time_zone": "-05:00",
    "update_time": 1732557092,
    "uuid": "6dd985327ee9c567"
  },
  "success": true,
  "t": 1732670676626,
  "tid": "5d68a181ac5e11efb0b89e5820c93cc8"
}

Query Properties:
--
{
  "result": {
    "properties": [
      {
        "code": "unlock_method_create",
        "custom_name": "",
        "dp_id": 1,
        "time": 1730753595896,
        "type": "raw",
        "value": "A/8BAQEAAA=="
      },
      {
        "code": "unlock_method_delete",
        "custom_name": "",
        "dp_id": 2,
        "time": 1730753495804,
        "type": "raw"
      },
      {
        "code": "unlock_method_modify",
        "custom_name": "",
        "dp_id": 3,
        "time": 1730753495804,
        "type": "raw"
      },
      {
        "code": "residual_electricity",
        "custom_name": "",
        "dp_id": 8,
        "time": 1732670737879,
        "type": "value",
        "value": 82
      },
      {
        "code": "anti_lock_outside",
        "custom_name": "",
        "dp_id": 11,
        "time": 1732670557745,
        "type": "bool",
        "value": true
      },
      {
        "code": "unlock_fingerprint",
        "custom_name": "",
        "dp_id": 12,
        "time": 1732670341000,
        "type": "value",
        "value": 1
      },
      {
        "code": "unlock_ble",
        "custom_name": "",
        "dp_id": 19,
        "time": 1732643035000,
        "type": "value",
        "value": 1
      },
      {
        "code": "lock_record",
        "custom_name": "",
        "dp_id": 20,
        "time": 1732670620094,
        "type": "raw",
        "value": "BAAAAAE="
      },
      {
        "code": "alarm_lock",
        "custom_name": "",
        "dp_id": 21,
        "time": 1730753495804,
        "type": "enum",
        "value": "wrong_finger"
      },
      {
        "code": "hijack",
        "custom_name": "",
        "dp_id": 22,
        "time": 1730753495804,
        "type": "bool",
        "value": false
      },
      {
        "code": "beep_volume",
        "custom_name": "",
        "dp_id": 31,
        "time": 1732650835864,
        "type": "enum",
        "value": "normal"
      },
      {
        "code": "reverse_lock",
        "custom_name": "",
        "dp_id": 32,
        "time": 1732670557736,
        "type": "bool",
        "value": true
      },
      {
        "code": "manual_lock",
        "custom_name": "",
        "dp_id": 46,
        "time": 1732670620092,
        "type": "bool",
        "value": true
      },
      {
        "code": "lock_motor_state",
        "custom_name": "",
        "dp_id": 47,
        "time": 1732670620213,
        "type": "bool",
        "value": false
      },
      {
        "code": "temporary_password_creat",
        "custom_name": "",
        "dp_id": 51,
        "time": 1730753495804,
        "type": "raw"
      },
      {
        "code": "synch_method",
        "custom_name": "",
        "dp_id": 54,
        "time": 1732643132000,
        "type": "raw",
        "value": "AQE="
      },
      {
        "code": "remote_no_dp_key",
        "custom_name": "",
        "dp_id": 61,
        "time": 1732645491992,
        "type": "raw",
        "value": "AAAB"
      },
      {
        "code": "unlock_phone_remote",
        "custom_name": "",
        "dp_id": 62,
        "time": 1732655974204,
        "type": "value",
        "value": 0
      },
      {
        "code": "record",
        "custom_name": "",
        "dp_id": 69,
        "time": 1730753495804,
        "type": "raw"
      },
      {
        "code": "check_code_set",
        "custom_name": "",
        "dp_id": 70,
        "time": 1730753498496,
        "type": "raw",
        "value": "AAL//zExNTg5MTA5AP//AA=="
      },
      {
        "code": "ble_unlock_check",
        "custom_name": "",
        "dp_id": 71,
        "time": 1732643035000,
        "type": "raw",
        "value": "AAL//zExNTg5MTA5AWdGCNsAAA=="
      },
      {
        "code": "remote_pd_setkey_check",
        "custom_name": "",
        "dp_id": 73,
        "time": 1732645502539,
        "type": "raw",
        "value": "AAL//zExNTg5MTA5AQABAA=="
      }
    ]
  },
  "success": true,
  "t": 1732670740113,
  "tid": "83415fbaac5e11efb0b89e5820c93cc8"
}
```
Query Things Data Model
```
{
  "result": {
    "model": "{\"modelId\":\"000004vrzy\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"unlock_method_create\",\"description\":\"【添加开锁方式】设备在线后，添加开锁方式。支持添加指密卡和人脸，以及支持管理员标记。\",\"extensions\":{\"iconName\":\"icon-a_up\",\"attribute\":\"1792\"},\"name\":\"添加开锁方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"unlock_method_delete\",\"description\":\"【删除开锁方式】设备在线后，删除开锁方式。支持删除指密卡和人脸。\",\"extensions\":{\"iconName\":\"icon-dp_rabbish\",\"attribute\":\"1792\"},\"name\":\"删除开锁方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"unlock_method_modify\",\"description\":\"【修改开锁方式】设备在线后，支持修改开锁方式的名称，以及密码的内容修改。\",\"extensions\":{\"iconName\":\"icon-edit\",\"attribute\":\"1792\"},\"name\":\"修改开锁方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":8,\"accessMode\":\"ro\",\"code\":\"residual_electricity\",\"description\":\"【设备状态】用于电量以百分比显示。范围-1～100，当设备上报数值-1时，不显示电量。（与DP9二选一）\",\"extensions\":{\"iconName\":\"icon-dp_battery\",\"attribute\":\"1280\"},\"name\":\"剩余电量\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"anti_lock_outside\",\"description\":\"【设备状态】若设备具有把手上提或锁舌上锁检测时，用于上报设备上锁的开关状态。仅在本智能锁产品支持在硬件能检测到把手上提或锁舌上锁，能够进行数据上报时，才启用本dp\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"上提反锁\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"unlock_fingerprint\",\"description\":\"【上报开锁记录】用于设备上报指纹开锁的记录。\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"指纹开锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"unlock_ble\",\"description\":\"【上报开锁记录】用于设备上报手机蓝牙开锁时的记录。\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"蓝牙开锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"lock_record\",\"description\":\"【上报关锁记录】用于设备上报门锁关锁的记录。\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"256\"},\"name\":\"关锁记录\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"alarm_lock\",\"description\":\"【告警记录】本地发生告警时，用于上报设备的告警记录。对应值说明：0=指纹试错报警、1=密码试错报警、2=卡试错报警、3=人脸试错报警、4=假锁（锁舌卡住）、5=高温报警、6=超时未关门、7=电子锁舌未弹出、8=防撬报警 、9=钥匙插入、10=低电报警、11=电量耗尽报警、12=震动报警、13=布防报警，如设备只用到告警dp中的几项，多余的内容也不需要删除。如删除则mcu在上报时的序号需要调整。建议开发者不要改动告警中的枚举值。如遇特殊情况，请在pm的指导下，进行增、删，以及配置多语言等操作\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"门锁告警\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"wrong_finger\",\"wrong_password\",\"wrong_card\",\"wrong_face\",\"tongue_bad\",\"too_hot\",\"unclosed_time\",\"tongue_not_out\",\"pry\",\"key_in\",\"low_battery\",\"power_off\",\"shock\",\"defense\"]}},{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"hijack\",\"description\":\"【告警记录】用于云端标记某个开锁方式为劫持告警开锁方式。该功能不需要mcu支持，启用本dp后，在app门锁的开门方式管理界面，可通过app对某解锁方案进行标记，标记为“劫持告警”的某个具体的解锁id操作开门时，会触发劫持告警的消息告警\",\"extensions\":{\"iconName\":\"icon-baojing\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"劫持告警\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":31,\"accessMode\":\"rw\",\"code\":\"beep_volume\",\"description\":\"【音量】用于设置设备本地导航语音音量大小。仅当本智能锁产品，硬件上支持门锁音量调节时，允许用户在app上进行切换操作的情况下，才启用本dp\",\"extensions\":{\"iconName\":\"icon-sound\",\"attribute\":\"1280\"},\"name\":\"门锁音量\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"mute\",\"normal\"]}},{\"abilityId\":32,\"accessMode\":\"rw\",\"code\":\"reverse_lock\",\"description\":\"【设备状态】若设备具有室内反锁检测时，用于上报室内反锁的开关状态。仅当本智能锁产品，硬件上功能检测反锁状态并能将数据上报，或允许通过app控制操作下发反锁指令的情况下，才启用本dp\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"反锁状态\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":46,\"accessMode\":\"rw\",\"code\":\"manual_lock\",\"description\":\"【落锁操作】用于触发设备执行落锁操作，可用于自动落锁和手动落锁的操作。\\n上报落锁（关锁）记录需使用dp=20 关锁记录。需要2个dp组合使用，完整实现关锁操作和关锁记录上报。在这两个dp之外，还需要使用dp47=落锁状态，进行落锁状态的上报，使得app上显示的锁的解锁/落锁状态与硬件本地保持一致\\t\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"手动落锁\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":47,\"accessMode\":\"ro\",\"code\":\"lock_motor_state\",\"description\":\"【设备状态】用于上报设备离合开关的状态，即锁的开关状态。\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"锁开合状态\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":51,\"accessMode\":\"rw\",\"code\":\"temporary_password_creat\",\"description\":\"【在线临时密码】用于添加在线临时密码，支持设置时间段及循环重复的时效。\",\"extensions\":{\"iconName\":\"icon-dp_add\",\"attribute\":\"1280\"},\"name\":\"添加临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":54,\"accessMode\":\"rw\",\"code\":\"synch_method\",\"description\":\"【同步开锁方式】用于手机同步设备本地所有的开锁方式。\",\"extensions\":{\"iconName\":\"icon-dp_upload\",\"attribute\":\"1792\"},\"name\":\"同步开锁方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":61,\"accessMode\":\"rw\",\"code\":\"remote_no_dp_key\",\"description\":\"【远程开锁】用于触发设备远程开锁操作。\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1280\"},\"name\":\"免密远程开锁（带密钥）\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":62,\"accessMode\":\"ro\",\"code\":\"unlock_phone_remote\",\"description\":\"【上报开锁记录】用于设备上报手机远程开锁的记录。\",\"extensions\":{\"iconName\":\"icon-shouji\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"远程手机开锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":69,\"accessMode\":\"rw\",\"code\":\"record\",\"description\":\"【获取开锁记录】用于手机主动获取设备本地存储的开门记录。\",\"extensions\":{\"iconName\":\"icon-dp_book\",\"attribute\":\"1280\"},\"name\":\"获取记录\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":70,\"accessMode\":\"rw\",\"code\":\"check_code_set\",\"description\":\"【蓝牙开锁】用于配置设备执行蓝牙解锁时需要的校验信息。\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1280\"},\"name\":\"配置蓝牙开锁校验码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":71,\"accessMode\":\"rw\",\"code\":\"ble_unlock_check\",\"description\":\"【蓝牙开锁】用于触发设备执行蓝牙解锁。触发源可以是手机、配件或靠近解锁。\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1280\"},\"name\":\"蓝牙开锁（带校验码）\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":73,\"accessMode\":\"rw\",\"code\":\"remote_pd_setkey_check\",\"description\":\"【远程开锁】用于配置远程开锁时需要的密钥。若设备需要进行远程开锁，该DP必选。\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1792\"},\"name\":\"设置远程开锁（带校验码）\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}}]}]}"
  },
  "success": true,
  "t": 1732671295602,
  "tid": "ce58e629ac5f11efb0b89e5820c93cc8"
}
```

### Information about how the device functions

Door lock is connected over Tuya Hub (it's BLE device) - everything works. 
With the Tuya (online) app - the device present in the list but has no properties (can't be controlled)
With [tuya-local](https://github.com/make-all/tuya-local) when I try to unlock have error:
![image](https://github.com/user-attachments/assets/adf10441-2ff5-45f1-85f2-e07e30f23a2d)

**Comment by FillHK** [comment]
Additional log:
`[36m2024-11-26 16:33:07.731 DEBUG (MainThread) [custom_components.tuya_local.device] Retrying after exception <class 'AttributeError'> Check device key or version (0/3)[0m
[36m2024-11-26 16:33:11.116 DEBUG (MainThread) [custom_components.tuya_local.device] Door lock new pending updates: {"46": {"value": true, "updated_at": 1732660391.1159382, "sent": false}}[0m
[36m2024-11-26 16:33:11.119 DEBUG (MainThread) [custom_components.tuya_local.device] Door lock sending dps update: {"46": true}[0m
[36m2024-11-26 16:33:13.708 DEBUG (MainThread) [custom_components.tuya_local.device] Door lock new pending updates: {"46": {"value": true, "updated_at": 1732660391.1335075, "sent": true}, "32": {"value": false, "updated_at": 1732660393.7082086, "sent": false}}[0m
[36m2024-11-26 16:33:13.719 DEBUG (MainThread) [custom_components.tuya_local.device] Door lock sending dps update: {"32": false}[0m
[33m2024-11-26 16:35:18.103 WARNING (MainThread) [custom_components.localtuya.coordinator] [eb9...2qr - 分离式多功能太阳能灯 3] Handshake with 192.168.31.60 failed: Sub device is not connected[0m
[33m2024-11-26 16:35:20.876 WARNING (MainThread) [custom_components.localtuya.coordinator] [eb6...hqf - KNOB LOCK] Handshake with 192.168.31.60 failed: Sub device is not connected[0m
[31m2024-11-26 16:38:45.817 ERROR (SyncWorker_2) [homeassistant.util.logging] Exception in _update_handler when dispatching 'localtuya_eb25007f73bbbbf8a4cqeb': ({'101': True, '103': True, '104': False, '105': False, '106': '1', '108': '0', '109': '0|0|0', '110': 5, '117': 0, '120': False, '124': 'auto', '127': 'motion', '134': True, '138': False, '139': False, '140': '0', '150': True, '151': '1', '158': 100, '159': False, '161': True, '168': False, '169': '', '170': True, '188': '0', '231': True, '115': 'eyJ2IjoiMy4wIiwiYnVja2V0IjoidHktdXMtc3RvcmFnZTMwLXBpYyIsImZpbGVzIjpbWyIvNjgxZDQ1LTE5NjcwODAzMS16dGFjYzU3Y2QwM2EwNGQ0Y2RjMi9kZXRlY3QvMTczMjY2MDcyNC5qcGVnIiwiMGQ4NWM2Y2JjYjA2ZGNjZCJdXX0=', '185': 'eyJ2IjoiMy4wIiwiYnVja2V0IjoidHktdXMtc3RvcmFnZTMwLXBpYyIsImNtZCI6ImlwY19odW1hbiIsInR5cGUiOiJpbWFnZSIsIndpdGgiOiJyZXNvdXJjZXMiLCJmaWxlcyI6W1siLzY4MWQ0NS0xOTY3MDgwMzEtenRhY2M1N2NkMDNhMDRkNGNkYzIvZGV0ZWN0LzE3MzI2NTg3MjYuanBlZyIsIjQzNGMxYzQ0NDRlMjQwMDQiXV19'},)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/entity.py", line 176, in _update_handler
    self.status_updated()
  File "/config/custom_components/localtuya/siren.py", line 64, in status_updated
    if state == self._config[CONF_STATE_ON].lower() or state == "true":
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'state_on'`

**Comment by make-all** [comment]
Report is for a different project

**Comment by FillHK** [comment]
I don't see other logs...
Help me please to get the logs.

Thank you
