### ISSUE TITLE
Request support for <productname>

### ISSUE THREAD

**Issue by palmareka** [make-all/tuya-local#2565]
### Log message

```text
Registrador: homeassistant.util.logging
Fuente: util/logging.py:95
Ocurrió por primera vez: 24 de noviembre de 2024, 19:27:33 (66 ocurrencias)
Última vez registrado: 17:58:21

Exception in _update_handler when dispatching 'localtuya_bfa39a887e68b7f744dbm5': ({'1': 'stop', '2': 75, '4': 'stop', '5': 95, '8': 'forward', '9': 'forward', '10': 18, '11': 18, '14': 'relay'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 413, in _update_handler self.status_updated() File "/config/custom_components/localtuya/cover.py", line 191, in status_updated if self._state.isupper(): ^^^^^^^^^^^^^^^^^^^ AttributeError: 'int' object has no attribute 'isupper'
Exception in _update_handler when dispatching 'localtuya_bfa39a887e68b7f744dbm5': ({'1': 'close', '2': 75, '4': 'stop', '5': 95, '8': 'forward', '9': 'forward', '10': 18, '11': 18, '14': 'relay'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 413, in _update_handler self.status_updated() File "/config/custom_components/localtuya/cover.py", line 191, in status_updated if self._state.isupper(): ^^^^^^^^^^^^^^^^^^^ AttributeError: 'int' object has no attribute 'isupper'
Exception in _update_handler when dispatching 'localtuya_bfa39a887e68b7f744dbm5': ({'1': 'stop', '2': 0, '4': 'stop', '5': 95, '8': 'forward', '9': 'forward', '10': 18, '11': 18, '14': 'relay'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 413, in _update_handler self.status_updated() File "/config/custom_components/localtuya/cover.py", line 191, in status_updated if self._state.isupper(): ^^^^^^^^^^^^^^^^^^^ AttributeError: 'int' object has no attribute 'isupper'
Exception in _update_handler when dispatching 'localtuya_bfa39a887e68b7f744dbm5': ({'1': 'stop', '2': 0, '4': 'close', '5': 95, '8': 'forward', '9': 'forward', '10': 18, '11': 18, '14': 'relay'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 413, in _update_handler self.status_updated() File "/config/custom_components/localtuya/cover.py", line 191, in status_updated if self._state.isupper(): ^^^^^^^^^^^^^^^^^^^ AttributeError: 'int' object has no attribute 'isupper'
Exception in _update_handler when dispatching 'localtuya_bfa39a887e68b7f744dbm5': ({'1': 'stop', '2': 0, '4': 'stop', '5': 0, '8': 'forward', '9': 'forward', '10': 18, '11': 18, '14': 'relay'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 413, in _update_handler self.status_updated() File "/config/custom_components/localtuya/cover.py", line 191, in status_updated if self._state.isupper(): ^^^^^^^^^^^^^^^^^^^ AttributeError: 'int' object has no attribute 'isupper'
```

### Product Name

2 Way Smart Curtain

### DPS information

```text
"id": "xxxx",
        "key": "xxxx",
        "mac": "xxxx",
        "uuid": "xxxx",
        "sn": "xxxx",
        "category": "clkg",
        "product_name": "2 Way Smart Curtain",
        "product_id": "zqypumy8ot4clzyi",
        "biz_type": 18,
        "model": "qcsc420w",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1509430484182dhmed/c12a90da4fa68c6b7565d94e6401b1bc.jpg",
        "mapping": {
            "1": {
                "code": "control",
                "type": "Enum",
                "values": {
                    "range": [
                        "open",
                        "stop",
                        "close"
                    ]
                }
            },
            "2": {
                "code": "percent_control",
                "type": "Integer",
                "values": {
                    "unit": "%",
                    "min": 0,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            },
            "3": {
                "code": "cur_calibration",
                "type": "Enum",
                "values": {
                    "range": [
                        "start",
                        "end"
                    ]
                }
            },
            "4": {
                "code": "control_2",
                "type": "Enum",
                "values": {
                    "range": [
                        "open",
                        "stop",
                        "close"
                    ]
                }
            },
            "5": {
                "code": "percent_control_2",
                "type": "Integer",
                "values": {
                    "unit": "%",
                    "min": 0,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            },
            "6": {
                "code": "cur_calibration_2",
                "type": "Enum",
                "values": {
                    "range": [
                        "start",
                        "end"
                    ]
                }
            },
            "8": {
                "code": "control_back_mode",
                "type": "Enum",
                "values": {
                    "range": [
                        "forward",
                        "back"
                    ]
                }
            },
            "9": {
                "code": "control_back_mode_2",
                "type": "Enum",
                "values": {
                    "range": [
                        "forward",
                        "back"
                    ]
                }
            },
            "10": {
                "code": "tr_timecon",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 2,
                    "max": 120,
                    "scale": 0,
                    "step": 1
                }
            },
            "11": {
                "code": "tr_timecon_2",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 2,
                    "max": 120,
                    "scale": 0,
                    "step": 1
                }
            },
            "14": {
                "code": "light_mode",
                "type": "Enum",
                "values": {
                    "range": [
                        "relay",
                        "pos",
                        "none"
                    ]
                }
            }
        },
        "ip": "192.168.1.239",
        "version": "3.3"
    }
]
```

### Information about how the device functions

There are 2 shutter relays in the same device. It has 6 buttons. Button to raise shutter 1. Button to raise shutter 2. Button to pause shutter movement 1. Button to pause shutter movement 2. Button to lower shutter 1. And button to lower shutter 2.
![Controlador Persianas](https://github.com/user-attachments/assets/c7bc7bef-2c8d-49fb-9b22-632c3142461f)

**Comment by make-all** [comment]
You are reporting to the wrong integration.
