### ISSUE TITLE
Unable to update 2024.12.2

### ISSUE THREAD

**Issue by HellixFix** [make-all/tuya-local#2716]
### Description

Unable to update. I have 2024.12.1 installed, updater wants 2024.12.0
![image](https://github.com/user-attachments/assets/50a39c63-9448-45fa-a34c-b5acf5955d4f)

### Additional context

Logger: homeassistant.components.websocket_api.http.connection
Zdroj: components/websocket_api/commands.py:245
integrace: Home Assistant WebSocket API (dokumentace, problémy)
První výskyt: 09:02:07 (2 výskyty)
Naposledy logováno: 09:06:20

[140155749270864] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hacs/update.py", line 88, in async_install
    await self.repository.async_download_repository(ref=version or self.latest_version)
  File "/config/custom_components/hacs/repositories/base.py", line 1417, in async_download_repository
    await self._ensure_download_capabilities(ref)
  File "/config/custom_components/hacs/repositories/base.py", line 1407, in _ensure_download_capabilities
    raise HacsException(
custom_components.hacs.exceptions.HacsException: This version requires Home Assistant 2024.12.0 or newer.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 502, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 90, in async_install
    raise HomeAssistantError(exception) from exception
homeassistant.exceptions.HomeAssistantError: This version requires Home Assistant 2024.12.0 or newer.

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
If HACS is unable to determine your HA version correctly, then that is an issue in HACS, not in this integration.
But I suspect HACS is correct, and you are only looking at the tuya-local version number, not the HA version.
