### ISSUE TITLE
Unable to add new integration

### ISSUE THREAD

**Issue by escoand** [make-all/tuya-local#289]
I've updated to the latest version 0.20.4 to add my Beok TOL47.
But it always throws an error:

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 35, in async_step_user
    return await self.async_step_select_type()
  File "/config/custom_components/tuya_local/config_flow.py", line 63, in async_step_select_type
    async for type in self.device.async_possible_types():
  File "/config/custom_components/tuya_local/device.py", line 94, in async_possible_types
    for match in possible_matches(cached_state):
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 752, in possible_matches
    if parsed.matches(dps):
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 122, in matches
    if (d.id not in dps.keys() and not d.optional) or (
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 268, in id
    return str(self._config["id"])
TypeError: string indices must be integers

```

**Comment by kekkutya** [comment]
Try to delete custom_components/tuya_local/devices/avatto_wt100_thermostat.yaml file and add Beok TOL47 again.

**Comment by escoand** [comment]
That worked. Thanks.
