### ISSUE TITLE
Support for WF96L Water level controller

### ISSUE THREAD

**Issue by hasio144** [make-all/tuya-local#381]

**Comment by hasio144** [comment]
It would be awesome to get support for WF96L Tuya Smart Water level controller.

![Screenshot (25)](https://user-images.githubusercontent.com/100513946/218025088-94f3c9d2-1a47-4068-ab16-5b3c75d1e265.png)

Not sure what else of data is needed - just point me right direction and lll dig more.

**Comment by make-all** [comment]
Please provide a sample of the data as it appears in the local protocol, which you will find in the Home Assistant log immediately after attempting to add the device.  The table you have given looks like the UI appearance, so I would have to guess at how it is actually represented in data.

**Comment by hasio144** [comment]
This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:704
Integration: LocalTuya (documentation, issues)
First occurred: February 9, 2023 at 10:35:56 AM (5874 occurrences)
Last logged: 12:10:02 PM

[030...89b] Connect to 192.168.88.33 failed
[634...b2e] Connect to 192.168.88.118 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 186, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.88.33', 6668)

**Comment by hasio144** [comment]
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/tuya_local/device.py:69
Integration: tuya_local (documentation, issues)
First occurred: February 9, 2023 at 10:51:41 AM (18 occurrences)
Last logged: 12:10:25 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 41, in async_step_user
    self.device = await async_test_connection(user_input, self.hass)
  File "/config/custom_components/tuya_local/config_flow.py", line 175, in async_test_connection
    device = TuyaLocalDevice(
  File "/config/custom_components/tuya_local/device.py", line 69, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)
  File "/usr/local/lib/python3.10/site-packages/tinytuya/core.py", line 727, in __init__
    bcast_data = find_device(dev_id)
  File "/usr/local/lib/python3.10/site-packages/tinytuya/core.py", line 524, in find_device
    client.bind(("", UDPPORT))
OSError: [Errno 98] Address in use

**Comment by make-all** [comment]
Set the IP address.  It seems you have both localtuya and tuya_local installed, and localtuya has already claimed the discovery port, which is used when you set the address to "Auto".

**Comment by hasio144** [comment]
Is this log ?

**Comment by make-all** [comment]
I meant the one that comes after the initial communcation is established, when trying to match devices.  Due to the above error, it is not getting that far.

**Comment by hasio144** [comment]
So I added the device but ther is only one switch . Now what do i have to do ?

**Comment by make-all** [comment]
Now look in the log again for a message from tuya_local that mentions DPS

**Comment by hasio144** [comment]
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:44
Integration: Tuya Local (documentation, issues)
First occurred: 12:17:31 PM (4 occurrences)
Last logged: 12:20:32 PM

Device matches mirabella_genio_usb with quality of 17%. DPS: {'updated_at': 1676269949.3453636, '1': True, '2': 100, '3': 50, '101': 25, '103': 100, '104': 0, '105': False, '106': 'OK', '108': True, '109': 0, '110': 'BUSHUI', '111': 0}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches mirabella_genio_usb with quality of 17%. DPS: {'updated_at': 1676270130.7121618, '1': True, '2': 100, '3': 50, '101': 25, '103': 100, '104': 0, '105': False, '106': 'OK', '108': True, '109': 0, '110': 'BUSHUI', '111': 0}

**Comment by hasio144** [comment]
Is this it ?

**Comment by make-all** [comment]
Yes, that was what I was looking for.
