### ISSUE TITLE
Request support for Blitzwolf BW-SH2 humidifier id: 20268362d8bfc0080ec9

### ISSUE THREAD

**Issue by fischrobi** [make-all/tuya-local#410]
# Log Message

# Information about DPS mappings
led colour dps id: 6
countdown dps id: 19
on/off dps id: 20
mist volume dps id: 3

# Product ID : 20268362d8bfc0080ec9

# Information about how the device functions

https://shop.baltrade.eu/3634,Blitzwolf_BW_SH2_intelligent_ultrasonic_air_humidifier_4L_LED_RGB_WiFi
https://www.youtube.com/watch?v=b2dpQ40SBfo

[blitzwolf_bwsh2-humidifier.zip](https://github.com/make-all/tuya-local/files/10731989/blitzwolf_bwsh2-humidifier.zip)

**Comment by make-all** [comment]
Please send the Home Assistant log message from when you attempted to add this device, so I can see the format of each dp in the local protocol.
Also, what is the range of the countdown and mist volume?

**Comment by fischrobi** [comment]
2023-02-18 16:45:02.676 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 142, in async_step_user
    device = await async_test_connection(config, self.hass)
  File "/config/custom_components/tuya_local/config_flow.py", line 175, in async_test_connection
    device = TuyaLocalDevice(
  File "/config/custom_components/tuya_local/device.py", line 69, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)
  File "/usr/local/lib/python3.10/site-packages/tinytuya/core.py", line 732, in __init__
    raise Exception("Unable to find device on network (specify IP address)")
Exception: Unable to find device on network (specify IP address)


Code | Type | Values
-- | -- | --
switch | Boolean | "{true,false}"
spray_volume | Enum | {   "range": [     "grade1",     "grade2",     "grade3",     "grade4",     "grade5",     "grade6",     "sleep"   ] }
work_mode | Enum | {   "range": [     "close",     "purple",     "blue",     "cyan",     "green",     "yellow",     "orange",     "red",     "colour"   ] }
countdown_set | Enum | {   "range": [     "cancel",     "2h",     "4h",     "6h",     "8h",     "10h",     "12h"   ] }

Standard Instruction and status sets are same.

![image](https://user-images.githubusercontent.com/118021596/219874860-a0947ec0-350a-418d-9454-b0fe215ffb3e.png)
![image](https://user-images.githubusercontent.com/118021596/219874911-3b7b245b-f3d2-4b99-ad7b-3ac84c2c139d.png)

**Comment by make-all** [comment]
Please set the IP address, and recapture the logs.

The log message above is saying that it cannot connect to the device, as it cannot find the device address, probably because localtuya is also installed, and has already claimed the discovery ports.

I need the log message from after a connection has been made, to see the format of the local protocol data, which may or may not match the format of the cloud data documented in the API explorer above.

**Comment by fischrobi** [comment]
I added the humidifier with tuya local just it see it as a simle switch

2023-02-19 10:56:04.394 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 69: self._api = tinytuya.Device(dev_id, address, local_key)
2023-02-19 10:56:04.497 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3.
2023-02-19 10:56:06.044 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch with quality of 25%. DPS: {'updated_at': 1676800564.622148, '1': False, '3': 'grade1', '6': 'close', '19': 'cancel'}
2023-02-19 10:56:06.048 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
2023-02-19 10:56:10.318 INFO (MainThread) [homeassistant.setup] Setting up tuya_local
2023-02-19 10:56:10.319 INFO (MainThread) [homeassistant.setup] Setup of domain tuya_local took 0.0 seconds
2023-02-19 10:56:10.322 INFO (MainThread) [custom_components.tuya_local.device] Creating device: 20268362d8bfc0080ec9
2023-02-19 10:56:14.382 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 69: self._api = tinytuya.Device(dev_id, address, local_key)
2023-02-19 10:56:14.508 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tuya_local
2023-02-19 10:56:14.617 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.tuya_local entity: switch.simple_switch
2023-02-19 10:56:14.633 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Simple switch to 3.3.

**Comment by make-all** [comment]
Support added in 2023.2.3

**Comment by fischrobi** [comment]
thanks your support :)

**Comment by fischrobi** [comment]
I had to change a little the config file, becouse the fan speed was not good. It tested, and works well
[blitzwolf_bwsh2-humidifier.txt](https://github.com/make-all/tuya-local/files/10784492/blitzwolf_bwsh2-humidifier.txt)

**Comment by make-all** [comment]
Can you please explain what the problem was with the fan speed?

The changes you made seem to remove it completely.

**Comment by fischrobi** [comment]
It doesnt made any changes. I couldnt set speed. I pushed the slider, but nothing changed. If i select it in the secondary entities, as i putted in, it makes changes.

**Comment by make-all** [comment]
The tests show that setting speed is working fine.  Note that there are only 7 steps, so you need to push the slider at least 15% of the way up to see any change.
