### ISSUE TITLE
Request support for HIPER Weather Station P1

### ISSUE THREAD

**Issue by garry0garry** [make-all/tuya-local#419]
# Log Message

```
      "dps_strings": [
        "101 (value: 782)",
        "102 (value: 20)",
        "103 (value: 246)",
        "104 (value: 87)",
        "106 (value: 244)",
        "107 (value: 88)",
        "110 (value: 1016)",
        "111 (value: mmHg)",
        "112 (value: True)",
        "118 (value: close)",
        "119 (value: False)",
        "120 (value: True)",
        "121 (value: 1)",
        "122 (value: A100B100C200)"
      ],

```
# Information about DPS mappings
```
{
  "code": 2009,
  "msg": "not support this device",
  "success": false,
  "t": 1676484561045,
  "tid": "dec2462fad5b11ed954a4e3668f00a74"
}

```
Developer Tools:
```
code "101" - indoor temperature
code "102" - indoor humidity
code "103" - CH1 remote temperaterue
code "104" - CH1 remote humidity
code "105" - 同步时间
code "106" - CH2 remote temperaterue
code "107" - CH2 remote humidity
code "108" - CH3 remote temperaterue
code "109" - CH3 remote humidity
code "110" - atmosphere
code "111" - atmosphere unit switch
code "112" - temperature unit switch
code "113" - 室内温度告警设置
code "114" - 室内温度告警设置
code "115" - 室内温度告警设置
code "116" - 室内温度告警设置
code "117" - Fault
code "118" - backlight brightness setting
code "119" - time mode
code "120" - date mode switch
code "121" - backlight leading time setting
code "122" - 从设备电量
```

# Product ID

```
"product_id": "q9opgtca8ymbxpqn",
"product_name": "IoT Weather Station P1",

```
# Information about how the device functions

HIPER Weather Station P1, API v3.3

**Comment by garry0garry** [comment]
https://expo.tuya.com/product/596713

**Comment by make-all** [comment]
Support added in 2023.2.3

**Comment by garry0garry** [comment]
Thanks for adding the device!

Tuya Local 2024.8.0, WiFi  "HIPER Weather Station P1"
The following options are available:
```
ir_remote_sensors
yx025wb_aromadiffuser
zigbee_mir_te100ty_climate_sensor
```
![Снимок экрана от 2024-09-08 09-21-12](https://github.com/user-attachments/assets/5eda3ac3-88f2-4776-9739-8788879737d4)
Which option should I choose?

**Comment by garry0garry** [comment]
![изображение](https://github.com/user-attachments/assets/c3bfe859-f9c1-4c90-9144-d24cea8e6740)

**Comment by garry0garry** [comment]
Tuya Local 2024.9.0
Same question. If I select `zigbee_mir_te100ty_climate_sensor`, I get a limited number of sensors with incorrect values.

**Comment by make-all** [comment]
If you included log messages, I might be able to help.

**Comment by garry0garry** [comment]
1. Enable debug from GUI.
2. Add Weather Station.
3. Disable debug from GUI.
4. `cat home-assistant_tuya_local_2024-09-09T04-34-00.193Z.log | grep "tuya_local" > tuya_local.log`
[tuya_local.log](https://github.com/user-attachments/files/16925429/tuya_local.log)

+ Traceback
```
2024-09-09 07:32:59.535 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Step for value is 1 with scale 10
2024-09-09 07:33:03.886 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Test
2024-09-09 07:33:03.886 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3
2024-09-09 07:33:03.930 DEBUG (SyncWorker_0) [custom_components.tuya_local.device] Test refreshed device state: {"devId": "324164718cce4edbc7d7", "dps": {"101": 750, "102": 54, "103": 540, "104": 78, "106": 544, "107": 79, "110": 1010, "111": "mmHg", "112": true, "118": "low", "119": false, "120": true, "121": 1, "122": "A100B100C200"}}
2024-09-09 07:33:03.930 DEBUG (SyncWorker_0) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1725856383.9305973, "101": 750, "102": 54, "103": 540, "104": 78, "106": 544, "107": 79, "110": 1010, "111": "mmHg", "112": true, "118": "low", "119": false, "120": true, "121": 1, "122": "A100B100C200"}
2024-09-09 07:33:03.939 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to walk with args ('/config/custom_components/tuya_local/devices',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 984: for path, dirs, files in walk(_CONFIG_DIR): (offender: /config/custom_components/tuya_local/helpers/device_config.py, line 984: for path, dirs, files in walk(_CONFIG_DIR):), please create a bug report at https://github.com/make-all/tuya-local/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#walk
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 438, in async_step_local
    return await self.async_step_select_type()
  File "/config/custom_components/tuya_local/config_flow.py", line 476, in async_step_select_type
    async for type in self.device.async_possible_types():
  File "/config/custom_components/tuya_local/device.py", line 375, in async_possible_types
    for match in possible:
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 992, in possible_matches
    for cfg in available_configs():
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 984, in available_configs
    for path, dirs, files in walk(_CONFIG_DIR):

2024-09-09 07:33:03.944 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to scandir with args ('/config/custom_components/tuya_local/devices',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 984: for path, dirs, files in walk(_CONFIG_DIR): (offender: <frozen os>, line 366: ?), please create a bug report at https://github.com/make-all/tuya-local/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#scandir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 438, in async_step_local
    return await self.async_step_select_type()
  File "/config/custom_components/tuya_local/config_flow.py", line 476, in async_step_select_type
    async for type in self.device.async_possible_types():
  File "/config/custom_components/tuya_local/device.py", line 375, in async_possible_types
    for match in possible:
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 992, in possible_matches
    for cfg in available_configs():
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 984, in available_configs
    for path, dirs, files in walk(_CONFIG_DIR):

2024-09-09 07:33:03.950 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/tuya_local/devices/9in1_airquality_monitor.yaml',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 230: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 438, in async_step_local
    return await self.async_step_select_type()
  File "/config/custom_components/tuya_local/config_flow.py", line 476, in async_step_select_type
    async for type in self.device.async_possible_types():
  File "/config/custom_components/tuya_local/device.py", line 375, in async_possible_types
    for match in possible:
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 993, in possible_matches
    parsed = TuyaDeviceConfig(cfg)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in __init__
    self._config = load_yaml(filename)

2024-09-09 07:33:03.954 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config 9in1_airquality_monitor.yaml

```

**Comment by make-all** [comment]
There is a lot of noise in that log caused by using an older version of tuya-local with new Home Assistant that has new non-blocking I/O requirements for integrations.  But I was able to get the needed information from line 4 of the log, thank you.

**Comment by garry0garry** [comment]
Do I need to reboot Home Assistant and collect more data? If that helps, I can do that now.

**Comment by make-all** [comment]
If you replace the config file with the one updated just now, or manually make the same changes, then you will be able to test. It will require a reload of the integration.

**Comment by garry0garry** [comment]
Thank you! It worked :-)
There are two errors:
```
- id: 112
type: boolean
name: option
mapping:
- dps_val: false
value: celsius
- dps_val: true
value: fahrenheit
```
true is celsius.

```
      - id: 119
        type: boolean
        name: option
        mapping:
          - dps_val: true
            value: 24h
          - dps_val: false
            value: 12h

```
true is 12h.

**Comment by garry0garry** [comment]
Third error in mmHg. One digit is displayed for any selection.
![Снимок экрана от 2024-09-09 08-56-28](https://github.com/user-attachments/assets/6f934a74-dd76-4815-a8a9-31c361184939) ![Снимок экрана от 2024-09-09 08-57-46](https://github.com/user-attachments/assets/365751e2-ffb8-4b9e-afb3-794eca1d6413) ![Снимок экрана от 2024-09-09 08-57-46](https://github.com/user-attachments/assets/be98e76b-3d6d-4d5e-94b3-918787f0643e)

**Comment by garry0garry** [comment]
And one more thing.
If I change celsius to fahrenheit, the values ​​change, but not temperature_unit. Values ​​in the screenshot with edits:
```
- id: 112
type: boolean
name: option
mapping:
- dps_val: true
value: celsius
- dps_val: false
value: fahrenheit

```
celsius - 16.1 °C
fahrenheit - 61.0 °C
![Снимок экрана от 2024-09-09 09-32-31](https://github.com/user-attachments/assets/3f6b99f7-69c6-44ad-897e-ed0f222ab159) ![Снимок экрана от 2024-09-09 09-32-41](https://github.com/user-attachments/assets/c59bd9fc-6f02-4d6d-bd7e-46104843b01c)

**Comment by make-all** [comment]
I think Home Assistant does not expect units to change on the fly, and only reads them from the sensor on startup.
I am not sure if your 3rd point is related, or the device simply does not really support changing the barometric pressure units.
Or maybe it is just not reporting pressure often enough and the value will update eventually when it gives its next reading.
There could also be some unit conversion happening in the front end which is hiding the changes.

**Comment by garry0garry** [comment]
About the new fix. As far as I understand, there is no need to switch units:
![изображение](https://github.com/user-attachments/assets/a54d1d86-2bdd-46b4-b8fc-403c1ac72139)
If you use this fix, the values ​​will be opposite.

You only need to fix this:
![изображение](https://github.com/user-attachments/assets/f95b72d1-2d81-48db-957c-f8652827ed0b)

Regarding the transfer of values. The device itself is controlled correctly, but not all values ​​are transferred to HA.

In the log:
14:24 Debugging enabled.
14:25 Switching C to F
14:26 Switching mmHg to mBar
14:28 Switching F to C and mBar to mmHg
14:29 Debugging stopped.
[home-assistant_tuya_local_2024-09-09T11-29-42.918Z.log](https://github.com/user-attachments/files/16929861/home-assistant_tuya_local_2024-09-09T11-29-42.918Z.log)

**Comment by make-all** [comment]
The setting of C/F must be consistent, whether the mapping is C = true/F = false, or the opposite.  Making it true in one place and false in another is clearly wrong.

Perhaps you are expecting the difference to show in the HA UI. It will not do that, as HA does unit conversion for the UI according to user preference.  So the correct way to configure the unit in the tuya-local config file is the one that results in a non-changing correct display in the Home Assistant UI.

If I understand correctly, the pressure issue is just that the device is slow sending an update, so HA displays the old numeric value with the newly selected units.

**Comment by garry0garry** [comment]
The thing is that I already tried to change the values ​​of F to C and I was shown the wrong type of units.

Ok. I downloaded your latest fix, rebooted the integration and added the weather station.
Incorrectly shows unit type - fahrenheit instead of celsius. But F and C are correct.

> Perhaps you are expecting the difference to show in the HA UI.

That's exactly what happens. I checked.

**Comment by garry0garry** [comment]
```
        mapping:
          - dps_val: false
            value: celsius
          - dps_val: true
            value: fahrenheit

```
Incorrect.

**Comment by garry0garry** [comment]
It might be something else, but for me the values ​​and value type are displayed correctly only with this configuration:
```
      type: boolean
      name: unit
      mapping:
        - dps_val: true
          value: F
        - dps_val: false
          value: C

```
```
      - id: 112
        type: boolean
        name: option
        mapping:
          - dps_val: true
            value: celsius
          - dps_val: false
            value: fahrenheit

```

**Comment by make-all** [comment]
In the log you posted, dp 101 is definitely coming through as Fahrenheit. And dp 112 is True.  So true is correct for Fahrenheit. Unless the temperature always comes through as Fahrenheit, and dp 112 is only changing the device display.

**Comment by make-all** [comment]
> > Perhaps you are expecting the difference to show in the HA UI.
> 
> That's exactly what happens. I checked.

Nothing should change in the Home Assistant UI if the units are setup correctly. This is because Home Assistant takes whatever value is output by the device and converts it to the units in your user preferences.  If the device config is set up correctly, it will output the correct temperature and correct unit for that temperature, and Home Assistant will convert it to the correct temperature in your display units.

If the device config is not set up correctly, you will see a change in the value displayed in the UI, because the conversion done by HA is incorrect.

**Comment by make-all** [comment]
Rereading the screenshot with the temperature unit change, I wonder if the wrong display is again due to the device not updating the temperature immediately after the unit change, and therefore the old F reading is being displayed with the new C units.  Does it self-correct after some time?

**Comment by garry0garry** [comment]
I ran the test at 17:28 with my configuration (where true = false).
![изображение](https://github.com/user-attachments/assets/689e162f-801c-480d-84e2-60c7dc8aae9a)
17:33
![изображение](https://github.com/user-attachments/assets/f0c53b8e-0043-42c6-860f-feb7da46a16c)

Changing units of measurement. 17:35. The data on the device instantly changed correctly. Home Assistant:
![изображение](https://github.com/user-attachments/assets/b3681585-ee6b-4f8b-80e3-eac758455cac)
17:45
![изображение](https://github.com/user-attachments/assets/fa7b5af2-ed5b-4637-84d4-da7d82088e8c)

When changing units of measurement in Home Assistant, pressure and temperature figures were displayed correctly without changing units of measurement for temperature.

17:47. I change units of measurement. Temperature is displayed correctly in Home Assistant. Pressure value has not changed.
![Снимок экрана от 2024-09-09 17-47-59](https://github.com/user-attachments/assets/7e7c3e9d-9d32-449f-bea3-761ce8025dd1)

**Comment by garry0garry** [comment]
When changing units of measurement in the device, everything changes correctly.

**Comment by make-all** [comment]
I think I see the problem.  The temperature in dp 101 appears to be in Fahrenheit, but others are in Celsius.

It would be useful if you could switch units and send the device diagnostics (from Settings / Devices & Services / Tuya local / menu at right of the device name.

**Comment by garry0garry** [comment]
Before and after switching units of measurement.
[config_entry-tuya_local-01J7BBBDPWY8SPND013X5Y6W9V.json](https://github.com/user-attachments/files/16939569/config_entry-tuya_local-01J7BBBDPWY8SPND013X5Y6W9V.json)
[config_entry-tuya_local-01J7BBBDPWY8SPND013X5Y6W9V(1).json](https://github.com/user-attachments/files/16939570/config_entry-tuya_local-01J7BBBDPWY8SPND013X5Y6W9V.1.json)

**Comment by garry0garry** [comment]
Just in case, I'll repeat. The correct code for controlling a **physical** device:

```
      - id: 112
        type: boolean
        name: option
        mapping:
          - dps_val: true
            value: celsius
          - dps_val: false
            value: fahrenheit
```

**Comment by garry0garry** [comment]
About this patch. I confirm that Configuration panel entitys correctly control the physical device.

Please tell me, are there no more changes planned? If not, I will use Tuya Local with this patch instead of LocalTuya integration. I like your implementation better.

**Comment by make-all** [comment]
I don't think there are any more changes planned, unless you find other issues.

**Comment by garry0garry** [comment]
Thank you very much! I didn't find any other issues.
