### ISSUE TITLE
Can't add  Warmme-ET6A Termostat

### ISSUE THREAD

**Issue by mihaiivanovici** [make-all/tuya-local#544]
When i try to add Warmme-ET6A, i got the error Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.
When i try to connect via tuya-cli, i got  error below. The termostat is the same as the Saswell c16, and the c16 i was able to add and is working perfectly.

 events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: Error from socket: read ECONNRESET
    at Socket.<anonymous> (C:\Users\mihai\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\tuyapi\index.js:627:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on TuyaDevice instance at:
    at Socket.<anonymous> (C:\Users\mihai\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\tuyapi\index.js:627:12)
    at Socket.emit (events.js:314:20)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

From Tuya api explorer, i can request the device and i get the result:
{
  "result": {
    "active_time": 1677916044,
    "category": "qn",
    "category_name": "Heater",
    "create_time": 1652069386,
    "gateway_id": "",
    "icon": "smart/icon/15367350215n2y57gek36_0.png",
    "id": "",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "ET－6AW",
    "name": "baie et1 dreapta",
    "online": true,
    "owner_id": "",
    "product_id": "",
    "product_name": "WiFi Thermostat",
    "sub": false,
    "time_zone": "+02:00",
    "update_time": 1678006526,
    "uuid": ""
  },
  "success": true,
  "t": ,
  "tid": ""
}

**Comment by make-all** [comment]
Please see discussion #522 for potential solutions.
