### ISSUE TITLE
TOMPD 63A Breaker I,A and P Unreachable after upgrade

### ISSUE THREAD

**Issue by dance12r** [make-all/tuya-local#631]
**Device:** tompd 63A breaker

**Issue:**
V,A and P Unreachable after upgrade up to 2023.4.1

**Device diagnostics:**
[tuya_local-8efbcb4bdf021dcf1f7326cf746b0f12-Breaker-1845b3de8bbbae32a83639bcd937b26f.json.txt](https://github.com/make-all/tuya-local/files/11292828/tuya_local-8efbcb4bdf021dcf1f7326cf746b0f12-Breaker-1845b3de8bbbae32a83639bcd937b26f.json.txt)

**Some errors from HA logs:**
```
Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/helpers/device_config.py:387
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 08:50:15 (3 occurrences)
Last logged: 09:06:15

Breaker receive loop terminated by exception argument should be a bytes-like object or ASCII string, not 'NoneType'
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 200, in receive_loop
    entity.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 721, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/home
[tuya_local-8efbcb4bdf021dcf1f7326cf746b0f12-Breaker-1845b3de8bbbae32a83639bcd937b26f.json.txt](https://github.com/make-all/tuya-local/files/11292832/tuya_local-8efbcb4bdf021dcf1f7326cf746b0f12-Breaker-1845b3de8bbbae32a83639bcd937b26f.json.txt)
assistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 470, in state
    value = self.native_value
  File "/config/custom_components/tuya_local/sensor.py", line 72, in native_value
    return self._sensor_dps.get_value(self._device)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 363, in get_value
    bytevalue = self.decoded_value(device)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 387, in decoded_value
    return b64decode(v)
  File "/usr/local/lib/python3.10/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/local/lib/python3.10/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```
**Screenshots:**
![Screenshot 2023-04-21 at 09 06 11](https://user-images.githubusercontent.com/29065090/233555455-50409c09-b1af-45fc-8c22-8cfebd793f2f.png)
![Screenshot 2023-04-21 at 09 06 46](https://user-images.githubusercontent.com/29065090/233555457-c4bdaa8f-76c8-45f6-bb8c-768d8870ae1f.png)

**Comment by dance12r** [comment]
Updated form git - all looks good
