### ISSUE TITLE
Request support for Tuya-Local Orion Grid Connect Bluetooth Lock via WiFi hub

### ISSUE THREAD

**Issue by jaydisc** [make-all/tuya-local#654]
Issue #162 seems to be how lock support came to be, and based on the description, I assume it's this lock (https://www.bunnings.com.au/orion-grid-connect-smart-wi-fi-entrance-lock_p0330511, which has built-in WiFi). I bought another Orion Grid Connect lock, but a Bluetooth one (https://www.bunnings.com.au/orion-grid-connect-smart-door-handle-lock_p0330508) and their Bluetooth (to WiFi) hub (https://www.bunnings.com.au/orion-grid-connect-smart-bluetooth-hub-with-socket_p0330509)

I have had IoT.Tuya set up for ages. I used `python -m tinytuya wizard` to get the keys. This is the output of the devices.json the generates:

```
[
    {
        "name": "Orion Lock",
        "id": "bf7916jzauojjy4q",
        "key": "d662327ad73d7de2",
        "mac": "DC:23:4E:A5:2B:CF",
        "uuid": "268b97205e021907",
        "category": "ms",
        "product_name": "",
        "product_id": "a6nttc41",
        "biz_type": 0,
        "model": "DL021HA",
        "sub": true,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/99fe0d9b7b8dfac27ce56ce6f2682d65.png",
        "node_id": "268b97205e021907",
        "parent": ""
    },
    {
        "name": "Orion Hub",
        "id": "bf7e1781ca46f16806tnsv",
        "key": "d662327ad73d7de2",
        "mac": "38:1f:8d:c0:5e:de",
        "uuid": "814b612b7f07dd47",
        "category": "cz",
        "product_name": "SG121HA",
        "product_id": "qhoybrozfhcenkyh",
        "biz_type": 0,
        "model": "SG121HA",
        "sub": true,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/9ceffdb41c5f3b7e52b25cef42df1228.png",
        "parent": ""
    },
    {
        "name": "Arlec Fan",
        "id": "10835277e8db849189d1",
        "key": "9d42bfa2551e4d0b",
        "mac": "e8:db:84:91:89:d1",
        "uuid": "10835277e8db849189d1",
        "sn": "100031445020B5",
        "category": "fs",
        "product_name": "APDC4501BHA",
        "product_id": "yl9xhvmeauwdmvss",
        "biz_type": 0,
        "model": "APDC4501BHA",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/f999684aae9c495405c73d7384e0e87f.png"
    }
]
```
(The fan is integrated via the plugin and works wonderfully)

I noticed that both the Lock and the Hub have different id's, but have the same key.

Using IoT API Explorer → Get Device Specification Attribute, I get the following for the Lock:

```
{
  "result": {
    "category": "ms",
    "functions": [
      {
        "code": "unlock_method_create",
        "dp_id": 1,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "unlock_method_delete",
        "dp_id": 2,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "automatic_lock",
        "dp_id": 33,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "synch_method",
        "dp_id": 54,
        "type": "Raw",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "unlock_method_create",
        "dp_id": 1,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "unlock_method_delete",
        "dp_id": 2,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "residual_electricity",
        "dp_id": 8,
        "type": "Integer",
        "values": "{\"min\":-1,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "unlock_fingerprint",
        "dp_id": 12,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "unlock_ble",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "automatic_lock",
        "dp_id": 33,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "synch_method",
        "dp_id": 54,
        "type": "Raw",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1682569550783,
  "tid": "974fd3a4e4b311edbff9f2ce989a5212"
}
```

Interestingly, when I use the same query for the Hub, I get:

```
{
  "code": 2009,
  "msg": "not support this device",
  "success": false,
  "t": 1682569641014,
  "tid": "cd1a5410e4b311eda8900e8ee93f159e"
}
```

When I add the Lock in HA (using id = bf7916jzauojjy4q), I get offered a Simple Switch or Simple Switch with Timer. Upon adding to HA, there is no reaction in any device when toggling the switch.

When I add the Hub (which has an integrated power socket), I get the same matches, but in this case, when I toggle the switch, the hub's socket properly toggles.

I captured the output when adding both devices to HA, and I actually don't see any difference:

Lock:

```
2023-04-27 14:14:11.234 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Test
2023-04-27 14:14:11.235 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3
2023-04-27 14:14:11.308 DEBUG (SyncWorker_20) [custom_components.tuya_local.device] Test refreshed device state: {"dps": {"1": true, "9": 0, "38": "memory", "40": "relay", "41": false, "42": "", "43": ""}}
2023-04-27 14:14:11.309 DEBUG (SyncWorker_20) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1682568851.3088422, "1": true, "9": 0, "38": "memory", "40": "relay", "41": false, "42": "", "43": ""}
<snip>
2023-04-27 14:14:12.978 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config simple_switch.yaml
2023-04-27 14:14:12.979 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Matched config for Simple switch
2023-04-27 14:14:12.981 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config simple_switch_timer.yaml
2023-04-27 14:14:12.985 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config simple_switch_timerv2.yaml
2023-04-27 14:14:12.985 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Matched config for Simple switch with timer
<snip>
2023-04-27 14:14:13.350 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch_timerv2 with quality of 43%. DPS: {"updated_at": 1682568851.3088422, "1": true, "9": 0, "38": "memory", "40": "relay", "41": false, "42": "", "43": ""}
2023-04-27 14:14:13.356 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

Hub:

```
2023-04-27 14:15:39.681 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Test
2023-04-27 14:15:39.681 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3
2023-04-27 14:15:39.785 DEBUG (SyncWorker_18) [custom_components.tuya_local.device] Test refreshed device state: {"dps": {"1": true, "9": 0, "38": "memory", "40": "relay", "41": false, "42": "", "43": ""}}
2023-04-27 14:15:39.785 DEBUG (SyncWorker_18) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1682568939.7852914, "1": true, "9": 0, "38": "memory", "40": "relay", "41": false, "42": "", "43": ""}
<snip>
2023-04-27 14:15:41.499 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config simple_switch.yaml
2023-04-27 14:15:41.500 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Matched config for Simple switch
2023-04-27 14:15:41.502 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config simple_switch_timer.yaml
2023-04-27 14:15:41.506 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config simple_switch_timerv2.yaml
2023-04-27 14:15:41.507 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Matched config for Simple switch with timer
<snip>
2023-04-27 14:15:41.867 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch_timerv2 with quality of 43%. DPS: {"updated_at": 1682568939.7852914, "1": true, "9": 0, "38": "memory", "40": "relay", "41": false, "42": "", "43": ""}
2023-04-27 14:15:41.870 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/

```

My first assumption, is that hubs and their devices simply aren't supported, so HA isn't even getting a chance at configuring the lock, but I thought I'd collect the info just in case it was of value. Thank you.

**Comment by make-all** [comment]
You are right, hubs and sub devices are not yet supported, but a pull request was submitted yesterday, so after the issues with it are fixed it should not be too far away from being ready to go.

**Comment by make-all** [comment]
I don't think that log is for the lock. It seems to match some kind of smartplug.

Prior to the recent addition of sub device support (as yet unreleased), I would not expect to get anything in the log for the lock, as it needs to go via the hub (IP address would be the same as the hub).

**Comment by jaydisc** [comment]
Hi, I've gotten around to testing all of this again. I've tried entering it numerous ways, but the times it goes through, this is the output:

```[core-ssh ~]$ 2023-05-25 15:41:13.826 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Test
2023-05-25 15:41:13.826 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3
2023-05-25 15:41:13.911 DEBUG (SyncWorker_9) [custom_components.tuya_local.device] Test refreshed device state: {"dps": {"8": 93, "33": false}, "cid": "268b97205e021907", "device": "Non-JSON: (Device( 'bf92e1nv04nozktm', address=None, local_key='', dev_type='default', connection_timeout=5, version=3.3, persist=False, cid='268b97205e021907', parent='bf92e1nv04nozktm', children={} ))"}
2023-05-25 15:41:13.911 DEBUG (SyncWorker_9) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1684993273.911662, "8": 93, "33": false}
2023-05-25 15:41:13.914 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config abalon_bcm700d_curtain.yaml
2023-05-25 15:41:13.918 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config agl_ultramagic_lock.yaml
<snipped out lots of uneventful devices load>
2023-05-25 15:41:14.702 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config zym100_presence_sensor.yaml
2023-05-25 15:41:14.702 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1684993273.911662, "8": 93, "33": false}
2023-05-25 15:41:14.703 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

I've done these recent tests on HA 2023.5.4, TuyaLocal 2023.5.1.

I tried using the devices.json file that tinytuna generates as well as the API Explorer at Tuya Cloud to get the IDs/Keys.

Here's devices.json (the lock is on top… the hub on bottom):

```[
    {
        "name": "DL021HA",
        "id": "bf92xxxxxxxxxxx",
        "key": "xxxxxxxxxxxxxx",
        "mac": "xxxxxxxxxxxxxx",
        "uuid": "xxxxxxxxxxxxxxxxxx",
        "category": "ms",
        "product_name": "",
        "product_id": "a6nttc41",
        "biz_type": 0,
        "model": "DL021HA",
        "sub": true,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/99fe0d9b7b8dfac27ce56ce6f2682d65.png",
        "node_id": "268bxxxxxxxxxxxxx",
        "parent": ""
    },
    {
        "name": "SG121HA",
        "id": "bff9xxxxxxxxxxxxx",
        "key": "xxxxxxxxxxxxxx",
        "mac": "xxxxxxxxxxxxxxx",
        "uuid": "xxxxxxxxxxxxxxx",
        "category": "cz",
        "product_name": "SG121HA",
        "product_id": "qhoybrozfhcenkyh",
        "biz_type": 0,
        "model": "SG121HA",
        "sub": true,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/9ceffdb41c5f3b7e52b25cef42df1228.png",
        "parent": ""
    }
]
```

The HA Integration now asks for "Sub device ID (for devices connected via gateway)".

So, I tried:

ID: bf92xxxxxxxxxxx
Sub ID: 268bxxxxxxxxxxxxx (the "node_id" from the lock record)

Result: "Sorry, there is no support for this device."

ID: bff9xxxxxxxxxxxxx ("id" of the Hub)
Sub ID: bf92xxxxxxxxxxx ("id" of the Lock)

Result: "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect."

ID: bff9xxxxxxxxxxxxx ("id" of the Hub)
Sub ID: 268bxxxxxxxxxxxxx (the "node_id" from the Lock)

Result: "Sorry, there is no support for this device."

I could try more combinations, but those seemed the only logical ones. Could you please confirm what should be going where, and/or if there's some other output I can provide? Thank you.

**Comment by make-all** [comment]
It looks like just some dps need to be marked optional, as they are not reporting when the door has not been recently unlocked.

**Comment by jaydisc** [comment]
I tried unlocking the door and trying again, but no difference. Can you please confirm which ID should be going where?

**Comment by make-all** [comment]
Try redownloading the integration, and select "main" as the version to install if you want to test the latest change.

**Comment by jaydisc** [comment]
OK. Progress. I have a Lock Device in Home Assistant, which has an "Auto-Lock" switch under Configuration. Toggling that in HA properly updates "Passage Mode" in the Tuya app. Changing it on either device is quickly reflected on the other.

BUT, there is also a Lock entity. However, pressing Unlock or Lock fails without feedback. The following is in the log:

```
[core-ssh ~]$ 2023-05-25 17:29:29.713 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140217949207712] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 980, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 106, in _async_unlock
    await entity.async_unlock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/tuya_local/lock.py", line 117, in async_unlock
    raise NotImplementedError()
NotImplementedError
2023-05-25 17:29:31.645 DEBUG (MainThread) [custom_components.tuya_local.device] Tuya Bluetooth Hub received {"1": false, "9": 0, "38": "memory", "40": "relay", "41": false, "42": "", "43": "", "full_poll": true}
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] option values: ['On', 'Off', 'Last state']
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple switch with timer: Mapped dps 38 value from memory to Last state
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple switch with timer: Mapped dps 38 value from memory to Last state
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple switch with timer: Mapped dps 38 value from memory to Last state
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple switch with timer: Mapped dps 38 value from memory to Last state
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] option values: ['On', 'Off', 'Last state']
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple switch with timer: Mapped dps 38 value from memory to Last state
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple switch with timer: Mapped dps 38 value from memory to Last state
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Considering mapping for step of value
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Step for value is 60 with scale 60
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple switch with timer: Mapped dps 9 value from 0 to 0.0
2023-05-25 17:29:31.646 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple switch with timer: Mapped dps 9 value from 0 to 0.0
2023-05-25 17:29:31.746 DEBUG (MainThread) [custom_components.tuya_local.device] Orion BLE lock received {"8": 83, "12": 0, "19": 1, "33": true, "full_poll": true}
2023-05-25 17:29:31.747 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] No mapping for sensor, unable to determine valid values
2023-05-25 17:29:31.747 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] No mapping for sensor, unable to determine valid values

```

**Comment by make-all** [comment]
That is expected, the device did not provide any obvious way to unlock via the local network.  But the lock entity should report what credential was used to unlock the door, so at least you will have logging.
If you can figure out the remote unlocking, you can give the details so the config can be updated - many locks have a request response format, so someone has to press a doorbell button, then the door can be unlocked remotely within 30s or so, or there may be some that require a PIN code for remote unlocking, as protection against someone tapping into your local network and unlocking the door.

**Comment by jaydisc** [comment]
OK, that's good to know. Thank you. I will have a dig.

I do see the "changed_by" attribute, currently "changed_by: App #1". I've tried unlocking the lock the two ways I can… app and fingerprint. In the Tuya app, I see the last unlock referred to as "Unlock with Mobile Phone" or "Unlock with fingerprint", but the "changed_by" attribute doesn't appear to change from "App #1".

**Comment by make-all** [comment]
If you update again, I have tried to fix the reporting.  Likely now the "changed_by" will only appear briefly after an unlock, but it might be in the LogBook, and automations triggered on it will work so you could use an automation to update a Helper entity if you want to track the last unlock long term.

**Comment by jaydisc** [comment]
OK. I'm running b9d978a now. I still haven't witnessed any change in changed_by, which still has value of "App #1". Doesn't appear to appear in logbook. Battery level seems to be working well too.

<img width="917" alt="Screenshot 2023-05-25 at 7 39 10 pm" src="https://github.com/make-all/tuya-local/assets/1192605/55e1c4cc-c545-41ca-9653-f6320dd7beb9">

<img width="517" alt="image" src="https://github.com/make-all/tuya-local/assets/1192605/7a5e02b7-c5a2-48c9-8943-aa115188126d">

**Comment by jaydisc** [comment]
So, the "Auto-Lock" (or "Passage Mode" as Orion calls it) really kinds of acts like a Locked/Unlocked control. If Auto-Lock is on, the handle is locked. If it's off, it isn't. The Unlock function in the Tuya app is only just a temporary unlock-for-a-few-seconds. I'm not sure it's even worth pursuing that, when we have Lock/Unlock functionality just from the Auto-Lock switch.

 I have set up the following Template Lock based exclusively on the auto-lock switch:

```
lock:
  - platform: template
    name: Office Hallway Lock
    unique_id: A797C836-9470-4AB2-A304-291D8B9F1D5F
    value_template: "{{ is_state('switch.office_hallway_lock_auto_lock', 'on') }}"
    lock:
      service: switch.turn_on
      target:
        entity_id: switch.office_hallway_lock_auto_lock
    unlock:
      service: switch.turn_off
      target:
        entity_id: switch.office_hallway_lock_auto_lock
```

I initially tried to just use the simple, HA-integrated method of Switch-as-Lock, but unfortunately, it's inverted, and I don't believe the Helper has an easy way of reversing it, so Template Lock to the rescue. Super simple, and works awesomely.

Thank you so much for your attention and effort. I'm going to go order another two!

**Comment by jaydisc** [comment]
Hi, I thought I'd re-open this (please tell me if this should be a new issue instead) because I have not been able to get the unlocking of the door to be a trigger an automation as you suggested above. I've tried using the 'unlocking' and 'unlocked' events to no avail (no traces either):

```
trigger:
  - platform: device
    device_id: 3edd6a86e47973b87580caf1d3284f95
    domain: lock
    entity_id: lock.office_lock_hallway
    type: unlocking
```

```
trigger:
  - platform: device
    device_id: 3edd6a86e47973b87580caf1d3284f95
    domain: lock
    entity_id: lock.office_lock_hallway
    type: unlocked
```

Also, am I able to switch back to the main/master branch?

Thank you.

**Comment by make-all** [comment]
Since 2023.6.0 was released yesterday, I don't think there is currently any reason to switch back to "main".  But in general, if you select "Redownload" in HACS, you can choose a specific version to install, from a list that includes "main" along with recent releases.
