### ISSUE TITLE
"Failed to call service fan/set_percentage." Error Message

### ISSUE THREAD

**Issue by writemike** [make-all/tuya-local#677]
**Describe the bug**
I'm using Tuya Local to control a Deta Smart Fan Speed Controller+Light Switch(Model 6914HA) recognized as a deta_fan.yaml device. The light is working perfectly, but the 3-speed fan is having a similar issue as #561 which refers to a 6-speed fan. The issue occurs with the first level (1, Low in HA) of fan speed. When the fan goes from off to level 1, Home Assistant produces the error message "Failed to call service fan/set_percentage. speed(33) must be between 33.33333333333333336 and 100.0" and the fan does not come on. I also get a similar message when trying to select the off button in the Lovelace HA Button, from any other fan speed level. It is slightly different with "Failed to call service fan/set_percentage. speed(0) must be between 33.33333333333333336 and 100.0".

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:
Add Deta Smart Fan Speed Controller+Light Switch(Model 6914HA) to HA via Tuya Local. Use Lovelace fan control card to select level 1, low speed. The second message will be produced when the fan is in level 3, high speed (Default speed when fan is turned on) and you attempt to select the off button in the same Lovelace fan control card.

**Expected behavior**
Using the Lovelace fan control card, I expect the fan to start running at level 1, slow, when the equivalent button is pressed. I also expect the fan to turn off when you attempt to select the off button from any speed level.

**Additional context**
Appears to be a math rounding error when the fan's speed is calculated and reported to/from Home Assistant to/from Tuya Local.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
```{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.5.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.11",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Australia/Sydney",
    "os_name": "Linux",
    "os_version": "6.1.25",
    "supervisor": "2023.04.1",
    "host_os": "Home Assistant OS 10.1",
    "docker_version": "23.0.3",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "garbage_collection": {
      "version": "4.10.2",
      "requirements": [
        "python-dateutil>=2.8.2"
      ]
    },
    "tuya_local": {
      "version": "2022.4.2",
      "requirements": [
        "pycryptodome~=3.17",
        "tinytuya==1.12.5"
      ]
    },
    "bureau_of_meteorology": {
      "version": "1.1.19",
      "requirements": [
        "iso8601"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "emporia_vue": {
      "version": "0.8.1",
      "requirements": [
        "pyemvue==0.16.2"
      ]
    },
    "tapo": {
      "version": "1.6.1",
      "requirements": [
        "plugp100==2.5.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.5"
    ],
    "version": "2022.4.2",
    "is_built_in": false
  },
  "data": {
    "name": "Master Bedroom fan controller",
    "type": "deta_fan",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1683266768.6912327,
      "1": true,
      "3": "2",
      "9": false,
      "101": true,
      "102": "1",
      "103": "1"
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Master Bedroom fan controller",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "fan.master_bedroom_fan_controller",
            "state": "on",
            "attributes": {
              "preset_modes": [],
              "percentage": 66.66666666666667,
              "percentage_step": 33.333333333333336,
              "preset_mode": null,
              "timer": 1,
              "friendly_name": "Master Bedroom fan controller",
              "supported_features": 1
            },
            "last_changed": "2023-05-05T05:56:03.574698+00:00",
            "last_updated": "2023-05-05T05:57:48.802112+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.master_bedroom_fan_controller_master",
            "state": "on",
            "attributes": {
              "device_class": "switch",
              "friendly_name": "Master Bedroom fan controller Master"
            },
            "last_changed": "2023-05-05T05:56:03.572997+00:00",
            "last_updated": "2023-05-05T05:56:03.572997+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "light.master_bedroom_fan_controller",
            "state": "off",
            "attributes": {
              "supported_color_modes": [
                "onoff"
              ],
              "timer": 1,
              "friendly_name": "Master Bedroom fan controller",
              "supported_features": 0
            },
            "last_changed": "2023-05-05T05:00:53.179601+00:00",
            "last_updated": "2023-05-05T05:00:53.179601+00:00"
          }
        }
      ]
    }
  }
}
```

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tuya_local/helpers/device_config.py:824
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:50:51 pm (24 occurrences)
Last logged: 3:57:53 pm

[139853402891808] speed (33) must be between 33.333333333333336 and 100.0
[139853402891808] speed (0) must be between 33.333333333333336 and 100.0
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 981, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/tuya_local/fan.py", line 119, in async_set_percentage
    await self._speed_dps.async_set_value(self._device, percentage)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 423, in async_set_value
    settings = self.get_values_to_set(device, value)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 824, in get_values_to_set
    raise ValueError(f"{self.name} ({value}) must be between {mn} and {mx}")
ValueError: speed (33) must be between 33.333333333333336 and 100.0
```

Thank you!

**Comment by writemike** [comment]
Thank you @make-all ! I made the manual change to deta_fan.yaml and tested. The fix makes the fan work as expected.

**Comment by cjba850** [comment]
The list of options when adding the device is all incorrect guesses..

<img width="365" height="514" alt="Image" src="https://github.com/user-attachments/assets/ae091598-1ad2-402b-b632-e1d54554f288" />
