### ISSUE TITLE
 LoraTap RF + WiFi Curtain Switch not supported anymore

### ISSUE THREAD

**Issue by elninosi** [make-all/tuya-local#704]
After Tuya Local update to 2023.4.2 device is no longer being supported.

**Describe the bug**
Device was first shown as unavailable, after consultation it was suggested to re-add the device.

**To Reproduce**
1) Add new device
![slika](https://github.com/make-all/tuya-local/assets/11082452/5ace1b0b-488e-4426-b502-46d876d6d1f5)
2) Error: 
![slika](https://github.com/make-all/tuya-local/assets/11082452/29377477-ccda-41f6-a1a3-c1fff2450ec6)

**Expected behavior**
Device should be added as it was before 2023.4.2 Tuya Local update.
**Additional context**
Log:
```
Log: 2023-05-08 21:41:16.664 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self.api = tinytuya.Device(dev_id, address, local_key)
2023-05-08 21:41:21.295 WARNING (MainThread) [homeassistant.util.async] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self.api = tinytuya.Device(dev_id, address, local_key)
2023-05-08 21:41:22.477 WARNING (MainThread) [homeassistant.util.async] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self.api = tinytuya.Device(dev_id, address, local_key)
2023-05-08 21:41:27.340 WARNING (MainThread) [homeassistant.util.async] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self.api = tinytuya.Device(dev_id, address, local_key)
2023-05-08 21:41:29.384 WARNING (MainThread) [homeassistant.util.async] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self._api = tinytuya.Device(dev_id, address, local_key)
2023-05-08 21:41:47.490 ERROR (MainThread) [custom_components.tuya_local.device] <class 'Exception'>: Unable to find device on network (specify IP address) while initialising device 4433632370039f89db10
2023-05-08 21:41:47.491 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Simple curtain switch for tuya_local
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/tuya_local/init.py", line 236, in async_setup_entry
setup_device(hass, config)
File "/config/custom_components/tuya_local/device.py", line 575, in setup_device
device = TuyaLocalDevice(
File "/config/custom_components/tuya_local/device.py", line 74, in init
raise e
File "/config/custom_components/tuya_local/device.py", line 66, in init
self._api = tinytuya.Device(dev_id, address, local_key)
File "/usr/local/lib/python3.10/site-packages/tinytuya/core.py", line 789, in init
raise Exception("Unable to find device on network (specify IP address)")
Exception: Unable to find device on network (specify IP address)
```

**Comment by make-all** [comment]
Your IP address is set to Auto.  There are circumstances where that will not work, so please try setting the IP address before filing it as a bug.

**Comment by elninosi** [comment]
After numerous tries entity was added with the following settings (20x tries or more):
![slika](https://github.com/make-all/tuya-local/assets/11082452/8999f929-f645-4425-8f7e-daef2a0c4a5f)
But when the device is added no entities are created, log is the following:
```
2023-05-12 18:44:20.773 ERROR (MainThread) [homeassistant.components.cover] Error while setting up tuya_local platform for cover
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tuya_local/cover.py", line 21, in async_setup_entry
await async_tuya_setup_platform(
File "/config/custom_components/tuya_local/helpers/config.py", line 28, in async_tuya_setup_platform
data[ecfg.config_id] = entity_class(device, ecfg)
File "/config/custom_components/tuya_local/cover.py", line 52, in __init__
if "stop" in self._control_dp.values(self._device):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by make-all** [comment]
Please enable debug logging for all of tuya_local as instructed above, and post the logs using 2023.5.1 that was just released.

**Comment by elninosi** [comment]
I removed the device and added it again after update. Device is now added on first try.
![slika](https://github.com/make-all/tuya-local/assets/11082452/2dbb26df-bd95-4504-ad7a-6992d967137d)
After confirmation 1 device & 1 entity are added.
![slika](https://github.com/make-all/tuya-local/assets/11082452/6124cc7b-6ea8-4ace-901e-407cba497289)
But entity can't be controlled:
![slika](https://github.com/make-all/tuya-local/assets/11082452/90f6618d-f8a7-4522-af84-f4e9759ab68c)


After adding debugging option I can se the following in the logs:
```
2023-05-21 15:39:06.521 DEBUG (SyncWorker_1) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.521 DEBUG (SyncWorker_1) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.522 DEBUG (SyncWorker_1) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.522 DEBUG (SyncWorker_1) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.522 DEBUG (SyncWorker_1) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.522 DEBUG (SyncWorker_1) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.522 DEBUG (SyncWorker_1) [custom_components.tuya_local.device] Living Room Blinds refreshed device state: {"devId": "4433632370039f89db10", "dps": {"1": "3"}}
2023-05-21 15:39:06.522 DEBUG (SyncWorker_1) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1684676346.521453, "1": "3"}
2023-05-21 15:39:06.532 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.532 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.532 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.533 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.533 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.533 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Simple curtain switch: Mapped dps 1 value from 3 to stop
2023-05-21 15:39:06.599 DEBUG (SyncWorker_3) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2023-05-21 15:39:06.599 DEBUG (SyncWorker_3) [custom_components.tuya_local.helpers.device_config] Considering mapping for range of value
2023-05-21 15:39:06.599 DEBUG (SyncWorker_3) [custom_components.tuya_local.helpers.device_config] Considering mapping for step of value
```

`2023-05-21 15:47:24.271 DEBUG (MainThread) [custom_components.tuya_local.device] Living Room Blinds received {"1": "3", "full_poll": true}`

**Comment by elninosi** [comment]
@make-all can we somehow revert the code for this device to the point in time where it worked, e.g. when it was first implemented in Tuya Local?

**Comment by make-all** [comment]
Your device is not the only device that needs to be supported by the cover integration.  This device is so simple and without useful feedback that it will never work perfectly.

I'm not even sure what your current problem with it is, as this bug was filed about a communication problem, which seems to have been resolved.  I think you need to file another report clearly stating the problem, keeping in mind that the only feedback we are getting from the device is that it is stopped, so keep your expectations about how it is reported realistic.
