### ISSUE TITLE
Error in Goldair GPPH620 heater "ValueError: invalid literal for int() with base 10: 'auto'"

### ISSUE THREAD

**Issue by nzdjb** [make-all/tuya-local#762]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Goldair GPPH620 (1.5kW) heater doesn't present data. The device responds to commands issued from home assistant (turn on heating, turn off heating) but the sensor data doesn't display.

**To Reproduce**
With a Goldair GPPH620, set it up in Home Assistant using Tuya Local.
Use protocol version 3.4 as this seems to be the only one that works.
Observe that no sensor data is reported.

**Expected behavior**
Sensor data should be reported.

**Additional context**
This has been working fine with both a GPPH610 and GPPH630 for several years, as well as with a GPPH610 purchased at the same time as the GPPH620.

There is an error in the HomeAssistant logs:
```Logger: custom_components.tuya_local.device
Source: components/sensor/__init__.py:583
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: May 29, 2023 at 8:26:46 PM (1 occurrences)
Last logged: May 29, 2023 at 8:26:46 PM
Guest Bedroom Heater receive loop terminated by exception Sensor sensor.guest_bedroom_heater_power_level has device class power_factor, state class None unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: auto (<class 'str'>)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'auto'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 218, in receive_loop
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.guest_bedroom_heater_power_level has device class power_factor, state class None unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: auto (<class 'str'>)```

The diagnostics from the device are:
```{
  "home_assistant": {
    "installation_type": "Unknown",
    "version": "2023.5.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.11",
    "docker": false,
    "arch": "x86_64",
    "timezone": "Pacific/Auckland",
    "os_name": "Linux",
    "os_version": "5.10.0-22-amd64",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "metlink": {
      "version": "1.0.8",
      "requirements": [
        "isodate~=0.6.1"
      ]
    },
    "localtuya": {
      "version": "5.2.0",
      "requirements": []
    },
    "goldair_climate": {
      "version": "0.1.3",
      "requirements": [
        "pycryptodome~=3.9",
        "pytuya~=7.0.5"
      ]
    },
    "tuya_local": {
      "version": "2022.5.1",
      "requirements": [
        "pycryptodome~=3.17",
        "tinytuya==1.12.7"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.7"
    ],
    "version": "2022.5.1",
    "is_built_in": false
  },
  "data": {
    "name": "Guest Bedroom Heater",
    "type": "goldair_gpph_heater",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.4,
    "api_version_set": 3.4,
    "api_version_used": 3.4,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1685348806.195129,
      "1": false,
      "2": 25,
      "3": 17,
      "4": "C",
      "6": false,
      "12": 0,
      "101": "auto",
      "102": 0,
      "103": false,
      "104": true,
      "105": "auto",
      "106": 21
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Guest Bedroom Heater",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.guest_bedroom_heater_child_lock",
            "state": "unavailable",
            "attributes": {
              "friendly_name": "Guest Bedroom Heater Child lock",
              "supported_features": 0
            },
            "last_changed": "2023-05-29T08:26:44.436001+00:00",
            "last_updated": "2023-05-29T08:26:44.436001+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.guest_bedroom_heater",
            "state": "unavailable",
            "attributes": {
              "hvac_modes": [
                "heat",
                "off"
              ],
              "min_temp": 5,
              "max_temp": 35,
              "target_temp_step": 1.0,
              "preset_modes": [
                "comfort",
                "away",
                "eco"
              ],
              "swing_modes": [
                "2",
                "5",
                "4",
                "1",
                "Stop",
                "3",
                "Auto"
              ],
              "friendly_name": "Guest Bedroom Heater",
              "supported_features": 49
            },
            "last_changed": "2023-05-29T08:26:44.200782+00:00",
            "last_updated": "2023-05-29T08:26:44.200782+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "min",
          "state": {
            "entity_id": "number.guest_bedroom_heater_timer",
            "state": "unavailable",
            "attributes": {
              "min": 0,
              "max": 1440,
              "step": 60.0,
              "mode": "auto",
              "unit_of_measurement": "min",
              "icon": "mdi:timer",
              "friendly_name": "Guest Bedroom Heater Timer"
            },
            "last_changed": "2023-05-29T08:26:44.269852+00:00",
            "last_updated": "2023-05-29T08:26:44.269852+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "light.guest_bedroom_heater_display",
            "state": "unavailable",
            "attributes": {
              "supported_color_modes": [
                "onoff"
              ],
              "friendly_name": "Guest Bedroom Heater Display",
              "supported_features": 0
            },
            "last_changed": "2023-05-29T08:26:44.435865+00:00",
            "last_updated": "2023-05-29T08:26:44.435865+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "power_factor",
          "icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.guest_bedroom_heater_power_level",
            "state": "unavailable",
            "attributes": {
              "unit_of_measurement": "%",
              "device_class": "power_factor",
              "icon": "mdi:signal",
              "friendly_name": "Guest Bedroom Heater Power level"
            },
            "last_changed": "2023-05-29T08:26:44.153494+00:00",
            "last_updated": "2023-05-29T08:26:44.153494+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.guest_bedroom_heater_error",
            "state": "off",
            "attributes": {
              "device_class": "problem",
              "friendly_name": "Guest Bedroom Heater Error"
            },
            "last_changed": "2023-05-29T08:26:46.195473+00:00",
            "last_updated": "2023-05-29T08:26:46.195473+00:00"
          }
        }
      ]
    }
  }
}```

Workaround:

Set the power level to something other than "AUTO" using the official app, then delete and re-add the device.

**Comment by nzdjb** [comment]
A little more information, this may be a version thing. My GPPH620 reports version "2.6.3" on the main module, while the older two report "1.0.2" and the newer GPPH610 reports "1.1.1".
