### ISSUE TITLE
Light Device will no longer connect that previously worked

### ISSUE THREAD

**Issue by DataGeek-AU** [make-all/tuya-local#788]
I am unable to connect to Tuya Devices that I had previously working without issue in Tuya Local after I updated to the latest version. I have removed the devices, restarted HA and tried to re-add without success. Any ideas on what else to try would be greatly appreciated. 

I am able to add other devices. And issue seems to only affect my light entities. All light entities are no longer available since updating. The ones still in the device list are showing in home assistant as unknown. And I see the same unexpected pay load error when open up that devices How Assistant page where it try's to get the status.

on the latest HA 2023.6.1

**Error:**
Unable to Connect to device
![Add Device](https://github.com/make-all/tuya-local/assets/47727356/906c705c-8745-477c-a329-dbe10aa316cc)

**Versions:**
Home Assistant - 2023.6.1
Tuya Local - 2023.5.2

**Log:**
2023-06-12 17:06:03.412 DEBUG (SyncWorker_7) [tinytuya.core] _recv_all(): no data? b''
2023-06-12 17:06:03.412 DEBUG (SyncWorker_7) [tinytuya.core] Error decoding received data - read retry 1/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 1008, in _send_receive
    rmsg = self._receive()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 898, in _receive
    data = self._recv_all( min_len )
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 879, in _recv_all
    raise DecodeError('No data received - connection closed?')
tinytuya.core.DecodeError: No data received - connection closed?
2023-06-12 17:06:03.413 DEBUG (SyncWorker_7) [tinytuya.core] ERROR Unexpected Payload from Device - 904 - payload: null
2023-06-12 17:06:03.413 DEBUG (SyncWorker_7) [tinytuya.core] status() received data={'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
2023-06-12 17:06:03.414 DEBUG (SyncWorker_7) [tinytuya.core] Detected dps: {}
2023-06-12 17:06:03.414 DEBUG (SyncWorker_21) [tinytuya.core] _recv_all(): no data? b''
2023-06-12 17:06:03.414 DEBUG (SyncWorker_21) [tinytuya.core] Error decoding received data - read retry 1/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 1008, in _send_receive
    rmsg = self._receive()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 898, in _receive
    data = self._recv_all( min_len )
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 879, in _recv_all
    raise DecodeError('No data received - connection closed?')
tinytuya.core.DecodeError: No data received - connection closed?
2023-06-12 17:06:03.415 DEBUG (SyncWorker_21) [tinytuya.core] ERROR Unexpected Payload from Device - 904 - payload: null
2023-06-12 17:06:03.415 DEBUG (SyncWorker_21) [tinytuya.core] status() received data={'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
2023-06-12 17:06:03.416 DEBUG (SyncWorker_21) [tinytuya.core] status() entry (dev_type is device22)
2023-06-12 17:06:03.416 DEBUG (SyncWorker_21) [tinytuya.core] building command 10 payload=b'{"devId":"bf3e676313df1d101dvqg4","uid":"bf3e676313df1d101dvqg4","t":"1686553563","dps":{"1":null,"11":null,"12":null,"13":null,"14":null,"15":null,"16":null,"17":null,"18":null,"19":null,"20":null}}'
2023-06-12 17:06:03.419 DEBUG (SyncWorker_15) [tinytuya.core] status() entry (dev_type is device22)
2023-06-12 17:06:03.419 DEBUG (SyncWorker_15) [tinytuya.core] building command 10 payload=b'{"devId":"bf2ea27633ac2f5fbdafdv","uid":"bf2ea27633ac2f5fbdafdv","t":"1686553563","dps":{}}'
2023-06-12 17:06:03.473 DEBUG (SyncWorker_14) [tinytuya.core] building command 9 payload=b'{"gwId":"bf9eae4301d409901ejlbv","devId":"bf9eae4301d409901ejlbv"}'
2023-06-12 17:06:03.473 DEBUG (SyncWorker_14) [tinytuya.core] sending payload
2023-06-12 17:06:03.474 DEBUG (SyncWorker_14) [tinytuya.core] payload encrypted=b'000055aa00000115000000090000005800ed2ee222d8bf2bda0f461143be2c9dc84a5c3fd43f66c9dbea72dc362cb29c6503c619b98f05af22d36dd0122b649e58812da26c6f00a687173aa89d639e78dc48f79a5f6260d17f9dd82f6fe7ba179c3b19a40000aa55'
2023-06-12 17:06:03.485 DEBUG (SyncWorker_14) [tinytuya.core] heartbeat received data=None
2023-06-12 17:06:03.498 DEBUG (SyncWorker_15) [tinytuya.core] sending payload
2023-06-12 17:06:03.498 DEBUG (SyncWorker_15) [tinytuya.core] payload encrypted=b'000055aa000008c50000000d00000077332e320000000000000000000000005eb5003595b3c3748d59c2e894831ba1be04ca508b9b1b62e5bd4c8c6e83de4a3022ccb7365a98583efb0a73dbf1550dbbbf25c0be3763ce18e8a9a88585abfc9131f1bef875010c232f8d2501eab677d123aadda9e7b2ca4151335cb2047b59d38901680000aa55'

**Comment by DataGeek-AU** [comment]
This effected all my light entities in tuya local.

I have managed to fix it after trying a few things. Including manually installing tuya local to ensure I had all the correct files from the upgrade.

I had to physically power off and on all of the light devices and they started to respond in Home Assistant Again. Didn't need to do that with any other device (switches and Fans) Just the lights.
