### ISSUE TITLE
Trying (and failing) to add Eberg Cooly C35HD support

### ISSUE THREAD

**Issue by ishioni** [make-all/tuya-local#99]
I've decoded most needed dpcodes so far, and generated the following yaml, but the integrations crashes on config flow for me. I can't really spot where i'm making the error. Any pointers?

```yaml
name: Eberg Cooly C35HD
primary_entity:
  entity: climate
  dps:
    - id: 1
      name: power
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:hvac-off"
          icon_priority: 1
      hidden: true
    - id: 4
      name: unknown_4
      type: integer
    - id: 5
      name: hvac_mode
      type: string
      mapping:
        - dps_val: 3
          icon: "mdi:snowflake"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: cool
        - dps_val: 4
          icon: "mdi:fan"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
              value: "off"
            - dps_val: true
              value: fan_only
        - dps_val: 2
          icon: "mdi:water"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: dry
        - dps_val: 1
          icon: "mdi:fire"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: heat
    - id: 6
      name: temperature
      type: integer
      mapping:
        - constraint: temperature_unit
          conditions:
            - dps_val: true
              range:
                min: 13
                max: 32
            - dps_val: false
              range:
                min: 55
                max: 90
    - id: 8
      name: fan_mode
      type: string
      mapping:
        - dps_val: 0
          value: "auto"
        - dps_val: 1
          value: "low"
        - dps_val: 2
          value: "medium"
        - dps_val: 3
          value: "high"
    - id: 10
      name: temperature_unit
      type: boolean
      mapping:
        - dps_val: true
          value: "C"
        - dps_val: false
          value: "F"
    - id: 13
      type: integer
      name: unknown_13
    - id: 14
      type: integer
      name: unknown_14
    - id: 15
      type: integer
      name: unknown_15
    - id: 16
      name: swing_mode
      type: boolean
      mapping:
        - dps_val: true
          value: "vertical"
        - dps_val: false
          value: "off"
    - id: 17
      type: boolean
      name: unknown_15
    - id: 18
      type: int
      name: unknown_18
    - id: 19
      type: boolean
      name: unknown_19
```

```
2021-12-21 23:04:25 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/tuya_local/config_flow.py", line 35, in async_step_user
return await self.async_step_select_type()
File "/config/custom_components/tuya_local/config_flow.py", line 63, in async_step_select_type
async for type in self.device.async_possible_types():
File "/config/custom_components/tuya_local/device.py", line 94, in async_possible_types
for match in possible_matches(cached_state):
File "/config/custom_components/tuya_local/helpers/device_config.py", line 620, in possible_matches
if parsed.matches(dps):
File "/config/custom_components/tuya_local/helpers/device_config.py", line 89, in matches
if d.id not in dps.keys() or not _typematch(d.type, dps[d.id]):
File "/config/custom_components/tuya_local/helpers/device_config.py", line 23, in _typematch
if isinstance(value, type):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by make-all** [comment]
```
    - id: 18
      type: int
      name: unknown_18
```
The type here should be `integer`.

Hopefully this helps get it going so you can figure out some more of the values.

**Comment by make-all** [comment]
If you have access to the Tuya Developer portal (which you may have set up to get your local keys, or to try your device using the default tuya integration), there is an API Explorer, which you can use to get more information about your device.  The most useful is under "Smart Home Management System" / "Device Control" / "Get Device Specification Attribute", which provides a complete listing of all the attributes accessible via the cloud API, including thier local IDs.

**Comment by ishioni** [comment]
@make-all functionality wise i've gotten everything that the tuya api offers, except for schedules. I just didn't have time to sit down and fix this, thanks for the pointer with int/integer. Once I do you can expect a PR. I didn't know you can get local IDs out of the tuya api, I'll take a look into it. I'm going local exactly because the tuya api doesn't offer some functionality on my device (the swing mode), and trips up every integration because tuya specifies c_f be 'c' or 'f' but my device returns true/false

**Comment by make-all** [comment]
There should be current_temperature readings as well (probably in C and F).  The app also exposes timers, but these can be replaced by automations within Home Assistant, so not really a high priority, I agree.

**Comment by ishioni** [comment]
> There should be current_temperature readings as well (probably in C and F).
There are 2, one for C the other for F

**Comment by ishioni** [comment]
@make-all Ok, I've fixed it, this is what I'm now working with, and it almost works:

```
name: Eberg Cooly C35HD
primary_entity:
  entity: climate
  dps:
    - id: 1
      name: power
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:hvac-off"
          icon_priority: 1
      hidden: true
    - id: 4
      name: unknown_4
      type: integer
    - id: 5
      name: hvac_mode
      type: string
      mapping:
        - dps_val: 3
          icon: "mdi:snowflake"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: cool
        - dps_val: 4
          icon: "mdi:fan"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
              value: "off"
            - dps_val: true
              value: fan_only
        - dps_val: 2
          icon: "mdi:water"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: dry
        - dps_val: 1
          icon: "mdi:fire"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: heat
    - id: 6
      name: temperature
      type: integer
      mapping:
        - constraint: temperature_unit
          conditions:
            - dps_val: false
              range:
                min: 13
                max: 32
            - dps_val: true
              range:
                min: 55
                max: 90
    - id: 8
      name: fan_mode
      type: string
      mapping:
        - dps_val: 0
          value: "auto"
        - dps_val: 1
          value: "low"
        - dps_val: 2
          value: "medium"
        - dps_val: 3
          value: "high"
    - id: 10
      name: temperature_unit
      type: boolean
      mapping:
        - dps_val: true
          value: "C"
        - dps_val: false
          value: "F"
    - id: 13
      type: integer
      name: unknown_13
    - id: 14
      type: integer
      name: unknown_14
    - id: 15
      type: integer
      name: unknown_15
    - id: 16
      name: swing_mode
      type: boolean
      mapping:
        - dps_val: true
          value: "vertical"
        - dps_val: false
          value: "off"
    - id: 17
      type: boolean
      name: unknown_15
    - id: 18
      type: integer
      name: unknown_18
    - id: 19
      type: boolean
      name: unknown_19
```

Except the temperature is off. The unit is set to C, it should give me 25 as per tuya-cli. These are my notes as to dpcodes:

```
1: switch on/off
4: unknown int
5: mode string (1 - heat, 2 - dry, 3 - cool, 4 - fan)
6: temp_c int
8: speed string (0 - auto,1 - low, 2 - medium, 3 - high)
10: c_f boolean (true - celsius)
13: unknown int
14: unknown int
15: unknown int
16: swing (true - vertical) boolean
17: unknown bool
18: temp_f int
19: unknown bool
```

And this is the output of tuya-cli
```
{
  devId: '4875044784cca893e465',
  dps: {
    '1': true,
    '4': 0,
    '5': '4',
    '6': 25,
    '8': '1',
    '10': false,
    '13': 0,
    '14': 0,
    '15': 0,
    '16': false,
    '17': false,
    '18': 78,
    '19': false
  }
}
```

But home assistant gives me -3.9 C
<img width="379" alt="Screenshot 2022-01-08 at 12 00 51" src="https://user-images.githubusercontent.com/50323052/148641661-c9557e08-5eba-4adf-abfe-7d014fac2f7b.png">
9

**Comment by ishioni** [comment]
PR in #113
